-- ============================================================
-- Plaza Boat College — Seed e-learning BM I
-- AUTOGEGENEREERD door scripts/gen-seed.mjs — niet handmatig bewerken.
-- Bron: data.js  ·  181 vragen
-- Idempotent: on conflict (id) do update. Voer uit NA migrations/0002_elearning.sql.
-- ============================================================

-- ---- Vragenbank (BM I) ----
insert into questions (id, course_code, module_seq, ref, stem, opts, correct, expl) values
  ('bm1:B12-001', 'BM-I', 2, 'B12.1', 'Merchant Shipping Notices and equivalent official notices are carried so the master can:', '["Decorate the wheelhouse","Stay current with safety information, requirements and warnings applicable to the vessel","Sell them ashore","Use them as scrap paper"]'::jsonb, 1, 'Answer B. Official notices convey mandatory requirements, guidance and safety information; the master keeps and applies those relevant to the vessel.'),
  ('bm1:B12-002', 'BM-I', 2, 'B12.2', 'The applicable regulations (e.g. the SCV Code) should be carried on board so that:', '["They look official","The master can reference the rules the vessel must comply with","They satisfy passengers","They replace the chart"]'::jsonb, 1, 'Answer B. Carrying the relevant regulations lets the master check and demonstrate compliance with the requirements that apply to the vessel.'),
  ('bm1:B12-003', 'BM-I', 2, 'B12.3', 'Charts and tide tables carried on board must be:', '["Any edition, however old","Of the correct area and corrected up to date (or a current edition) for the intended passage","Photocopies only","Optional if a plotter is fitted"]'::jsonb, 1, 'Answer B. Navigation charts and tide tables must cover the area and be up to date/corrected; electronic aids supplement but do not excuse carrying correct navigational publications.'),
  ('bm1:B16-001', 'BM-I', 2, 'B16.1', 'The deck log should be prepared and kept so that it:', '["Is written up from memory at season end","Provides a contemporaneous, ink record of times, positions, courses, weather and events, ready for inspection","Contains only fuel costs","Is filled in by passengers"]'::jsonb, 1, 'Answer B. The deck log is prepared in advance and completed contemporaneously in ink; it records the navigation and operation of the vessel and must be available for inspection.'),
  ('bm1:B16-002', 'BM-I', 2, 'B16.2', 'Standard procedure on leaving port includes:', '["Departing without checks","Pre-departure checks, confirming numbers on board, obtaining clearance where required and logging the time of departure","Telling no one","Leaving the gangway rigged"]'::jsonb, 1, 'Answer B. On departure the master completes pre-departure and safety checks, confirms persons on board, obtains any required port clearance and records the time of sailing.'),
  ('bm1:B16-003', 'BM-I', 2, 'B16.2', 'On entering a port the master should:', '["Maintain full speed to the berth","Observe local rules and speed limits, monitor the working VHF channel, follow buoyage/traffic schemes and contact port control if required","Ignore other traffic","Anchor in the fairway"]'::jsonb, 1, 'Answer B. Entering port, comply with local regulations and speed limits, keep a listening watch on the port channel, follow the buoyage and contact port control as required.'),
  ('bm1:B16-004', 'BM-I', 2, 'B16.3', 'A crew list is maintained so that:', '["It is never needed","Those on board are known to the master and authorities, aiding accounting in an emergency and meeting reporting requirements","It records passengers'' meals","It lists only the master"]'::jsonb, 1, 'Answer B. The crew list records who is on board for safe manning, emergency headcount and the reporting requirements of the authorities.'),
  ('bm1:B16-005', 'BM-I', 2, 'B16.4', 'A passenger list / accurate headcount is important because:', '["It is optional","It ensures the certified number is not exceeded and enables a full account of everyone in an emergency or evacuation","It is only for ticketing","It tells the chef numbers"]'::jsonb, 1, 'Answer B. An accurate passenger count keeps within the certified limit and is essential to account for all persons during and after an emergency (VIII/7).'),
  ('bm1:B16-006', 'BM-I', 2, 'B16.5', 'Carrying valid vessel insurance matters because:', '["It is decorative","It provides cover for liabilities (including third-party/passenger) and is often a legal/operational requirement","It replaces the Safety Certificate","It is only for racing"]'::jsonb, 1, 'Answer B. Adequate insurance (including third-party and passenger liability) protects against the financial consequences of a casualty and is commonly required to operate commercially.'),
  ('bm1:B16-007', 'BM-I', 2, 'B16.6', 'A Safety Management System (SMS) provides:', '["A wage scale","Documented procedures for safe operation, maintenance, emergencies and reporting, with defined responsibilities","A sales brochure","The tide tables"]'::jsonb, 1, 'Answer B. An SMS sets out documented procedures and responsibilities for safe operation, planned maintenance, emergency response and incident reporting.'),
  ('bm1:B16-008', 'BM-I', 2, 'B16.6', 'Following an incident, the SMS typically requires the master to:', '["Forget about it","Record and report the incident so causes can be reviewed and recurrence prevented","Hide it from the operator","Blame the crew verbally only"]'::jsonb, 1, 'Answer B. The SMS requires incidents and near-misses to be recorded and reported so the operator can investigate, learn and improve procedures.'),
  ('bm1:B3-001', 'BM-I', 2, 'B3.1', 'On loss of life or serious injury to a person on board, the master must:', '["Continue the voyage and mention it on return","Preserve the scene as far as safety allows, render aid, and report to the authorities as soon as possible","Tell no one","Discharge the crew involved"]'::jsonb, 1, 'Answer B. The master renders aid, preserves evidence so far as safe, records the facts and reports the casualty to the competent authority without delay.'),
  ('bm1:B3-002', 'BM-I', 2, 'B3.2', 'The principal certificate that a small commercial vessel must carry is the:', '["VHF licence only","SCV Safety Certificate (Reg. I/15)","Insurance schedule only","Crew agreement only"]'::jsonb, 1, 'Answer B. The vessel must carry a valid SCV Safety Certificate issued under Regulation I/15, confirming it meets the Code for its area and service.'),
  ('bm1:B3-003', 'BM-I', 2, 'B3.3', 'A vessel may operate only within:', '["Whatever area the master prefers","The area and conditions stated on its Safety Certificate and the master''s licence — the narrower governs","Any area within 24 hours of port","Any area in daylight"]'::jsonb, 1, 'Answer B. Operation is limited to the area/conditions on the Safety Certificate and to the grade of the master''s licence; the narrower of the two governs.'),
  ('bm1:B3-004', 'BM-I', 2, 'B3.3', 'A Grade 1 master in command of a vessel certified only for sheltered day operation may:', '["Take her to sea overnight because the master is highly qualified","Only operate her within the sheltered, day limits of her certificate","Ignore the certificate limits","Upgrade the certificate himself"]'::jsonb, 1, 'Answer B. The certificate limits the vessel regardless of the master''s grade; she may only be operated within her certified area and conditions.'),
  ('bm1:B9-001', 'BM-I', 2, 'B9.1', 'Safe access to and from the vessel means providing:', '["A single rope to climb","A properly rigged, secured gangway/passerelle or safe step with handholds and adequate lighting","A jump from the quay","Access only at high water"]'::jsonb, 1, 'Answer B. The master must provide safe means of access — a secured gangway or safe step with handhold and lighting — to prevent falls boarding or leaving.'),
  ('bm1:B9-002', 'BM-I', 2, 'B9.2', 'Safe working practices on deck include:', '["Working alone in all conditions","Using PPE, non-slip footwear, keeping clear of bights of line, and briefing the crew on the task","Removing all guards","Working at full speed regardless"]'::jsonb, 1, 'Answer B. Safe working practices include suitable PPE and footwear, keeping clear of snap-back and bights, securing the task and briefing the crew on hazards.'),
  ('bm1:B9-003', 'BM-I', 2, 'B9.3', 'The SCV Safety Certificate (I/15) certifies that:', '["The crew are paid","The vessel complies with the Code for its area and category and may operate within stated limits","The vessel is insured","The master holds a licence"]'::jsonb, 1, 'Answer B. The Safety Certificate (I/15) records that the vessel meets the Code''s requirements for its category and area and states the limits within which she may operate.'),
  ('bm1:B9-004', 'BM-I', 2, 'B9.4', 'Basic security awareness on board includes:', '["Ignoring strangers","Controlling access to the vessel, securing valuables and being alert to suspicious behaviour or items","Leaving the vessel open","Posting the schedule publicly"]'::jsonb, 1, 'Answer B. Basic security means controlling who boards, securing the vessel and valuables, and reporting suspicious persons, packages or activity.'),
  ('bm1:B10-001', 'BM-I', 3, 'B10.1', 'Before departure the master should obtain the latest forecast from:', '["Memory of yesterday''s weather","Official meteorological services via radio, NAVTEX, VHF, TV or internet","The colour of the sky only","Other passengers"]'::jsonb, 1, 'Answer B. The master uses official met services (radio, NAVTEX, VHF broadcasts, internet) to get the latest forecast and warnings before and during a passage.'),
  ('bm1:B10-002', 'BM-I', 3, 'B10.3', 'A rapid fall in barometric pressure usually indicates:', '["Improving, settled weather","Approaching deteriorating weather, often with strengthening wind","No change","Fog only"]'::jsonb, 1, 'Answer B. A rapid pressure fall signals an approaching depression/front and usually strengthening wind and worsening conditions.'),
  ('bm1:B10-003', 'BM-I', 3, 'B10.3', 'Signs of approaching bad weather at sea include:', '["Clearing skies and steady glass","Lowering/thickening cloud, increasing swell, freshening and backing/veering wind and a falling barometer","Calm with no cloud","Rising barometer only"]'::jsonb, 1, 'Answer B. Thickening high cloud, increasing swell, a shifting and freshening wind and a falling barometer together warn of deteriorating weather.'),
  ('bm1:B10-004', 'BM-I', 3, 'B10.2', 'Local effects such as sea and land breezes and acceleration around headlands matter because they:', '["Never affect small craft","Can produce wind and sea conditions markedly different from the general forecast","Only affect large ships","Cancel the tide"]'::jsonb, 1, 'Answer B. Local topography (headlands, valleys, sea/land breezes) can strengthen or shift the wind and raise steep seas beyond what the area forecast suggests.'),
  ('bm1:B10-005', 'BM-I', 3, 'B10.1', 'A gale warning broadcast means:', '["Winds of force 5 are forecast","Winds of at least force 8 (or gusts) are forecast in the area — consider delaying or sheltering","Fog is forecast","The sea is flat"]'::jsonb, 1, 'Answer B. A gale warning indicates winds of force 8 or more (or severe gusts) are expected; the master should consider postponing or seeking shelter.'),
  ('bm1:B14-001', 'BM-I', 3, 'B14.1', 'Marine radar is primarily used to:', '["Listen to weather forecasts","Detect and range other vessels and the coastline, and help assess risk of collision","Measure depth","Receive GPS position"]'::jsonb, 1, 'Answer B. Radar shows the range and bearing of targets and the coast, aiding collision avoidance and navigation, especially in poor visibility.'),
  ('bm1:B14-002', 'BM-I', 3, 'B14.1', 'AIS (Automatic Identification System) provides:', '["Depth under the keel","Identity, position, course and speed of equipped vessels","The tidal stream","Engine temperature"]'::jsonb, 1, 'Answer B. AIS exchanges vessel identity, position, course, speed and other data between equipped ships and shore, aiding identification and collision avoidance.'),
  ('bm1:B14-003', 'BM-I', 3, 'B14.1', 'An echo sounder measures:', '["Distance to the shore","Depth of water under the transducer","Speed over ground","The variation"]'::jsonb, 1, 'Answer B. The echo sounder measures the depth of water beneath the transducer by timing a sound pulse to the seabed and back.'),
  ('bm1:B14-004', 'BM-I', 3, 'B14.1', 'A GPS/GNSS receiver provides primarily:', '["Depth","Position (latitude and longitude), and from successive fixes COG and SOG","Wind speed","Engine hours"]'::jsonb, 1, 'Answer B. Satellite navigation gives position; from changing positions it derives course and speed over the ground.'),
  ('bm1:B14-005', 'BM-I', 3, 'B14.1', 'A prudent Grade 1 master treats electronic aids as:', '["Infallible and a replacement for the chart and lookout","Valuable aids to be cross-checked against the chart, the lookout and other methods","Only for fine weather","Decorative"]'::jsonb, 1, 'Answer B. Electronic aids can fail or mislead (datum, signal loss, clutter); they must be cross-checked against the chart, visual fixes and a proper lookout.'),
  ('bm1:B14-006', 'BM-I', 3, 'B14.1', 'A limitation of radar the operator must remember is that:', '["It shows colours of buoys","Small craft, low targets and objects in clutter/rain may not show up reliably","It always detects everything","It measures depth"]'::jsonb, 1, 'Answer B. Radar can miss small or low targets and those hidden in sea/rain clutter; it must not replace a visual and audible lookout.'),
  ('bm1:B14-007', 'BM-I', 3, 'B14.1', 'GPS position should be cross-checked because:', '["It is never wrong","Wrong chart datum, signal loss or input error can put the displayed position adrift of the real one","It measures the tide","It only works in port"]'::jsonb, 1, 'Answer B. GPS can mislead through datum mismatch, signal interruption or operator error; confirm against the chart and visual fixes.'),
  ('bm1:B5-001', 'BM-I', 3, 'B5.3', 'A position fix from the intersection of two or more position lines is most reliable when the lines:', '["Cross at a very fine angle","Cross at a good angle (near 90 degrees) — three lines giving a small cocked hat","Are parallel","Are all from the same object"]'::jsonb, 1, 'Answer B. A good fix has position lines crossing near right angles; three lines giving a small cocked hat give confidence in the position.'),
  ('bm1:B5-002', 'BM-I', 3, 'B5.3', 'A ''running fix'' is used when:', '["Two objects are visible at once","Only one object is available — a bearing is taken, the run transferred, and a second bearing of the same object gives a fix","No objects are visible","The GPS has failed permanently"]'::jsonb, 1, 'Answer B. A running fix transfers an earlier position line forward by the vessel''s run (course and distance) to cross a later bearing of the same object.'),
  ('bm1:B5-003', 'BM-I', 3, 'B5.4', 'To find the course to steer to make good a desired track when a current is setting the vessel, you:', '["Steer the track and ignore the current","Construct a vector triangle: lay off the track, the tide/current vector, and resolve for the course to steer at your boat speed","Add the current to your speed","Steer downstream of the track"]'::jsonb, 1, 'Answer B. Draw the tidal/current vector from the start, set the boat-speed radius onto the required track line, and the resulting heading is the course to steer.'),
  ('bm1:B5-004', 'BM-I', 3, 'B5.4', 'Leeway is:', '["The slack in the steering","The vessel''s sideways drift to leeward caused by wind, applied as an angle off the heading","The difference between true and magnetic north","The tidal set"]'::jsonb, 1, 'Answer B. Leeway is the angle between the heading and the actual water track caused by wind pushing the vessel to leeward; it is applied to the course to steer.'),
  ('bm1:B5-005', 'BM-I', 3, 'B5.4', 'To allow for leeway when steering, you apply the leeway angle:', '["Downwind of the desired track","Up-wind of the track so the vessel is blown back onto track","It makes no difference","Only to the GPS course"]'::jsonb, 1, 'Answer B. You steer up-wind of the desired track by the leeway angle so that the wind sets the vessel back onto the intended track.'),
  ('bm1:B5-006', 'BM-I', 3, 'B5.5', 'Variation is the angle between:', '["True north and magnetic north at a place","The heading and the track","The lubber line and the card","Compass north and magnetic north"]'::jsonb, 0, 'Answer A. Variation is the angle between true and magnetic north for a given place and year, shown on the chart''s compass rose.'),
  ('bm1:B5-007', 'BM-I', 3, 'B5.5', 'Deviation is the compass error caused by:', '["The earth''s magnetic field only","The vessel''s own magnetism acting on the compass, varying with the ship''s heading","Tidal streams","The chart datum"]'::jsonb, 1, 'Answer B. Deviation is the error caused by the vessel''s own iron/electrics; it changes with the vessel''s heading and is read from the deviation card.'),
  ('bm1:B5-008', 'BM-I', 3, 'B5.5', 'To convert a compass course to a true course you apply, in order:', '["Variation then deviation","Deviation (for that heading) then variation","Leeway only","Nothing — they are the same"]'::jsonb, 1, 'Answer B. Compass to true: apply deviation (for that heading) to get magnetic, then variation to get true.'),
  ('bm1:B5-009', 'BM-I', 3, 'B5.5', 'With variation 5W and deviation 2E on the steered heading, the total compass error is:', '["7W","3W","3E","7E"]'::jsonb, 1, 'Answer B. Combine: 5W and 2E give a net 3W total error (east cancels part of the west error).'),
  ('bm1:B5-010', 'BM-I', 3, 'B5.2', 'A tidal diamond on a chart gives:', '["The depth of water","The direction and rate of tidal stream at that position for each hour relative to HW","The variation","The position of a wreck"]'::jsonb, 1, 'Answer B. A tidal diamond keys to a table giving the set (direction) and rate (speed) of the tidal stream for each hour before/after high water at the reference port.'),
  ('bm1:B5-011', 'BM-I', 3, 'B5.2', 'Tidal stream rates in the diamond tables are usually given for:', '["Springs and neaps","Daylight only","One fixed value all year","Full moon only"]'::jsonb, 0, 'Answer A. The diamond tables list spring and neap rates; you interpolate for the day''s range between them.'),
  ('bm1:B5-012', 'BM-I', 3, 'B5.6', 'The four stages of a passage (voyage) plan are:', '["Appraisal, Planning, Execution, Monitoring","Look, point, go","Speed, fuel, food","Anchor, moor, depart"]'::jsonb, 0, 'Answer A. Good passage planning follows Appraisal, Planning, Execution and Monitoring: gather information, plan the route, carry it out and continuously check progress.'),
  ('bm1:B5-013', 'BM-I', 3, 'B5.6', 'A safe passage plan should include:', '["Only the start and finish","Courses, distances, hazards, clearing bearings, tidal windows, contingency/abort points and fuel","Just the GPS waypoints","Only the weather forecast"]'::jsonb, 1, 'Answer B. A plan covers the route, courses and distances, dangers and clearing lines, tidal heights/streams, no-go areas, contingencies and fuel/endurance.'),
  ('bm1:B5-014', 'BM-I', 3, 'B5.1', 'On a chart, the anchor symbol indicates:', '["A wreck","A recommended anchorage","A lighthouse","A tide gauge"]'::jsonb, 1, 'Answer B. The anchor symbol marks an anchorage area; chart symbols are interpreted via the chart legend (INT 1 / Chart 5011).'),
  ('bm1:B5-015', 'BM-I', 3, 'B5.1', 'Charted depths (soundings) are normally given relative to:', '["Mean high water","Chart datum (approximately the lowest astronomical tide)","The deck of your vessel","Mean sea level only"]'::jsonb, 1, 'Answer B. Soundings are reduced to chart datum (close to LAT), so actual depth = charted depth + height of tide above datum.'),
  ('bm1:B5-016', 'BM-I', 3, 'B5.6', 'To find the depth of water at a given time, you:', '["Read the charted sounding directly","Add the height of tide for that time to the charted sounding","Subtract the variation","Use the deviation card"]'::jsonb, 1, 'Answer B. Depth at a given time = charted sounding + height of tide above chart datum at that time (from the tide tables/curve).'),
  ('bm1:B5-017', 'BM-I', 3, 'B5.6', 'A clearing bearing is used to:', '["Set the radar range","Keep the vessel clear of a known danger by ensuring a bearing of a fixed mark stays beyond a safe limit","Measure speed","Correct deviation"]'::jsonb, 1, 'Answer B. A clearing bearing of a fixed mark defines a line that, kept on the safe side, ensures the vessel stays clear of a charted danger.'),
  ('bm1:B5-018', 'BM-I', 3, 'B5.5', 'Parallel rules (or a plotter) are used on the chart to:', '["Measure distance only","Transfer a bearing/course to or from the compass rose without changing its direction","Measure depth","Find the variation table"]'::jsonb, 1, 'Answer B. Parallel rules walk a line across the chart keeping its direction, so a course or bearing can be read off the compass rose or laid from a position.'),
  ('bm1:B5-019', 'BM-I', 3, 'B5.5', 'Dividers on a chart are used to:', '["Draw the course line","Measure distance against the latitude scale","Apply leeway","Read the tide table"]'::jsonb, 1, 'Answer B. Dividers measure distance, read against the latitude scale at the side of the chart (1 minute of latitude = 1 nautical mile).'),
  ('bm1:B2-001', 'BM-I', 4, 'Rule 5', 'COLREG Rule 5 requires that:', '["A proper lookout is kept by sight and hearing and all available means at all times","A lookout is only needed at night","Radar replaces the human lookout","A lookout is optional in good visibility"]'::jsonb, 0, 'Answer A. Rule 5: every vessel shall at all times maintain a proper lookout by sight and hearing and by all available means appropriate to the circumstances.'),
  ('bm1:B2-002', 'BM-I', 4, 'Rule 6', 'Rule 6 (safe speed) requires speed to be set so a vessel can:', '["Always make best passage time","Stop within a distance appropriate to the prevailing circumstances and visibility","Outrun other vessels","Plane in all conditions"]'::jsonb, 1, 'Answer B. Safe speed allows proper and effective action to avoid collision and stopping within a distance appropriate to the circumstances and conditions.'),
  ('bm1:B2-003', 'BM-I', 4, 'Rule 7', 'Under Rule 7, risk of collision exists if the compass bearing of an approaching vessel:', '["Changes rapidly","Does not appreciably change","Is abeam","Is astern"]'::jsonb, 1, 'Answer B. A steady or little-changing compass bearing with decreasing range indicates risk of collision exists.'),
  ('bm1:B2-004', 'BM-I', 4, 'Rule 8', 'Rule 8 requires that action to avoid collision be:', '["Small and gradual so as not to alarm","Positive, made in ample time and large enough to be readily apparent","Left to the last moment","A series of tiny alterations"]'::jsonb, 1, 'Answer B. Action shall be positive, made in good time, and large enough to be readily apparent to another vessel observing visually or by radar.'),
  ('bm1:B2-005', 'BM-I', 4, 'Rule 9', 'In a narrow channel a vessel shall keep:', '["In the middle","To the outer limit on her starboard side","To the port side","Wherever the tide is weakest"]'::jsonb, 1, 'Answer B. Rule 9: keep as near to the outer limit of the channel on your starboard side as is safe and practicable.'),
  ('bm1:B2-006', 'BM-I', 4, 'Rule 12', 'When two sailing vessels have the wind on different sides, the one that gives way is:', '["The vessel with wind on the starboard side","The vessel with wind on the port side","The larger vessel","The faster vessel"]'::jsonb, 1, 'Answer B. Rule 12: when each has wind on a different side, the vessel with the wind on the port side keeps out of the way.'),
  ('bm1:B2-007', 'BM-I', 4, 'Rule 13', 'An overtaking vessel:', '["Has right of way over the vessel ahead","Must keep out of the way of the vessel being overtaken","May cut across as it pleases","Is the stand-on vessel"]'::jsonb, 1, 'Answer B. Rule 13: any vessel overtaking shall keep out of the way of the vessel being overtaken, regardless of later changes.'),
  ('bm1:B2-008', 'BM-I', 4, 'Rule 14', 'Two power-driven vessels meeting head-on shall each:', '["Alter course to port","Alter course to starboard so each passes port-to-port","Stop","Hold course and speed"]'::jsonb, 1, 'Answer B. Rule 14: in a head-on situation each alters course to starboard to pass port to port.'),
  ('bm1:B2-009', 'BM-I', 4, 'Rule 15', 'In a crossing situation between two power-driven vessels, the vessel that gives way is the one that:', '["Has the other on her own port side","Has the other on her own starboard side","Is to windward","Is the faster"]'::jsonb, 1, 'Answer B. Rule 15: the vessel which has the other on her own starboard side keeps out of the way and avoids crossing ahead.'),
  ('bm1:B2-010', 'BM-I', 4, 'Rule 16', 'The give-way vessel is required to:', '["Hold course and speed","Take early and substantial action to keep well clear","Sound five short blasts","Call the other vessel on VHF first"]'::jsonb, 1, 'Answer B. Rule 16: the give-way vessel shall take early and substantial action to keep well clear.'),
  ('bm1:B2-011', 'BM-I', 4, 'Rule 17', 'The stand-on vessel must:', '["Always hold course and speed no matter what","Keep her course and speed, but may and finally must act if the give-way vessel does not","Immediately give way","Stop her engines"]'::jsonb, 1, 'Answer B. Rule 17: the stand-on vessel keeps course and speed, may take action when collision appears, and must act when collision cannot be avoided by the give-way vessel alone.'),
  ('bm1:B2-012', 'BM-I', 4, 'Rule 18', 'In general the ''pecking order'' means a power-driven vessel keeps out of the way of:', '["A vessel restricted in her ability to manoeuvre, not under command, fishing, and sailing","Only sailing vessels","Only larger ships","Nothing — power always has right of way"]'::jsonb, 0, 'Answer A. Rule 18 hierarchy: a power-driven vessel gives way to NUC, RAM, vessels engaged in fishing and sailing vessels.'),
  ('bm1:B2-013', 'BM-I', 4, 'Rule 19', 'In or near restricted visibility, on hearing a fog signal apparently forward of the beam, a vessel shall:', '["Maintain speed","Reduce to the minimum at which she can be kept on course, or stop if necessary","Alter boldly to port","Sound the overtaking signal"]'::jsonb, 1, 'Answer B. Rule 19: reduce speed to the minimum to keep steerage, and if necessary take all way off, navigating with extreme caution.'),
  ('bm1:B2-014', 'BM-I', 4, 'Rule 23', 'A power-driven vessel under way of less than 50 m shows, as a minimum:', '["One masthead light, sidelights and a sternlight","Two masthead lights and a red all-round","Three all-round red lights","Sidelights only"]'::jsonb, 0, 'Answer A. Rule 23: a power-driven vessel under 50 m shows a masthead light, sidelights and a sternlight (a second masthead light is optional).'),
  ('bm1:B2-015', 'BM-I', 4, 'Rule 24', 'A vessel towing astern, where the tow exceeds 200 m, shows on the masthead:', '["One white light","Two white lights in a vertical line","Three white lights in a vertical line","A red over white"]'::jsonb, 2, 'Answer C. Rule 24: when the length of tow exceeds 200 m the towing vessel shows three masthead lights in a vertical line (otherwise two).'),
  ('bm1:B2-016', 'BM-I', 4, 'Rule 25', 'A sailing vessel under way shows:', '["Sidelights and a sternlight","A masthead light and sidelights","Two all-round red lights","A green over white"]'::jsonb, 0, 'Answer A. Rule 25: a sailing vessel under way shows sidelights and a sternlight (no masthead steaming light).'),
  ('bm1:B2-017', 'BM-I', 4, 'Rule 26', 'A vessel engaged in trawling shows:', '["Red over white","Green over white","Two red lights vertically","Red over red"]'::jsonb, 1, 'Answer B. Rule 26: a vessel trawling shows green over white all-round lights (''green over white, trawling at night'').'),
  ('bm1:B2-018', 'BM-I', 4, 'Rule 27', 'A vessel not under command (NUC) shows at night:', '["Two all-round red lights in a vertical line","Two all-round green lights","Red over white","Three white lights"]'::jsonb, 0, 'Answer A. Rule 27: a vessel not under command shows two all-round red lights in a vertical line.'),
  ('bm1:B2-019', 'BM-I', 4, 'Rule 27', 'A vessel restricted in her ability to manoeuvre (RAM) shows:', '["Red-white-red in a vertical line","Red over red","Green over white","Three green lights"]'::jsonb, 0, 'Answer A. Rule 27: a RAM vessel shows three all-round lights in a vertical line — red, white, red (''red, white, red — restricted'').'),
  ('bm1:B2-020', 'BM-I', 4, 'Rule 30', 'A vessel at anchor of less than 50 m shows:', '["One all-round white light where best seen","Two all-round red lights","Sidelights","A masthead light"]'::jsonb, 0, 'Answer A. Rule 30: a vessel under 50 m at anchor shows one all-round white light where it can best be seen.'),
  ('bm1:B2-021', 'BM-I', 4, 'Rule 34', 'One short blast on the whistle means:', '["I am altering my course to starboard","I am altering my course to port","I am operating astern propulsion","I do not understand your intentions"]'::jsonb, 0, 'Answer A. Rule 34: one short blast = ''I am altering my course to starboard.'''),
  ('bm1:B2-022', 'BM-I', 4, 'Rule 34', 'Two short blasts mean:', '["I am altering to starboard","I am altering to port","Astern propulsion","Overtaking on your starboard side"]'::jsonb, 1, 'Answer B. Two short blasts = ''I am altering my course to port.'''),
  ('bm1:B2-023', 'BM-I', 4, 'Rule 34', 'Three short blasts mean:', '["I am operating astern propulsion","I am altering to port","I am altering to starboard","I am in distress"]'::jsonb, 0, 'Answer A. Three short blasts = ''I am operating astern propulsion'' (engines going astern).'),
  ('bm1:B2-024', 'BM-I', 4, 'Rule 34', 'Five or more short rapid blasts mean:', '["I am altering course","I am at anchor","I am in doubt whether you are taking sufficient action","I am overtaking"]'::jsonb, 2, 'Answer C. Five (or more) short rapid blasts is the doubt/wake-up signal: I am in doubt whether you are taking sufficient action to avoid collision.'),
  ('bm1:B2-025', 'BM-I', 4, 'Rule 35', 'A power-driven vessel making way in fog sounds, at intervals of not more than 2 minutes:', '["One prolonged blast","Two prolonged blasts","One prolonged plus three short","Five short"]'::jsonb, 0, 'Answer A. Rule 35: a power-driven vessel making way through the water sounds one prolonged blast every 2 minutes.'),
  ('bm1:B2-026', 'BM-I', 4, 'Rule 35', 'A power-driven vessel under way but stopped (not making way) in fog sounds:', '["One prolonged blast","Two prolonged blasts in succession every 2 minutes","Three short blasts","A bell"]'::jsonb, 1, 'Answer B. Rule 35: a vessel under way but stopped sounds two prolonged blasts in succession (about 2 s apart) every 2 minutes.'),
  ('bm1:B2-027', 'BM-I', 4, 'Rule 35', 'A vessel at anchor in fog (under 100 m) sounds:', '["A bell rung rapidly for about 5 seconds at intervals of not more than 1 minute","One prolonged blast","Two prolonged blasts","Three short blasts"]'::jsonb, 0, 'Answer A. Rule 35: a vessel at anchor rings the bell rapidly for about 5 seconds at intervals of not more than one minute.'),
  ('bm1:B2-028', 'BM-I', 4, 'B2.3', 'A proper lookout includes:', '["Watching the chart plotter only","Using sight, hearing, radar and all available means to assess collision risk and the situation","Listening to VHF only","Relying on the autopilot"]'::jsonb, 1, 'Answer B. A proper lookout (Rule 5) uses sight, hearing and all available means, including radar, to make a full appraisal of the situation and risk of collision.'),
  ('bm1:B2-029', 'BM-I', 4, 'B2.4', 'The deck log on a Grade 1 vessel is primarily a record of:', '["The crew''s wages only","Navigational and operational events — courses, positions, weather, incidents and key decisions","Fuel receipts only","Passenger meals"]'::jsonb, 1, 'Answer B. The deck log records the vessel''s navigation and operation — times, positions, courses, weather, drills and any incidents — and is legal evidence of how she was run.'),
  ('bm1:B2-030', 'BM-I', 4, 'B2.4', 'An entry should be made in the deck log:', '["Only at the end of the season","Contemporaneously, in ink, and not erased — corrections are struck through and initialled","In pencil so it can be changed","Only if an accident occurs"]'::jsonb, 1, 'Answer B. Log entries are made at the time, in ink; errors are ruled through and initialled, never erased, so the log remains reliable evidence.'),
  ('bm1:B4-001', 'BM-I', 5, 'B4.3', 'A vessel making slow headway is set sideways by a strong beam wind because:', '["The wind has no effect at slow speed","Reduced steerage and high windage let the wind push her bodily to leeward","The propeller pulls her to windward","The rudder over-corrects"]'::jsonb, 1, 'Answer B. At slow speed steerage is poor and windage dominates, so a beam wind sets the vessel bodily to leeward; allow for it when manoeuvring.'),
  ('bm1:B4-002', 'BM-I', 5, 'B4.2', '''Interaction'' between two vessels passing close at speed can cause:', '["No effect","The vessels to be drawn together or the smaller to sheer, especially in shallow water","The vessels to speed up","The compass to deviate"]'::jsonb, 1, 'Answer B. Pressure fields around hulls interact when passing close, drawing vessels together or causing a sheer; reduce speed and increase passing distance, especially in shallow water.'),
  ('bm1:B4-003', 'BM-I', 5, 'B4.4', 'Anchor cable should be stowed and the anchor secured so that:', '["It can run freely at any time","It cannot run out accidentally at sea and is ready to let go when needed","It is permanently lashed and unusable","It is left hanging over the bow"]'::jsonb, 1, 'Answer B. The anchor is secured against accidental release at sea (devil''s claw/lashing) but kept ready to let go quickly when required.'),
  ('bm1:B4-004', 'BM-I', 5, 'B4.5', 'A good anchorage offers:', '["Maximum tidal stream and exposure","Shelter, good holding ground, sufficient swinging room and adequate depth at all states of tide","Rocky bottom and deep water only","A position in the fairway"]'::jsonb, 1, 'Answer B. Choose shelter from wind/sea, good holding ground, enough depth at low water and swinging room clear of other vessels and dangers.'),
  ('bm1:B4-005', 'BM-I', 5, 'B4.6', 'Navigating at reduced speed past moored craft and shorelines matters because:', '["It saves fuel only","Your bow and stern wave (wash) can damage other craft, banks and people","Speed limits never apply at sea","Wash improves your handling"]'::jsonb, 1, 'Answer B. The master must reduce speed where wash from the bow/stern wave could cause damage or danger to others; it is both good seamanship and a legal duty.'),
  ('bm1:B4-006', 'BM-I', 5, 'B4.7', 'Compared with a single screw, a twin-screw vessel can:', '["Never turn in her own length","Turn in her own length using one engine ahead and the other astern","Only steer with the rudder","Not go astern"]'::jsonb, 1, 'Answer B. Twin screws give a turning couple — one ahead, one astern — letting the vessel turn in her own length without using the rudder.'),
  ('bm1:B4-007', 'BM-I', 5, 'B4.8', 'A key hazard when towing another vessel is:', '["The tow has no effect on handling","Girting and the loss of manoeuvrability; the towline can part under load","Towing makes you faster","The towline never chafes"]'::jsonb, 1, 'Answer B. Towing reduces manoeuvrability, risks girting (being pulled beam-on) and a parting line under load; rig a quick-release and tow at moderate, steady speed.'),
  ('bm1:B4-008', 'BM-I', 5, 'B4.1', 'In nautical terms, ''freeboard'' is the:', '["Width of the deck","Vertical distance from the waterline to the deck edge","Length of the keel","Height of the mast"]'::jsonb, 1, 'Answer B. Freeboard is the vertical distance from the waterline to the watertight deck edge — the vessel''s reserve buoyancy.'),
  ('bm1:A-001', 'BM-I', 6, 'A1.7', 'Transverse thrust (paddle-wheel effect) on a single right-handed fixed propeller is most pronounced when the engine is:', '["Idling ahead in deep water","Running ahead at cruising speed","Stopped with the rudder amidships","First put astern from rest, before the boat gathers sternway"]'::jsonb, 3, 'Answer D. Transverse thrust is strongest going astern from rest, before water flow over the rudder builds; a right-handed prop walks the stern to port.'),
  ('bm1:A-002', 'BM-I', 6, 'A1.7', 'A right-handed single screw (clockwise viewed from astern) is put astern from rest. The stern tends to walk to:', '["Whichever way the wind blows","Port","Starboard","Dead straight"]'::jsonb, 1, 'Answer B. A right-handed propeller going astern walks the stern to port and swings the bow to starboard.'),
  ('bm1:A-003', 'BM-I', 6, 'A1.6', 'To turn a single-screw vessel short round in its own length in confined water, the most effective method is to:', '["Use alternating short bursts ahead with hard-over rudder, and astern, exploiting prop wash and transverse thrust","Use full ahead with hard-over rudder only","Drift and let the wind turn her","Tow the bow round with the dinghy"]'::jsonb, 0, 'Answer A. Turning short round uses short bursts ahead against hard-over rudder to kick the stern, alternated with astern, using prop wash and transverse thrust.'),
  ('bm1:A-004', 'BM-I', 6, 'A1.1', 'When coming alongside a berth, the safest general approach is to:', '["Approach beam-on and let the fenders absorb the contact","Approach fast so she answers the helm and stop with a burst astern","Approach downwind and downtide for an easy stop","Approach slowly at a shallow angle, stemming the stronger of wind or tide to keep steerage at low speed"]'::jsonb, 3, 'Answer D. Approach slowly against the stronger of wind or tide so the boat is held back and steerage is retained; never approach faster than you are willing to hit the berth.'),
  ('bm1:A-005', 'BM-I', 6, 'A1.2', 'When weighing (recovering) the anchor, the helmsman should:', '["Drive ahead hard to break it out while the crew heaves","Motor gently up towards the anchor as the cable comes in so the crew never takes the boat''s weight","Go full astern to drag it out","Leave the engine in neutral throughout"]'::jsonb, 1, 'Answer B. The boat is motored gently up to the anchor to reduce strain; the windlass and crew should never take the full weight of the vessel.'),
  ('bm1:A-006', 'BM-I', 6, 'A1.3', 'To come alongside another vessel that is under way and making way, you should:', '["Take an opposite course, bow to bow","Match her course and speed and close gently, normally on her lee side","Match her course but at twice her speed","Match her speed only, ignoring her heading"]'::jsonb, 1, 'Answer B. Come alongside a moving vessel by matching course and speed and closing gently, normally on the lee (sheltered) side.'),
  ('bm1:A-007', 'BM-I', 6, 'A1.4', 'To make fast to a mooring buoy single-handed in a tideway, you should approach:', '["Beam-on at speed","Downtide so you arrive quickly","Heading into the stronger of wind or tide so it acts as a brake","From directly downwind only, ignoring tide"]'::jsonb, 2, 'Answer C. Approach a buoy stemming the stronger of wind or tide; it acts as a brake and lets you stop with the buoy at the bow.'),
  ('bm1:A-008', 'BM-I', 6, 'A1.5', 'When manoeuvring at low speed in a confined marina, the master should bear in mind that:', '["A boat with little way on answers the helm slowly and is more affected by wind and tide","Rudder is fully effective at all speeds","Wind has no effect below cruising speed","Transverse thrust disappears at low speed"]'::jsonb, 0, 'Answer A. At low speed the rudder is less effective and the vessel is more easily set by wind and tide; plan the approach and use short bursts of power for steerage.'),
  ('bm1:A-009', 'BM-I', 6, 'A1.8', 'Steering an accurate compass course means:', '["Following the GPS course-over-ground exactly with no compass","Pointing the bow at the destination and locking the wheel","Steering by the wake only","Holding the lubber line on the ordered compass figure and cross-checking with a transit or mark"]'::jsonb, 3, 'Answer D. Keep the compass card steady on the ordered course at the lubber line, cross-checking with a transit or fixed mark to detect set.'),
  ('bm1:A-010', 'BM-I', 6, 'A1.9', 'On VHF, the spoken word that precedes a DISTRESS call is:', '["SEELONCE","PAN-PAN","SECURITE","MAYDAY (spoken three times)"]'::jsonb, 3, 'Answer D. A distress call is preceded by MAYDAY spoken three times, used only when a vessel or person is in grave and imminent danger.'),
  ('bm1:A-011', 'BM-I', 6, 'A1.9', 'The VHF urgency signal, for an urgent message about safety but not grave and imminent danger, is:', '["SECURITE","PAN-PAN (spoken three times)","MAYDAY","MAYDAY RELAY"]'::jsonb, 1, 'Answer B. PAN-PAN (three times) is the urgency signal — a very urgent message concerning the safety of a vessel or person, short of grave danger.'),
  ('bm1:A-012', 'BM-I', 6, 'A1.9', 'The VHF safety signal SECURITE introduces:', '["A navigational or meteorological warning","A routine radio check","A distress message","A request to change channel"]'::jsonb, 0, 'Answer A. SECURITE (three times) introduces an important navigational or meteorological warning.'),
  ('bm1:A-013', 'BM-I', 6, 'A1.9', 'The international VHF distress, safety and calling channel is:', '["Channel 6","Channel 16","Channel 80","Channel 72"]'::jsonb, 1, 'Answer B. Channel 16 (156.8 MHz) is the international distress, safety and calling channel and must be monitored.'),
  ('bm1:A-014', 'BM-I', 6, 'A1.9', 'A DSC distress alert on VHF is normally transmitted on:', '["Channel 70","Channel 13","Channel 16","Channel 6"]'::jsonb, 0, 'Answer A. Digital Selective Calling distress alerts are sent on VHF Channel 70; voice distress traffic then follows on Channel 16.'),
  ('bm1:A-015', 'BM-I', 6, '1.2.3', 'Every person in charge of a vessel operating in EXPOSED waters must hold:', '["No radio qualification","A VHF short range certificate only","The GMDSS General Operator''s Certificate","A coastal skipper certificate only"]'::jsonb, 2, 'Answer C. SCV Code Annex 11-1.2.3 requires the GMDSS General Operator''s Certificate for the person in charge of a vessel operating in exposed waters.'),
  ('bm1:A-016', 'BM-I', 6, 'A1.9', 'A spoken MAYDAY message should include, in order:', '["Only the vessel''s name","MAYDAY and vessel name, position, nature of distress, assistance required, persons on board","The nature of distress only","The channel you wish to use"]'::jsonb, 1, 'Answer B. A MAYDAY gives: MAYDAY x3 and vessel name/identity, position, nature of distress, assistance required, number of persons on board and any other information.'),
  ('bm1:B11-001', 'BM-I', 7, 'B11.1', 'A daily pre-start engine check should include:', '["Only the fuel gauge","Oil and coolant levels, fuel, belts, water in the raw-water filter, and the battery state","Nothing if it ran yesterday","Only the paintwork"]'::jsonb, 1, 'Answer B. Daily checks cover lubricating-oil and coolant levels, fuel and water/sediment, belts, raw-water strainer and the batteries before starting.'),
  ('bm1:B11-002', 'BM-I', 7, 'B11.4', 'A running check while under way should include watching:', '["Only the speed","Oil pressure, coolant temperature, charging, exhaust colour and any unusual noise or vibration","The radio volume","The clock"]'::jsonb, 1, 'Answer B. Running checks monitor oil pressure, temperature, charging, exhaust note/colour and any abnormal noise or vibration so faults are caught early.'),
  ('bm1:B11-003', 'BM-I', 7, 'B11.3', 'An engine high-temperature alarm or shut-off device exists to:', '["Save fuel","Warn of, or prevent, damage from overheating before the engine is wrecked","Increase power","Charge the batteries"]'::jsonb, 1, 'Answer B. Safety and shut-off devices warn of, or stop the engine on, conditions such as overheating or low oil pressure to prevent serious damage.'),
  ('bm1:B11-004', 'BM-I', 7, 'B11.1', 'If the engine raw-water (cooling) telltale stops flowing, the likely first cause to check is:', '["A flat battery","A blocked raw-water intake/strainer or a failed impeller","The VHF aerial","The compass"]'::jsonb, 1, 'Answer B. Loss of cooling-water flow points to a blocked inlet/strainer or a failed raw-water pump impeller; stop the engine before it overheats.'),
  ('bm1:B11-005', 'BM-I', 7, 'B11.5', 'If the engine loses power and the exhaust shows black smoke, a reasonable diagnosis is:', '["Too much cooling water","Over-fuelling / restricted air (dirty air filter) or overload","The compass is wrong","Low battery only"]'::jsonb, 1, 'Answer B. Black smoke indicates incomplete combustion from over-fuelling, a restricted air supply (clogged filter) or overload; check air supply and loading.'),
  ('bm1:B11-006', 'BM-I', 7, 'B11.2', 'Routine servicing of the engine and auxiliaries should be carried out:', '["Only when it breaks down","According to the maker''s schedule (oil/filter changes, impellers, anodes) with records kept","Never, to save money","Only by the surveyor"]'::jsonb, 1, 'Answer B. Planned maintenance to the manufacturer''s schedule — oil and filter changes, impellers, anodes, belts — with records, keeps machinery reliable.'),
  ('bm1:B11-007', 'BM-I', 7, 'B11.1', 'Batteries should be checked for:', '["Colour only","Secure mounting, clean tight terminals, electrolyte level (if applicable) and state of charge","Weight only","Nothing"]'::jsonb, 1, 'Answer B. Battery checks cover secure stowage, clean/tight terminals, electrolyte level where serviceable and the state of charge.'),
  ('bm1:B1-001', 'BM-I', 8, 'B1.1', 'When recovering a man overboard under power, the engine should be:', '["Kept running ahead until the last second","Stopped (or clutch out) before the casualty is brought alongside, to remove propeller risk","Run astern throughout the approach","Left at cruising revs to maintain steerage"]'::jsonb, 1, 'Answer B. The propeller must be stopped before the casualty comes alongside; an exposed turning propeller can kill or injure a person in the water.'),
  ('bm1:B1-002', 'BM-I', 8, 'B1.1', 'The first action on seeing a person fall overboard is to:', '["Go below to fetch the first-aid kit","Shout ''man overboard'', throw a lifebuoy and post a pointer to keep the casualty in sight","Increase speed to circle quickly","Make a MAYDAY before anything else"]'::jsonb, 1, 'Answer B. Raise the alarm, throw buoyancy to the casualty, and detail a crew member to point at and never lose sight of the person; then manoeuvre back.'),
  ('bm1:B1-003', 'BM-I', 8, 'B1.2', 'On total loss of main engine in open water, the first priorities are to:', '["Abandon ship immediately","Assess drift/danger of grounding, anchor if practicable, and warn other traffic; attempt restart only when safe","Send a MAYDAY at once regardless of danger","Go below and start dismantling the engine"]'::jsonb, 1, 'Answer B. Loss of engines is not in itself a MAYDAY; assess the danger of drifting onto a hazard, anchor or signal as appropriate, and call for help according to the level of danger.'),
  ('bm1:B1-004', 'BM-I', 8, 'B1.3', 'On loss of steering, the master should first:', '["Stop the vessel if safe, warn the crew, and rig the emergency tiller or use engines to steer","Continue at full speed and hope it returns","Abandon ship","Disconnect the batteries"]'::jsonb, 0, 'Answer A. Reduce way, warn the crew, rig emergency steering (emergency tiller) and, on a twin-screw vessel, steer on the engines until repaired.'),
  ('bm1:B1-005', 'BM-I', 8, 'B1.4', 'Immediately after a collision the master should:', '["Reverse away from the other vessel at once","Account for all persons, assess damage and flooding, and stand by to render assistance","Leave the scene to avoid liability","Restart the engines and continue passage"]'::jsonb, 1, 'Answer B. Check for injuries and missing persons, assess your own and the other vessel''s damage/flooding, render assistance and exchange particulars; do not part company if it endangers life.'),
  ('bm1:B1-006', 'BM-I', 8, 'B1.5', 'After running aground, before attempting to refloat, the master should:', '["Immediately go full astern at maximum power","Check for injuries, sound the bilges for ingress, and assess the state of tide before deciding whether to refloat","Drop all anchors","Empty all fuel overboard"]'::jsonb, 1, 'Answer B. First check for casualties and hull damage/ingress and consider the tide; coming off may make flooding worse, so assess before acting.'),
  ('bm1:B1-007', 'BM-I', 8, 'B1.6', 'On a serious accident to a passenger, the master''s first duty is to:', '["Continue the trip as planned","Make the casualty safe, give first aid, and summon medical help/evacuation as required","Note it in the log later and carry on","Ask other passengers to handle it"]'::jsonb, 1, 'Answer B. Render first aid, prevent further harm, and call for medical assistance or arrange evacuation; the incident is then logged and reported.'),
  ('bm1:B1-008', 'BM-I', 8, 'B1.7', 'A fire involving flammable liquids (petrol, oil) is class:', '["Class A","Class B","Class C","Class D"]'::jsonb, 1, 'Answer B. Class B fires are flammable liquids; foam, dry powder or CO2 are suitable — never a water jet.'),
  ('bm1:B1-009', 'BM-I', 8, 'B1.7', 'The correct extinguisher for a live electrical fire is:', '["Water","Foam","CO2 or dry powder","Wet chemical"]'::jsonb, 2, 'Answer C. On live electrical equipment use a non-conductive medium — CO2 or dry powder — never water or foam.'),
  ('bm1:B1-010', 'BM-I', 8, 'B1.8', 'The ''fire triangle'' shows that to burn, a fire needs:', '["Heat, fuel and oxygen","Heat, smoke and water","Fuel, foam and oxygen","Spark, fuel and metal"]'::jsonb, 0, 'Answer A. Fire needs heat, fuel and oxygen; removing any one (cooling, starving or smothering) extinguishes it.'),
  ('bm1:B1-011', 'BM-I', 8, 'B1.9', 'Before launching a liferaft you must:', '["Inflate it on deck first","Make the painter fast to a strong point on the vessel, then throw the raft to leeward","Cut the painter immediately","Board it before inflation"]'::jsonb, 1, 'Answer B. Secure the painter to the ship, launch the raft to leeward, then sharply pull the painter to inflate before boarding.'),
  ('bm1:B1-012', 'BM-I', 8, 'B1.10', 'When searching for a casualty in reduced visibility, an effective method is to:', '["Steam in a straight line and hope","Use a systematic search pattern (e.g. expanding square) at slow safe speed with all lookouts posted","Switch off the radar to save power","Anchor and wait until visibility clears"]'::jsonb, 1, 'Answer B. A systematic pattern such as an expanding square, at safe slow speed with all available lookouts, gives the best chance of finding a casualty.'),
  ('bm1:B1-013', 'BM-I', 8, 'B1.11', 'If beaching is unavoidable to save life, the master should choose:', '["A steep rocky shore close to deep water","A gently shelving sheltered beach, head to sea, clear of rocks","Any shore downwind regardless of bottom","A harbour wall at speed"]'::jsonb, 1, 'Answer B. Choose a gently shelving, sheltered beach clear of rocks, approaching head to sea so the vessel does not broach.'),
  ('bm1:B1-014', 'BM-I', 8, 'B1.4', 'After a collision involving injury or potential pollution, the master must, as soon as practicable:', '["Say nothing to anyone","Report the casualty to the Coastguard/authorities and record the facts","Repair the damage before reporting","Wait until returning to home port"]'::jsonb, 1, 'Answer B. Serious casualties (injury, loss of life, pollution) must be reported to the authorities and the facts recorded in the log.'),
  ('bm1:B8-001', 'BM-I', 8, 'B8.1', 'A pre-departure passenger safety briefing (VIII/8) should cover:', '["The lunch menu","Location and use of lifejackets, emergency exits, and what to do in an emergency","Only the destination","The vessel''s fuel consumption"]'::jsonb, 1, 'Answer B. Regulation VIII/8 requires a safety announcement covering lifejackets, exits/muster and emergency procedures before departure.'),
  ('bm1:B8-002', 'BM-I', 8, 'B8.2', 'Passengers should be disposed about the vessel so as to:', '["Crowd one side for the view","Maintain the vessel''s stability and trim, avoiding overcrowding to one side","Sit anywhere with no regard to balance","All stand at the bow"]'::jsonb, 1, 'Answer B. The master arranges and, if needed, redistributes passengers to keep the vessel upright and properly trimmed; crowding to one side causes a dangerous list.'),
  ('bm1:B8-003', 'BM-I', 8, 'B8.3', 'The number of persons carried must:', '["Be whatever fits","Never exceed the maximum stated on the Safety Certificate, and be recorded/reported as required (VIII/7)","Be estimated by eye","Depend only on the weather"]'::jsonb, 1, 'Answer B. Passenger numbers must not exceed the certified maximum and must be counted, recorded and reported per VIII/7 — vital for headcount in an emergency.'),
  ('bm1:B8-004', 'BM-I', 8, 'B8.4', 'An orderly evacuation (VIII/10) depends most on:', '["Speed alone","A briefed crew, clear instructions, marked exits and a controlled, calm process suited to the vessel and area","Letting passengers self-organise","Switching off the lights"]'::jsonb, 1, 'Answer B. Orderly evacuation needs prepared crew, clear emergency instructions, accessible exits and a controlled process appropriate to the vessel''s size and operating area.'),
  ('bm1:B8-005', 'BM-I', 8, 'B8.5', 'Demonstrating a lifejacket to passengers should include:', '["Only telling them where it is","How to don and secure it, and how to operate the light/whistle","A long technical lecture","Nothing — they will work it out"]'::jsonb, 1, 'Answer B. The crew must be able to show passengers how to put on and secure a lifejacket and operate its light and whistle.'),
  ('bm1:B13-001', 'BM-I', 9, 'B13.3', 'Under MARPOL, the discharge into the sea of plastics, synthetic ropes and garbage bags is:', '["Permitted beyond 12 miles","Prohibited everywhere","Permitted at night","Permitted in port only"]'::jsonb, 1, 'Answer B. The disposal of all plastics into the sea is prohibited anywhere; they must be retained on board and landed ashore.'),
  ('bm1:B13-002', 'BM-I', 9, 'B13.2', 'When pumping bilges or changing lubricating oil, the master must ensure that:', '["Any oil goes straight over the side","No oil or oily water is discharged into the sea; oil/oily waste is retained and landed ashore","It is done at sea only","It is done quickly without care"]'::jsonb, 1, 'Answer B. Bilge water and waste oil must not be discharged; an oily-water separator or retention and landing ashore prevents oil pollution.'),
  ('bm1:B13-003', 'BM-I', 9, 'B13.1', 'A general appreciation of the pollution regulations requires the master to prevent the discharge of:', '["Only oil","Oil, garbage, sewage and other harmful substances, within the rules for the area","Nothing — the sea dilutes everything","Only plastics"]'::jsonb, 1, 'Answer B. MARPOL covers oil, noxious liquids, sewage, garbage and air pollution; the master must prevent unlawful discharge of all of these.'),
  ('bm1:B13-004', 'BM-I', 9, 'B13.2', 'To prevent fuel/oil spills during bunkering, the master should:', '["Fill quickly and walk away","Stop scuppers/use a drip tray, monitor the transfer, avoid overfilling and have spill kit ready","Overfill to be sure it is full","Bunker while under way at speed"]'::jsonb, 1, 'Answer B. Block deck scuppers, use drip trays, watch the level to avoid overflow and keep an oil-spill kit ready to contain any spill.'),
  ('bm1:B13-005', 'BM-I', 9, 'B13.3', 'Annoyed by floating litter, a crew member wishes to throw a torn plastic fender over the side. The master should:', '["Allow it — it is only one item","Refuse — disposal of plastics at sea is prohibited; retain it for disposal ashore","Allow it if more than 3 miles out","Allow it at night"]'::jsonb, 1, 'Answer B. All plastics, including damaged gear, must be retained on board and disposed of ashore; throwing any plastic overboard is prohibited.'),
  ('bm1:B6-001', 'BM-I', 11, 'B6.1', 'The person in charge of the vessel is responsible for ensuring that:', '["LSA and FFA are only checked at survey time","The life-saving and fire-fighting appliances are properly maintained and ready for use","The crew buy their own equipment","Equipment is landed ashore when not in use"]'::jsonb, 1, 'Answer B. Annex 11-B6.1: the master must be satisfied that the statutory life-saving and fire-fighting appliances are properly maintained and serviceable.'),
  ('bm1:B6-002', 'BM-I', 11, 'B6.2', 'A throw-over (non-davit) inflatable liferaft is launched by:', '["Lifting it over the side by hand fully inflated","Securing the painter, releasing it from its cradle and throwing it overboard to leeward, then jerking the painter to inflate","Cutting all lashings and leaving it","Inflating it on deck and walking it over"]'::jsonb, 1, 'Answer B. Secure the painter to the ship, release and throw the canister to leeward, then sharply pull the painter to fire the inflation bottle before boarding.'),
  ('bm1:B6-003', 'BM-I', 11, 'B6.3', 'Inflatable liferafts must be serviced:', '["Never, once installed","At an approved service station at the intervals required by the manufacturer/Administration (typically annually)","Only by the crew at sea","Every five years only"]'::jsonb, 1, 'Answer B. Liferafts (and inflatable boats) must be serviced at an approved station at the required intervals so the inflation system and equipment remain reliable.'),
  ('bm1:B6-004', 'BM-I', 11, 'B6.4', 'A hydrostatic release unit (HRU) is fitted to a liferaft so that:', '["It deflates the raft automatically","If the vessel sinks, water pressure releases the raft, which floats free and inflates","It locks the raft permanently in its cradle","It heats the raft"]'::jsonb, 1, 'Answer B. The HRU releases the lashing at a set depth (about 4 m) if the vessel founders, so the raft floats free, the painter comes taut and the raft inflates.'),
  ('bm1:B6-005', 'BM-I', 11, 'B6.4', 'A hydrostatic release unit must be checked because:', '["It never expires","It has an expiry date and must be replaced when it lapses","It is purely decorative","It works without water"]'::jsonb, 1, 'Answer B. HRUs carry an expiry date and must be renewed; an out-of-date unit may fail to release the raft when the vessel sinks.'),
  ('bm1:B6-006', 'BM-I', 11, 'B6.5', 'Buoyant apparatus and lifebuoys should be:', '["Painted over for appearance","Maintained, kept accessible, with lights/lines serviceable and ready for instant use","Stowed below in a locker","Used as fenders"]'::jsonb, 1, 'Answer B. Buoyant apparatus and lifebuoys are kept accessible and ready, with attached lights and lines serviceable, and inspected as part of routine maintenance.'),
  ('bm1:B6-007', 'BM-I', 11, 'B6.1', 'A fire extinguisher should be checked to confirm that:', '["It is the right colour only","It is in date, the gauge (if fitted) reads in the green/charged band, the seal is intact and it is correctly stowed","It is heavy","It has been used recently"]'::jsonb, 1, 'Answer B. Routine checks confirm the extinguisher is in date and charged (gauge in green where fitted), seal intact, accessible and of the correct type for the risk.'),
  ('bm1:B7-001', 'BM-I', 11, 'B7.1', 'Which of the following is a recognised distress signal under COLREG Annex IV?', '["A single white flare","A continuous sounding of the fog horn / a gun fired at intervals","Switching off all lights","Hoisting a yellow flag"]'::jsonb, 1, 'Answer B. Annex IV distress signals include continuous sounding of a fog apparatus, a gun fired at intervals of about a minute, red flares, the SOS signal and MAYDAY by radio.'),
  ('bm1:B7-002', 'BM-I', 11, 'B7.1', 'A red parachute or red hand flare indicates:', '["A request to pass to port","Distress — a vessel or person needs assistance","All clear","A diving operation"]'::jsonb, 1, 'Answer B. Red flares (parachute and hand) are distress signals under Annex IV; orange smoke is the daytime equivalent.'),
  ('bm1:B7-003', 'BM-I', 11, 'B7.1', 'The signal of raising and lowering outstretched arms slowly and repeatedly means:', '["Greeting another vessel","Distress — I need assistance","Man overboard recovered","Reduce speed"]'::jsonb, 1, 'Answer B. Slowly and repeatedly raising and lowering outstretched arms is a recognised distress signal under Annex IV.'),
  ('bm1:B7-004', 'BM-I', 11, 'B7.2', 'On receiving a distress alert, the Coast Guard / MRCC will:', '["Ignore it unless it is repeated","Acknowledge, coordinate the search and rescue response and task assets","Charge the vessel a fee first","Wait for daylight"]'::jsonb, 1, 'Answer B. The Coast Guard / Maritime Rescue Coordination Centre acknowledges the distress, gathers information and coordinates the SAR response.'),
  ('bm1:B7-005', 'BM-I', 11, 'B7.3', 'To aid your location by rescuers you should:', '["Switch everything off and wait quietly","Use all available means — EPIRB, SART, flares, VHF/DSC, lights and any visual/sound signals","Throw the flares away","Steer away from rescuers to avoid collision"]'::jsonb, 1, 'Answer B. Use every aid to location: EPIRB/PLB, radar SART, DSC/VHF, flares and smoke, lights and reflective material, to help searchers find you quickly.'),
  ('bm1:B7-006', 'BM-I', 11, 'B7.4', 'Before abandoning ship the master should, if time allows:', '["Nothing — just jump","Send/confirm a distress message and position, don lifejackets, take the grab bag/EPIRB and board the raft dry if possible","Open the seacocks first","Leave the EPIRB behind"]'::jsonb, 1, 'Answer B. Make/confirm the distress message with position, get lifejackets on, take the EPIRB and grab bag, and try to step up into the raft rather than into the water.'),
  ('bm1:B18-001', 'BM-I', 12, 'B18.1', 'The first-aid kit on board must be:', '["Whatever the crew bring","Of the required contents, in date, accessible and known to the crew","Kept locked away from everyone","Used only by a doctor"]'::jsonb, 1, 'Answer B. The kit must hold the required, in-date contents, be readily accessible and the crew must know its location and how to use the items.'),
  ('bm1:B18-002', 'BM-I', 12, 'B18.1', 'The instructions/guidance in the first-aid kit are provided so that:', '["They can be discarded","Whoever uses the kit can apply the correct treatment for common injuries","They look professional","They replace calling for help"]'::jsonb, 1, 'Answer B. The kit''s instructions guide correct use for common injuries; serious cases still require radio medical advice and evacuation.'),
  ('bm1:B18-003', 'BM-I', 12, 'B18.1', 'After using items from the first-aid kit, the master should:', '["Leave it empty","Restock the used items and check expiry dates so the kit is ready for the next emergency","Throw the kit away","Hide the shortage"]'::jsonb, 1, 'Answer B. Used items are replaced and expiry dates checked so the kit remains complete and serviceable for the next incident.'),
  ('bm1:B15-001', 'BM-I', 13, 'B15.1', 'The Caribbean Netherlands lies in IALA Region B. Entering harbour from seaward, you leave:', '["Red to port, green to starboard","Red to starboard, green to port (''red-right-returning'')","Red and green on either side","All marks to starboard"]'::jsonb, 1, 'Answer B. In Region B, entering from seaward, red lateral marks are kept to starboard and green to port — ''red-right-returning.'''),
  ('bm1:B15-002', 'BM-I', 13, 'B15.1', 'A north cardinal mark tells you that:', '["Safe water is to the south","Safe water lies to the north of the mark — pass to the north","It marks safe water all round","It is a special mark"]'::jsonb, 1, 'Answer B. A north cardinal mark indicates the safe water is to its north; you pass to the north of it. Its topmarks are two cones pointing up.'),
  ('bm1:B15-003', 'BM-I', 13, 'B15.1', 'An isolated danger mark is:', '["Yellow with an X topmark","Black with one or more red horizontal bands and two black spheres as a topmark","Red and white vertical stripes","Green with a cone topmark"]'::jsonb, 1, 'Answer B. An isolated danger mark is black with red band(s) and a topmark of two black balls; it marks a danger with navigable water all round.'),
  ('bm1:B15-004', 'BM-I', 13, 'B15.1', 'A safe-water (fairway/landfall) mark is:', '["Black and yellow","Red and white vertical stripes, often with a single red spherical topmark","All green","All yellow"]'::jsonb, 1, 'Answer B. A safe-water mark has red and white vertical stripes with a red sphere topmark, indicating navigable water all round (mid-channel or landfall).'),
  ('bm1:B15-005', 'BM-I', 13, 'B15.1', 'A yellow buoy with an X (St Andrew''s cross) topmark is a:', '["Port lateral mark","Special mark indicating an area or feature (e.g. a restricted/marine-park zone)","Cardinal mark","Isolated danger mark"]'::jsonb, 1, 'Answer B. A special mark is yellow with an X topmark and a yellow light; it marks a special area or feature, not primarily a navigational danger.'),
  ('bm1:B15-006', 'BM-I', 13, 'B15.1', 'In the Bonaire National Marine Park, the master must:', '["Anchor anywhere on the reef","Use the designated moorings and observe no-anchor and protected zones","Ignore the zones offshore","Anchor only at night"]'::jsonb, 1, 'Answer B. Local restrictions require use of designated moorings and respect for no-anchor and protected zones to avoid damaging the reef; the master knows and obeys them.'),
  ('bm1:B15-007', 'BM-I', 13, 'B15.1', 'Cardinal marks are coloured and lit so that:', '["All look identical","Their black/yellow colours and quick/very-quick white light codes show which quarter is safe","They never show a light","They are red and green"]'::jsonb, 1, 'Answer B. Cardinal marks use black and yellow bands and distinctive quick/very-quick white flash groups keyed to N, E, S or W to show the safe side.'),
  ('bm1:B17-001', 'BM-I', 13, 'B17.1', 'Ship''s plans carried on board (where provided) help the master to:', '["Decorate the saloon","Understand the structure, tanks, watertight boundaries and systems for safe operation and damage control","Sell the vessel","Replace the chart"]'::jsonb, 1, 'Answer B. General arrangement and related plans show structure, tanks, watertight divisions and systems, supporting loading, maintenance and damage-control decisions.'),
  ('bm1:B17-002', 'BM-I', 13, 'B17.2', 'Watertight subdivision protects the vessel by:', '["Making her faster","Confining flooding to one compartment so the vessel can survive a breach","Reducing fuel use","Improving the view"]'::jsonb, 1, 'Answer B. Bulkheads divide the hull so that flooding from a breach is contained in one compartment, preserving buoyancy and stability.'),
  ('bm1:B17-003', 'BM-I', 13, 'B17.2', 'Watertight doors and hatches at sea should be:', '["Left open for ventilation","Kept closed (or as the stability information requires) so subdivision is maintained","Removed","Wedged open"]'::jsonb, 1, 'Answer B. Watertight closures are kept shut at sea so that, if the hull is breached, the subdivision actually contains the flooding.'),
  ('bm1:B17-004', 'BM-I', 13, 'B17.3', 'The bilge pumping arrangement is provided to:', '["Supply drinking water","Remove water that enters the hull and help control minor flooding","Cool the engine","Trim the vessel by the bow"]'::jsonb, 1, 'Answer B. Bilge pumps remove accumulated or ingressed water; keeping the system and strainers clear is essential for controlling flooding.'),
  ('bm1:B17-005', 'BM-I', 13, 'B17.4', 'A vessel has positive transverse (initial) stability when:', '["The centre of gravity G is above the metacentre M","The metacentre M is above the centre of gravity G, giving a positive GM and a righting lever when heeled","G and M coincide","She has no freeboard"]'::jsonb, 1, 'Answer B. With M above G (positive GM) a heeled vessel develops a righting lever GZ that returns her upright; if G rises above M she is unstable.'),
  ('bm1:B17-006', 'BM-I', 13, 'B17.4', 'Metacentric height (GM) is:', '["The height of the mast","The vertical distance between the centre of gravity G and the metacentre M, a measure of initial stiffness","The freeboard","The draught"]'::jsonb, 1, 'Answer B. GM is the distance from G to M; a larger positive GM gives a stiffer (more quickly righting) vessel, a small GM a tender one.'),
  ('bm1:B17-007', 'BM-I', 13, 'B17.4', 'The righting lever GZ is:', '["The length of the keel","The horizontal distance between the lines of buoyancy and gravity at a given heel, giving the righting moment","Always zero","The same as GM at all angles"]'::jsonb, 1, 'Answer B. GZ is the horizontal separation of the weight (through G) and buoyancy (through B) forces when heeled; righting moment = displacement x GZ.'),
  ('bm1:B17-008', 'BM-I', 13, 'B17.5', 'Raising weights high in the vessel (e.g. on deck or aloft) will:', '["Lower G and increase stability","Raise G, reduce GM and make the vessel more tender","Have no effect","Increase freeboard"]'::jsonb, 1, 'Answer B. Adding weight high raises the centre of gravity G, reducing GM and making the vessel roll more slowly and heel more easily — more tender.'),
  ('bm1:B17-009', 'BM-I', 13, 'B17.6', 'Wind heeling force on a vessel increases with:', '["Lower freeboard only","The projected (side) area exposed to the wind and the square of the wind speed","Engine power","The number of anchors"]'::jsonb, 1, 'Answer B. Wind pressure acts on the projected side area; the heeling force rises with that area and roughly with the square of wind speed.'),
  ('bm1:B17-010', 'BM-I', 13, 'B17.7', 'Asymmetric loading (more weight to one side) causes:', '["A bodily sinkage only","A list (steady heel) to the loaded side, reducing stability on that side","Increased speed","No change in trim"]'::jsonb, 1, 'Answer B. Loading more to one side shifts G off the centreline, producing a list; it reduces the effective range of stability and freeboard on that side.'),
  ('bm1:B17-011', 'BM-I', 13, 'B17.8', 'Mooring lines led overtight where there is a large tidal range can:', '["Improve stability","Heel or even capsize the vessel, or part the lines, as the water level changes","Save fuel","Have no effect"]'::jsonb, 1, 'Answer B. Overtight moorings cannot accommodate the rise and fall of tide; as the level changes they can heel/pull down the vessel or part suddenly.'),
  ('bm1:B17-012', 'BM-I', 13, 'B17.9', 'The angle of equilibrium (steady heel under a heeling force) is where:', '["The vessel capsizes","The righting moment exactly balances the heeling moment","GM is zero","The engine stops"]'::jsonb, 1, 'Answer B. A vessel settles at the heel angle where its righting moment equals the applied heeling moment; a tender vessel settles at a larger angle.'),
  ('bm1:B17-013', 'BM-I', 13, 'B17.10', 'Dynamic stability (the area under the GZ curve) represents the vessel''s:', '["Top speed","Ability to absorb the energy of a gust or wave without capsizing","Fuel capacity","Freeboard"]'::jsonb, 1, 'Answer B. Dynamic stability is the energy the vessel can absorb before capsizing — the area under the righting-lever (GZ) curve; rolling and gusts test it.'),
  ('bm1:B17-014', 'BM-I', 13, 'B17.11', 'Free-surface effect (liquid free to move in a partly filled tank or flooded space) acts to:', '["Lower G and increase stability","Effectively raise G and reduce GM, worsening any heel","Increase freeboard","Have no effect at sea"]'::jsonb, 1, 'Answer B. A free liquid surface shifts to the low side as the vessel heels, effectively raising G and reducing GM; subdividing tanks and keeping them pressed up or empty limits it.'),
  ('bm1:B17-015', 'BM-I', 13, 'B17.11', 'Free-surface effect is best controlled by:', '["Filling tanks half full","Keeping tanks either pressed full or empty, fitting baffles/subdivision, and pumping out flooded spaces promptly","Leaving bilges flooded","Adding more free liquid"]'::jsonb, 1, 'Answer B. Pressed-up or empty tanks have no free surface; baffles/subdivision reduce the effect, and flooded spaces should be pumped out quickly.'),
  ('bm1:B17-016', 'BM-I', 13, 'B17.12', 'Operating a deck crane/davit safely requires that:', '["The load may exceed the SWL briefly","The Safe Working Load is never exceeded, and the heeling effect of a suspended load is allowed for","The crane is used at any angle","Stability is ignored"]'::jsonb, 1, 'Answer B. Never exceed the crane''s Safe Working Load; a suspended load acts high up and to one side, heeling the vessel — allow for it in stability terms.'),
  ('bm1:B17-017', 'BM-I', 13, 'B17.13', 'Adequate freeboard is important because it provides:', '["A place to sit","Reserve buoyancy and a margin against shipping water on deck","Faster speed","Lower fuel use"]'::jsonb, 1, 'Answer B. Freeboard is reserve buoyancy and the margin before the deck edge immerses; overloading reduces it and the safety it provides.'),
  ('bm1:B17-018', 'BM-I', 13, 'B17.13', 'Correct fore-and-aft trim is important because:', '["It only affects appearance","Bad trim degrades handling, sea-keeping and freeboard and can bury the bow in a head sea","It increases the certified number of passengers","It changes the variation"]'::jsonb, 1, 'Answer B. Trim is the difference between forward and after draughts; poor trim from bad loading worsens handling, sea-keeping and freeboard.'),
  ('bm1:B17-019', 'BM-I', 13, 'B17.14', 'The vessel''s stability and hydrostatic data should be used by the master to:', '["Guess the loading","Load and operate within the approved limits — persons, weights and conditions — rather than by eye","Decorate the wheelhouse","Set the radar range"]'::jsonb, 1, 'Answer B. The approved stability information (from the inclining test and calculations) tells the master how to load and operate safely; he works within it, not by guesswork.'),
  ('bm1:B17-020', 'BM-I', 13, 'B17.15', 'In a following or quartering sea, a danger to stability is that the vessel may:', '["Become more stable","Be pooped or broach, and lose stability as a wave crest passes amidships","Speed up safely","Stop rolling"]'::jsonb, 1, 'Answer B. In following/quartering seas the vessel can broach or be pooped, and a crest amidships reduces waterplane and stability; reduce speed and adjust heading.'),
  ('bm1:B17-021', 'BM-I', 13, 'B17.16', 'The maximum number of persons and load stated on the certificate must:', '["Be treated as a target to beat","Never be exceeded, as it is the basis of the vessel''s stability and safety","Be ignored in calm weather","Apply only at night"]'::jsonb, 1, 'Answer B. The certified persons and load underpin the vessel''s stability; exceeding them reduces freeboard and stability and is unlawful and dangerous.'),
  ('bm1:B17-022', 'BM-I', 13, 'B17.17', 'Before entering an enclosed or confined space (e.g. a tank or void), the master must:', '["Enter quickly to save time","Treat it as potentially lethal — test/ventilate the atmosphere, use a permit, post a watch and have rescue arrangements ready","Light a match to check for gas","Send the smallest crew member alone"]'::jsonb, 1, 'Answer B. Enclosed spaces may be oxygen-deficient or toxic; test and ventilate, use a permit-to-work, post an attendant and prepare rescue before any entry.'),
  ('bm1:B17-023', 'BM-I', 13, 'B17.18', 'When carrying small quantities of dangerous goods, the master should:', '["Stow them anywhere convenient","Know the hazards, stow and segregate them correctly, secure them and keep ignition sources clear","Carry them in the accommodation","Ignore the labels"]'::jsonb, 1, 'Answer B. Dangerous goods must be identified, correctly stowed, segregated and secured away from ignition/heat, with the master aware of the hazards and emergency action.')
on conflict (id) do update set
  course_code = excluded.course_code,
  module_seq  = excluded.module_seq,
  ref         = excluded.ref,
  stem        = excluded.stem,
  opts        = excluded.opts,
  correct     = excluded.correct,
  expl        = excluded.expl;

-- ---- Module-content (reader/deck-paden + gecureerde quizlijst) ----
-- Storage-paden in bucket 'course-content'. Volgnummer = modules.sequence.

update modules m set
  reader_path = 'bm1/readers/M01.pdf',
  deck_path   = 'bm1/decks/M01.pdf',
  quiz_ids    = '["bm1:A-015","bm1:B2-029","bm1:B3-003","bm1:B3-004","bm1:B6-001","bm1:B14-005"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-I' and m.sequence = 1;
update modules m set
  reader_path = 'bm1/readers/M02.pdf',
  deck_path   = 'bm1/decks/M02.pdf',
  quiz_ids    = '["bm1:B12-001","bm1:B12-002","bm1:B12-003","bm1:B16-001","bm1:B16-002","bm1:B16-003","bm1:B16-004","bm1:B16-005","bm1:B16-006","bm1:B16-007","bm1:B16-008","bm1:B3-001","bm1:B3-002","bm1:B3-003","bm1:B3-004","bm1:B9-001","bm1:B9-002","bm1:B9-003","bm1:B9-004"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-I' and m.sequence = 2;
update modules m set
  reader_path = 'bm1/readers/M03.pdf',
  deck_path   = 'bm1/decks/M03.pdf',
  quiz_ids    = '["bm1:B10-001","bm1:B10-002","bm1:B10-003","bm1:B10-004","bm1:B10-005","bm1:B14-001","bm1:B14-002","bm1:B14-003","bm1:B14-004","bm1:B14-005","bm1:B14-006","bm1:B14-007","bm1:B5-001","bm1:B5-002","bm1:B5-003","bm1:B5-004","bm1:B5-005","bm1:B5-006","bm1:B5-007","bm1:B5-008","bm1:B5-009","bm1:B5-010","bm1:B5-011","bm1:B5-012","bm1:B5-013","bm1:B5-014","bm1:B5-015","bm1:B5-016","bm1:B5-017","bm1:B5-018","bm1:B5-019"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-I' and m.sequence = 3;
update modules m set
  reader_path = 'bm1/readers/M04.pdf',
  deck_path   = 'bm1/decks/M04.pdf',
  quiz_ids    = '["bm1:B2-001","bm1:B2-002","bm1:B2-003","bm1:B2-004","bm1:B2-005","bm1:B2-006","bm1:B2-007","bm1:B2-008","bm1:B2-009","bm1:B2-010","bm1:B2-011","bm1:B2-012","bm1:B2-013","bm1:B2-014","bm1:B2-015","bm1:B2-016","bm1:B2-017","bm1:B2-018","bm1:B2-019","bm1:B2-020","bm1:B2-021","bm1:B2-022","bm1:B2-023","bm1:B2-024","bm1:B2-025","bm1:B2-026","bm1:B2-027","bm1:B2-028","bm1:B2-029","bm1:B2-030"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-I' and m.sequence = 4;
update modules m set
  reader_path = 'bm1/readers/M05.pdf',
  deck_path   = 'bm1/decks/M05.pdf',
  quiz_ids    = '["bm1:B4-001","bm1:B4-002","bm1:B4-003","bm1:B4-004","bm1:B4-005","bm1:B4-006","bm1:B4-007","bm1:B4-008"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-I' and m.sequence = 5;
update modules m set
  reader_path = 'bm1/readers/M06.pdf',
  deck_path   = 'bm1/decks/M06.pdf',
  quiz_ids    = '["bm1:A-001","bm1:A-002","bm1:A-003","bm1:A-004","bm1:A-005","bm1:A-006","bm1:A-007","bm1:A-008","bm1:A-009","bm1:A-010","bm1:A-011","bm1:A-012","bm1:A-013","bm1:A-014","bm1:A-015","bm1:A-016"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-I' and m.sequence = 6;
update modules m set
  reader_path = 'bm1/readers/M07.pdf',
  deck_path   = 'bm1/decks/M07.pdf',
  quiz_ids    = '["bm1:B11-001","bm1:B11-002","bm1:B11-003","bm1:B11-004","bm1:B11-005","bm1:B11-006","bm1:B11-007"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-I' and m.sequence = 7;
update modules m set
  reader_path = 'bm1/readers/M08.pdf',
  deck_path   = 'bm1/decks/M08.pdf',
  quiz_ids    = '["bm1:B1-001","bm1:B1-002","bm1:B1-003","bm1:B1-004","bm1:B1-005","bm1:B1-006","bm1:B1-007","bm1:B1-008","bm1:B1-009","bm1:B1-010","bm1:B1-011","bm1:B1-012","bm1:B1-013","bm1:B1-014","bm1:B8-001","bm1:B8-002","bm1:B8-003","bm1:B8-004","bm1:B8-005"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-I' and m.sequence = 8;
update modules m set
  reader_path = 'bm1/readers/M09.pdf',
  deck_path   = 'bm1/decks/M09.pdf',
  quiz_ids    = '["bm1:B13-001","bm1:B13-002","bm1:B13-003","bm1:B13-004","bm1:B13-005"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-I' and m.sequence = 9;
update modules m set
  reader_path = 'bm1/readers/M10.pdf',
  deck_path   = 'bm1/decks/M10.pdf',
  quiz_ids    = '["bm1:B1-008","bm1:B1-009","bm1:B1-010","bm1:B6-001","bm1:B6-002","bm1:B6-007","bm1:B7-001","bm1:B11-005"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-I' and m.sequence = 10;
update modules m set
  reader_path = 'bm1/readers/M11.pdf',
  deck_path   = 'bm1/decks/M11.pdf',
  quiz_ids    = '["bm1:B6-001","bm1:B6-002","bm1:B6-003","bm1:B6-004","bm1:B6-005","bm1:B6-006","bm1:B6-007","bm1:B7-001","bm1:B7-002","bm1:B7-003","bm1:B7-004","bm1:B7-005","bm1:B7-006"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-I' and m.sequence = 11;
update modules m set
  reader_path = 'bm1/readers/M12.pdf',
  deck_path   = 'bm1/decks/M12.pdf',
  quiz_ids    = '["bm1:B18-001","bm1:B18-002","bm1:B18-003","bm1:B1-001","bm1:B1-002","bm1:B1-006","bm1:B1-007","bm1:B1-010"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-I' and m.sequence = 12;
update modules m set
  reader_path = 'bm1/readers/M13.pdf',
  deck_path   = 'bm1/decks/M13.pdf',
  quiz_ids    = '["bm1:B15-001","bm1:B15-002","bm1:B15-003","bm1:B15-004","bm1:B15-005","bm1:B15-006","bm1:B15-007","bm1:B17-001","bm1:B17-002","bm1:B17-003","bm1:B17-004","bm1:B17-005","bm1:B17-006","bm1:B17-007","bm1:B17-008","bm1:B17-009","bm1:B17-010","bm1:B17-011","bm1:B17-012","bm1:B17-013","bm1:B17-014","bm1:B17-015","bm1:B17-016","bm1:B17-017","bm1:B17-018","bm1:B17-019","bm1:B17-020","bm1:B17-021","bm1:B17-022","bm1:B17-023"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-I' and m.sequence = 13;

-- Klaar.
