-- ============================================================
-- Plaza Boat College — Seed e-learning BM III
-- AUTOGEGENEREERD door scripts/gen-seed-bm3.mjs — niet handmatig bewerken.
-- Bron: data.js  ·  183 vragen
-- Idempotent: on conflict (id) do update. Voer uit NA migrations/0002_elearning.sql.
-- ============================================================

-- ---- Vragenbank (BM III) ----
insert into questions (id, course_code, module_seq, ref, stem, opts, correct, expl) values
  ('bm3:M01-001', 'BM-III', 1, 'Annex 11', 'Which chapter of the SCV Code 2021 covers licences for boatmasters and boat engineers?', '["Chapter VIII","Chapter X","Chapter I","Chapter V"]'::jsonb, 1, 'Answer B. Chapter X of the SCV Code covers licences for boatmasters and boat engineers.'),
  ('bm3:M01-002', 'BM-III', 1, 'Annex 11', 'What does Annex 11 of the SCV Code contain?', '["The examination syllabus for boatmaster and engineer licences","The construction and stability standards for the vessel","The list of life-saving appliances to be carried","The international rules to prevent collisions at sea"]'::jsonb, 0, 'Answer A. Annex 11 is the examination syllabus for the licences, set under Regulation X/8.'),
  ('bm3:M01-003', 'BM-III', 1, 'Table X/5.2', 'Under Table X/5.2, on what type of vessel and in which waters may a Grade 3 boatmaster operate?', '["A decked vessel in exposed waters","A passenger ship in coastal waters","An open boat in protected or coastal waters","Any vessel in protected waters at night"]'::jsonb, 2, 'Answer C. Table X/5.2: a Grade 3 boatmaster may command an open boat in protected or coastal waters. SCV Code 2021 · Caribbean Netherlands Page 2 / 40'),
  ('bm3:M01-004', 'BM-III', 1, 'Table X/5.2', 'What time-of-day restriction applies to a Grade 3 boatmaster licence?', '["No restriction","Daylight only","Night only","Between sunset and sunrise"]'::jsonb, 1, 'Answer B. A Grade 3 licence permits operation in daylight only (Table X/5.2).'),
  ('bm3:M01-005', 'BM-III', 1, 'X/6.1', 'What is the minimum age to be issued a Boatmaster Licence Grade 3 under Regulation X/6.1?', '["16 years","17 years","18 years","21 years"]'::jsonb, 2, 'Answer C. Regulation X/6.1 requires an applicant to be eighteen years of age or over.'),
  ('bm3:M01-006', 'BM-III', 1, 'X/6.1', 'A candidate is 18, holds a valid medical certificate, has completed practical instruction under a licensed boatmaster and has passed the Grade 3 theory exam, but cannot produce one further document required by X/6.1. What is most likely missing?', '["A VHF certificate","A passport photograph","A first aid instructor qualification","A vessel registration document"]'::jsonb, 0, 'Answer A. Regulation X/6.1 also requires the applicant to produce a VHF certificate.'),
  ('bm3:M01-007', 'BM-III', 1, 'X/8', 'What is the minimum mark needed to pass the BM III theory examination, out of a maximum of 50 points?', '["25","30","35","40"]'::jsonb, 2, 'Answer C. The theory exam requires a minimum of 35 out of a maximum of 50 points (about 70%).'),
  ('bm3:M01-008', 'BM-III', 1, null, 'A candidate has passed the theory paper and the fire-fighting, survival/passenger-safety and boat-handling practicals. Which separate assessment must they still complete to qualify?', '["A navigation chartwork test","An engine overhaul test","A Grade 2 oral examination","Elementary First Aid"]'::jsonb, 3, 'Answer D. Elementary First Aid is a separate assessment run outside the theory paper but required to qualify. SCV Code 2021 · Caribbean Netherlands Page 3 / 40'),
  ('bm3:M02-001', 'BM-III', 2, 'B3', 'Which islands make up the Caribbean Netherlands (BES)?', '["Aruba, Curacao and Sint Maarten","Bonaire, Sint Eustatius and Saba","Bonaire, Aruba and Curacao","Saba, Sint Maarten and Sint Eustatius"]'::jsonb, 1, 'Answer B. The Caribbean Netherlands (BES) comprises Bonaire, Sint Eustatius and Saba.'),
  ('bm3:M02-002', 'BM-III', 2, 'B3', 'To whom does a vessel owner apply for island registration in the Caribbean Netherlands?', '["The harbour master","The coastguard","The Administration of Shipping in The Hague","The local police"]'::jsonb, 0, 'Answer A. Island registration is required and you apply to the harbour master.'),
  ('bm3:M02-003', 'BM-III', 2, 'B3', 'An owner wants to operate a small commercial vessel in Bonaire. After island registration, what is the next step before it may operate?', '["Issue tickets to passengers immediately","Submit the vessel for certification under Annex 6 or the SCV Code","Apply for an international voyage permit","Register the vessel a second time with the coastguard"]'::jsonb, 1, 'Answer B. After registration the vessel is submitted for certification under either Annex 6 or the SCV Code.'),
  ('bm3:M02-004', 'BM-III', 2, 'B3', 'Your vessel previously held a Local certification and is now being certified under the SCV Code. What must you confirm regarding equipment?', '["That no equipment is required under the SCV Code","That Local and SCV certification always require identical equipment","That the equipment requirements may differ between Local and SCV certification","That equipment is decided solely by the boatmaster"]'::jsonb, 2, 'Answer C. Required equipment can differ between a Local and an SCV certification, so always confirm which applies.'),
  ('bm3:M02-005', 'BM-III', 2, null, 'What does RVZ Article 41b, first paragraph, establish for the Caribbean Netherlands?', '["The medical certificate validity period","The operating area for the Caribbean Netherlands, excluding certain parts","The minimum age for a boatmaster","The renewal cycle of the safety certificate"]'::jsonb, 1, 'Answer B. RVZ Article 41b, first paragraph, sets the operating area for the Caribbean Netherlands and excludes certain parts. SCV Code 2021 · Caribbean Netherlands Page 4 / 40'),
  ('bm3:M02-006', 'BM-III', 2, 'RVZ 62a', 'What does RVZ Article 62a contain?', '["The list of distress signals","The construction standards for open boats","The transitional regulations for Dutch Caribbean (Annex 6) ships","The pass mark for the theory examination"]'::jsonb, 2, 'Answer C. RVZ Article 62a contains the transitional regulations for Dutch Caribbean (Annex 6) ships.'),
  ('bm3:M02-007', 'BM-III', 2, null, 'How many passengers must a vessel carry to be classed as a passenger ship?', '["More than 6 passengers","More than 8 passengers","More than 12 passengers","More than 20 passengers"]'::jsonb, 2, 'Answer C. A passenger ship is a vessel, other than a pleasure vessel, carrying more than 12 passengers.'),
  ('bm3:M02-008', 'BM-III', 2, 'B3 / definitions', 'A skipper holding only a Grade 3 licence is asked to take charge of a vessel carrying 14 passengers. What is the correct position?', '["It is permitted because the vessel is small","It is permitted in daylight only","It is not permitted, as this is a passenger ship not covered by a Grade 3 licence","It is permitted in protected waters only"]'::jsonb, 2, 'Answer C. Carrying more than 12 passengers makes the vessel a passenger ship, which a Grade 3 licence does not cover.'),
  ('bm3:M02-009', 'BM-III', 2, null, 'Which of the following is excluded from the definition of a commercial vessel?', '["An excursion boat carrying passengers for reward","A fishing vessel","A vessel carrying cargo for reward","A boat carrying passengers on a voyage for reward"]'::jsonb, 1, 'Answer B. A commercial vessel carries cargo or passengers for reward; it does not include a fishing vessel.'),
  ('bm3:M02-010', 'BM-III', 2, 'Reg 10.8', 'Which regulation covers the crew certificate for a CN ship?', '["Reg 10.8","Reg 10.9","Reg 10.10","Reg 10.11"]'::jsonb, 0, 'Answer A. Reg 10.8 covers the crew certificate for a CN ship. SCV Code 2021 · Caribbean Netherlands Page 5 / 40'),
  ('bm3:M02-011', 'BM-III', 2, 'Reg 10.11', 'Which regulation applies to the master of a local CN ship (BM III)?', '["Reg 10.8","Reg 10.9","Reg 10.10","Reg 10.11"]'::jsonb, 3, 'Answer D. Reg 10.11 covers the master of a local CN ship (BM III).'),
  ('bm3:M02-012', 'BM-III', 2, 'Reg 10.10', 'Under Reg 10.10, how long is a medical fitness certificate valid for an Annex 6 ship and for an SCV Code ship respectively?', '["2 years (Annex 6) and 3 years (SCV Code)","3 years (Annex 6) and 2 years (SCV Code)","5 years (Annex 6) and 2 years (SCV Code)","3 years (Annex 6) and 5 years (SCV Code)"]'::jsonb, 1, 'Answer B. Reg 10.10: medical fitness is valid 3 years under Annex 6 and 2 years under the SCV Code.'),
  ('bm3:M02-013', 'BM-III', 2, 'Reg 10.11', 'A BM III applicant brings a BM III course certificate and a doctor''s medical statement to the harbour master for the RS licence. Which further document must they produce under Reg 10.11?', '["A tonnage certificate","A radar endorsement","A VHF certificate","An insurance policy"]'::jsonb, 2, 'Answer C. Reg 10.11 requires a BM III course certificate, a VHF certificate and a doctor''s medical statement.'),
  ('bm3:M02-014', 'BM-III', 2, 'Reg 10.11', 'Your RS licence is due for its three-year renewal. You provide a fresh doctor''s medical statement. What is the other requirement, including the minimum sailing time?', '["A re-sit of the theory paper","A statement of sailing time of at least 45 days in 3 years","A statement of sailing time of at least 90 days in 3 years","A new island registration"]'::jsonb, 1, 'Answer B. Renewal after three years requires a fresh medical statement plus a statement of sailing time of at least 45 days in 3 years.'),
  ('bm3:M02-015', 'BM-III', 2, 'Annex 6', 'How often must the engine of an Annex 6 vessel be serviced?', '["Once every 5 years","Once every 2 years","Once a year","Once every 6 months"]'::jsonb, 2, 'Answer C. Under Annex 6 the engine must be serviced periodically, once a year. SCV Code 2021 · Caribbean Netherlands Page 6 / 40'),
  ('bm3:M02-016', 'BM-III', 2, 'Annex 6', 'How often is the RS National Safety Certificate renewed, and when is the intermediate survey carried out?', '["Every 3 years, with an intermediate survey in the 1st year","Every 5 years, with no intermediate survey","Every 2 years, with an intermediate survey each year","Every 5 years, with an intermediate survey in the 2nd-3rd year"]'::jsonb, 3, 'Answer D. The RS National Safety Certificate is renewed every 5 years, with an intermediate survey in the 2nd-3rd year.'),
  ('bm3:M02-017', 'BM-III', 2, 'B9', 'Before crew handle paint and chemicals on board, which document should the boatmaster make sure they read?', '["The vessel''s tonnage certificate","The Material Safety Data Sheets (MSDS)","The passenger manifest","The COLREGs"]'::jsonb, 1, 'Answer B. Safe working practice requires reading the MSDS (Material Safety Data Sheets) for chemicals and paint.'),
  ('bm3:M02-018', 'BM-III', 2, null, 'Under SCV reg I/15, what does the SCV Safety Certificate record about persons carried?', '["The names of all crew on the voyage","The total number of persons permitted to be carried, as determined by the Administration","The number of passengers who have paid","The maximum cargo weight"]'::jsonb, 1, 'Answer B. Under SCV reg I/15 the total number of persons permitted to be carried is determined by the Administration and recorded on the SCV Safety Certificate.'),
  ('bm3:M02-019', 'BM-III', 2, null, 'Which of the following is part of a boatmaster''s basic security responsibilities on board?', '["Control who comes aboard and stay alert to unauthorised persons or suspicious activity","Allow anyone aboard at any time to keep the operation friendly","Leave the vessel unattended and unlocked between trips","Treat security as not applicable to small commercial vessels"]'::jsonb, 0, 'Answer A. B9.4 basic security: as part of legal responsibilities the boatmaster controls access to the vessel and stays alert to unauthorised access or suspicious activity.'),
  ('bm3:M03-001', 'BM-III', 3, null, 'In a written position, which coordinate is given first and what letters can it carry?', '["Latitude first, labelled N or S","Longitude first, labelled E or W","Latitude first, labelled E or W","Longitude first, labelled N or S"]'::jsonb, 0, 'Answer A. Latitude (distance N or S of the equator) is always written first, followed by longitude (E or W). SCV Code 2021 · Caribbean Netherlands Page 7 / 40'),
  ('bm3:M03-002', 'BM-III', 3, 'A1.8', 'What does longitude measure?', '["The depth of water below chart datum","Distance east or west of the Greenwich (prime) meridian","Distance north or south of the equator","The height of land above sea level"]'::jsonb, 1, 'Answer B. Longitude is the distance east or west of the Greenwich (prime) meridian, labelled E or W.'),
  ('bm3:M03-003', 'BM-III', 3, 'A1.8', 'Why is distance on a chart measured up the side rather than along the top?', '["Because the side scale is printed larger","Because the top edge is distorted by the chart projection","Because one minute of latitude equals one nautical mile","Because one minute of longitude equals one nautical mile"]'::jsonb, 2, 'Answer C. One minute of latitude equals one nautical mile, so distance is read off the latitude scale up the side.'),
  ('bm3:M03-004', 'BM-III', 3, 'A1.8', 'On the compass card, which direction corresponds to a bearing of 270°?', '["North","East","South","West"]'::jsonb, 3, 'Answer D. Directions increase clockwise from north: N 000°, E 090°, S 180°, W 270°.'),
  ('bm3:M03-005', 'BM-III', 3, 'A1.8', 'What is the compass bearing of due East?', '["090°","045°","135°","180°"]'::jsonb, 0, 'Answer A. East is 090° on the 360° compass card, increasing clockwise from north at 000°.'),
  ('bm3:M03-006', 'BM-III', 3, 'A1.8', 'Your vessel is steering a heading of 045°. In which direction is she travelling?', '["North-west","North-east","South-east","South-west"]'::jsonb, 1, 'Answer B. 045° is the intercardinal point north-east, midway between north (000°) and east (090°).'),
  ('bm3:M03-007', 'BM-III', 3, null, 'Why should a course or bearing always be expressed as three figures, such as 005°?', '["Because charts only accept three-figure entries","Because the compass card has exactly three rings","To avoid confusion between, for example, 5° and 50°","To convert degrees into nautical miles"]'::jsonb, 2, 'Answer C. Three figures (005°, 045°, 180°) prevent confusion between similar single- and double-digit values. SCV Code 2021 · Caribbean Netherlands Page 8 / 40'),
  ('bm3:M03-008', 'BM-III', 3, 'A1.8', 'What is the difference between a heading and a bearing?', '["A heading is where the boat is pointing; a bearing is the direction to an object","A heading is the direction to an object; a bearing is where the boat is pointing","A heading is measured in miles; a bearing is measured in degrees","They are two words for exactly the same thing"]'::jsonb, 0, 'Answer A. A heading (course) is where the boat is pointing; a bearing is the direction to an object.'),
  ('bm3:M03-009', 'BM-III', 3, 'A1.8', 'You take rough bearings of three charted landmarks and draw each on the chart. What does the point where they cross give you?', '["Your speed over the ground","The tidal set and drift","A simple position fix","The depth of water beneath you"]'::jsonb, 2, 'Answer C. Two or three crossed rough bearings of charted objects give a simple position fix.'),
  ('bm3:M03-010', 'BM-III', 3, 'B5.1', 'On a nautical chart, what does a small number (a sounding) tell you?', '["The distance to the nearest buoy","The height of a lighthouse","The charted depth of water at that spot","The compass bearing to a landmark"]'::jsonb, 2, 'Answer C. Soundings are charted depths of water in metres below chart datum, not distances.'),
  ('bm3:M03-011', 'BM-III', 3, 'B5.1', 'What does an underlined number (a drying height) on a chart indicate?', '["A height that uncovers at low water — a hazard","A safe deep-water channel","A recommended anchorage","The range of a nearby light"]'::jsonb, 0, 'Answer A. An underlined number is a drying height that uncovers at low water and is a hazard.'),
  ('bm3:M03-012', 'BM-III', 3, 'B5.1', 'On a chart the bottom abbreviation ''S'' tells the skipper the nature of the seabed is which of the following?', '["Stone","Sand","Shoal","Swell"]'::jsonb, 1, 'Answer B. Nature-of-bottom abbreviations include S (sand), M (mud), R (rock) and Co (coral).'),
  ('bm3:M03-013', 'BM-III', 3, 'B10.1', 'On the Beaufort scale, which force is described as a gale?', '["Force 6","Force 7","Force 8","Force 10"]'::jsonb, 2, 'Answer C. Force 8 is a gale (34–40 knots); a Grade III skipper stays in port well before then. SCV Code 2021 · Caribbean Netherlands Page 9 / 40'),
  ('bm3:M03-014', 'BM-III', 3, null, 'A hurricane on the Beaufort scale is force 12. From what wind speed does it begin?', '["34 knots and over","48 knots and over","56 knots and over","64 knots and over"]'::jsonb, 3, 'Answer D. Force 12 (hurricane) is 64 knots and over on the Beaufort scale.'),
  ('bm3:M03-015', 'BM-III', 3, 'B10.1', 'Which VHF channel should you keep a listening watch on for coastguard safety announcements and weather warnings?', '["Channel 6","Channel 16","Channel 12","Channel 72"]'::jsonb, 1, 'Answer B. VHF Channel 16 carries coastguard safety announcements and weather warnings; broadcasts then move to a working channel.'),
  ('bm3:M03-016', 'BM-III', 3, null, 'A marine bulletin states winds ''easterly, force 3 to 4, gusting force 5 in showers'' and seas ''slight to moderate, 0.5 to 1.5 m''. Which four things should you pull out for your trip?', '["Barometric pressure, tide times, moon phase and sunrise","Water temperature, salinity, current and chart datum","Wind direction and force, visibility, wave height, and any warning of change later","Engine load, fuel state, crew number and ETA"]'::jsonb, 2, 'Answer C. From a bulletin pull the wind (direction and force), visibility, wave height, and any warning of change later.'),
  ('bm3:M03-017', 'BM-III', 3, 'B10.2', 'An anchorage on a lee shore is calm in trade-wind weather, but the bulletin warns of a northerly swell. Why is this a concern?', '["The trade wind will drop to a flat calm","Swell only affects vessels under power, not at anchor","Swell raises the water temperature and fouls the engine intake","Northerly swell can break heavily on lee shores even when local wind is light, making the anchorage untenable ✓"]'::jsonb, 0, 'Answer D. Northerly swell from distant systems can break heavily on lee shores even in light wind, so have an alternative anchorage ready.'),
  ('bm3:M03-018', 'BM-III', 3, 'B10.3', 'You notice the barometer falling steadily, towering cumulonimbus building, and the wind beginning to shift and freshen. What does this classic combination indicate?', '["Settled fair weather is on the way","Bad weather is approaching — head for shelter early","A land breeze setting in for the night","Nothing of concern in the tropics"]'::jsonb, 1, 'Answer B. Falling pressure, building cumulonimbus and a shifting, freshening wind warn of approaching bad weather — seek shelter early. SCV Code 2021 · Caribbean Netherlands Page 10 / 40'),
  ('bm3:M04-001', 'BM-III', 4, 'B2.1', 'Which part of the COLREGs covers General matters such as application, responsibility and definitions?', '["Part A (Rules 1–3)","Part B (Rules 4–19)","Part C (Rules 20–31)","Part D (Rules 32–37)"]'::jsonb, 0, 'Answer A. Part A — General covers application, responsibility and definitions in Rules 1–3.'),
  ('bm3:M04-002', 'BM-III', 4, 'B7.1 / Annex IV', 'Which of the following is a recognised distress signal under Annex IV?', '["A single green flare","A white all-round light flashing twice","A black ball hoisted at the masthead","A red rocket or red hand flare, or an orange smoke signal"]'::jsonb, 3, 'Answer D. Annex IV distress signals include red rockets or hand flares and an orange smoke signal.'),
  ('bm3:M04-003', 'BM-III', 4, 'B7.1', 'Which Annex of the COLREGs contains the distress signals?', '["Annex I","Annex II","Annex III","Annex IV"]'::jsonb, 3, 'Answer D. Annex IV contains the distress signals; Annexes I–III cover lights/shapes, fishing signals and sound appliances.'),
  ('bm3:M04-004', 'BM-III', 4, null, 'Which spoken word, transmitted by radio, is a distress signal under Annex IV?', '["MAYDAY","PAN-PAN","SECURITE","ROGER"]'::jsonb, 0, 'Answer A. Annex IV lists the spoken word MAYDAY by radio, and SOS by any signalling method, as distress signals.'),
  ('bm3:M04-005', 'BM-III', 4, 'B2.3 / Rule 5', 'What does Rule 5 require of every vessel?', '["To carry radar at all times","To sound a fog signal every two minutes","To maintain a proper look-out by sight and hearing and by all available means at all times","To keep to the starboard side of any channel"]'::jsonb, 2, 'Answer C. Rule 5 requires a proper look-out by sight and hearing, and by all available means, at all times. SCV Code 2021 · Caribbean Netherlands Page 11 / 40'),
  ('bm3:M04-006', 'BM-III', 4, 'B2.3 / Rule 5', 'While conning your small craft you are tempted to keep your eyes on the chartplotter and your phone. What does Rule 5 require instead?', '["Use your eyes and ears first and do not let devices distract the person conning the boat","Rely on the chartplotter, which counts as a proper look-out","Post the look-out only when other vessels are visible","Keep a look-out only after dark or in fog"]'::jsonb, 0, 'Answer A. Rule 5: a proper look-out uses sight and hearing first; chartplotters and phones must not distract the conning skipper.'),
  ('bm3:M04-007', 'BM-III', 4, 'Rule 6', 'Which of the following is a factor a skipper must weigh in deciding a safe speed under Rule 6?', '["The colour of the other vessel''s hull","The nationality of the other vessel","The visibility at the time","The price of fuel"]'::jsonb, 2, 'Answer C. Rule 6 safe-speed factors include visibility, traffic density, wind/sea/current, navigational hazards and draft.'),
  ('bm3:M04-008', 'BM-III', 4, 'Rule 6', 'You are entering an area of fog, heavy traffic and shoals, with little depth under your keel. What does Rule 6 require?', '["Maintain full cruising speed to clear the area quickly","Proceed at a safe speed so you can take proper action and stop within an appropriate distance","Stop the engine and drift until the fog lifts","Increase speed to improve steerage"]'::jsonb, 1, 'Answer B. Rule 6 requires a safe speed — judged by visibility, traffic, hazards and draft — allowing effective action and stopping in time.'),
  ('bm3:M04-009', 'BM-III', 4, null, 'Under Rule 7, what is the key test when you are unsure whether risk of collision exists?', '["Assume no risk exists until you can prove otherwise","Wait for the other vessel to signal her intentions","If there is any doubt, assume that risk of collision exists and act accordingly","Increase speed to pass ahead before risk develops"]'::jsonb, 2, 'Answer C. Rule 7: if there is any doubt, risk of collision is deemed to exist and you must act accordingly.'),
  ('bm3:M04-010', 'BM-III', 4, 'Rule 7', 'An approaching vessel is getting steadily closer but its compass bearing is not changing. What does this tell you under Rule 7?', '["There is no risk because the bearing is steady","The other vessel will alter course in good time","You have right of way and need take no action","Risk of collision is present"]'::jsonb, 3, 'Answer D. Rule 7: a steady compass bearing of an approaching vessel that is closing means risk of collision exists. SCV Code 2021 · Caribbean Netherlands Page 12 / 40'),
  ('bm3:M04-011', 'BM-III', 4, null, 'Under Rule 8, an alteration of course to avoid collision should be which of the following?', '["Late, small and gradual","Early, substantial and obvious","Made only after the other vessel acts first","A series of small changes to keep options open"]'::jsonb, 1, 'Answer B. Rule 8 requires action that is positive, made in good time and seamanlike — early, substantial and obvious.'),
  ('bm3:M04-012', 'BM-III', 4, 'Rule 9', 'In a narrow channel, to which side should a vessel keep as far as is safe?', '["The port side","The centre of the channel","The starboard side","Whichever side has deepest water"]'::jsonb, 2, 'Answer C. Rule 9 requires a vessel in a narrow channel to keep to the starboard side as far as is safe.'),
  ('bm3:M04-013', 'BM-III', 4, 'Rule 9', 'You are skippering an 8 m power boat in a narrow channel where a large ship can only stay safe within the channel. What does Rule 9 require of you?', '["Insist on your right of way and hold your course","Not impede the large vessel, since you are under 20 m","Anchor in the middle of the channel and wait","Cross ahead of the large vessel as quickly as possible"]'::jsonb, 1, 'Answer B. Rule 9: a vessel under 20 m, or a sailing vessel, shall not impede a vessel that can only navigate safely within the channel.'),
  ('bm3:M04-014', 'BM-III', 4, 'Rule 12', 'When two sailing vessels have the wind on different sides, which one keeps out of the way?', '["The vessel with the wind on the starboard side","The vessel with the wind on the port side","The larger vessel","The vessel to leeward"]'::jsonb, 1, 'Answer B. Rule 12: with the wind on different sides, the vessel with the wind on the port side keeps out of the way.'),
  ('bm3:M04-015', 'BM-III', 4, null, 'Two sailing vessels have the wind on the same side. Which one must keep clear?', '["The vessel to leeward keeps clear of the one to windward","Neither — they pass freely","The vessel to windward keeps clear of the one to leeward","The faster of the two keeps clear"]'::jsonb, 2, 'Answer C. Rule 12: with the wind on the same side, the windward vessel keeps clear of the leeward vessel. SCV Code 2021 · Caribbean Netherlands Page 13 / 40'),
  ('bm3:M04-016', 'BM-III', 4, 'Rule 13', 'Until what point does an overtaking vessel remain the give-way vessel?', '["Until she draws level with the other vessel","Until the other vessel sounds a signal","Until she is finally past and clear","Until she has overtaken by one boat length"]'::jsonb, 2, 'Answer C. Rule 13: the overtaking vessel keeps out of the way and stays give-way until finally past and clear.'),
  ('bm3:M04-017', 'BM-III', 4, null, 'Your sailing vessel is overtaking a slower power-driven vessel. Who must keep clear?', '["Your sailing vessel, because the overtaking vessel always keeps clear","The power-driven vessel, because power gives way to sail","Neither, because they are different vessel types","Whichever vessel is the smaller"]'::jsonb, 0, 'Answer A. Rule 13 outranks other situations: even a sailing vessel overtaking a power-driven vessel must keep clear.'),
  ('bm3:M04-018', 'BM-III', 4, null, 'When two power-driven vessels meet head-on with risk of collision, what must each do?', '["Each alter course to port and pass starboard to starboard","Each alter course to starboard and pass port to port","The smaller vessel gives way to the larger","Each hold course and sound one short blast"]'::jsonb, 1, 'Answer B. Rule 14: each power-driven vessel alters course to starboard so they pass port to port.'),
  ('bm3:M04-019', 'BM-III', 4, 'Rule 14', 'At night you see another power-driven vessel''s masthead lights in line and both her sidelights, almost dead ahead. What action does Rule 14 require?', '["Hold your course and let her decide","Alter course to port and pass starboard to starboard","Stop and reverse engines","Alter course to starboard so you pass port to port"]'::jsonb, 3, 'Answer D. Rule 14: in a head-on situation alter to starboard and pass port to port; if in doubt, assume it is head-on.'),
  ('bm3:M04-020', 'BM-III', 4, null, 'In a crossing situation between two power-driven vessels, which vessel must give way?', '["The vessel which has the other on her own port side","The vessel which has the other on her own starboard side","The larger of the two vessels","The faster of the two vessels"]'::jsonb, 1, 'Answer B. Rule 15: the vessel which has the other on her starboard side keeps out of the way. SCV Code 2021 · Caribbean Netherlands Page 14 / 40'),
  ('bm3:M04-021', 'BM-III', 4, 'Rule 15', 'You are in a power-driven vessel and another power-driven vessel is crossing from your starboard side. What should you do?', '["Stand on and hold your course and speed","Cross ahead of her quickly","Give way — alter to starboard and pass astern of her","Alter to port and pass ahead of her"]'::jsonb, 2, 'Answer C. Rule 15: with the other vessel on your starboard side you are give-way — alter to starboard and pass astern.'),
  ('bm3:M04-022', 'BM-III', 4, 'Rule 17', 'You are the stand-on vessel, but it has become clear the give-way vessel is taking no action and collision is now imminent. What does Rule 17 permit and require?', '["You may act once it is clear the other is not acting, and you must act if collision cannot be avoided by her alone ✓","You must continue to stand on regardless","You must immediately turn to port","You have no authority to alter course as the stand-on vessel"]'::jsonb, 0, 'Answer A. Rule 17: the stand-on vessel may act when the give-way vessel is clearly not acting and must act if she alone cannot avoid collision.'),
  ('bm3:M04-023', 'BM-III', 4, 'Rule 18', 'In the Rule 18 ''pecking order'', which vessel keeps clear of all the others?', '["A vessel not under command","A vessel restricted in her ability to manoeuvre","A sailing vessel","A power-driven vessel"]'::jsonb, 3, 'Answer D. Rule 18 order (top to bottom): NUC, RAM, fishing, sailing, power — a power-driven vessel keeps clear of the rest.'),
  ('bm3:M04-024', 'BM-III', 4, 'Rule 18', 'You are skippering a power-driven vessel and a sailing vessel and a fishing vessel are both nearby with risk of collision. Under Rule 18, who keeps clear?', '["Your power-driven vessel keeps clear of both","The fishing vessel, because she is working","The sailing vessel, because she has no engine","Whichever vessel is largest"]'::jsonb, 0, 'Answer A. Rule 18: a power-driven vessel sits at the bottom of the order and keeps clear of fishing and sailing vessels.'),
  ('bm3:M04-025', 'BM-III', 4, 'Part C', 'What colour are the sidelights of a vessel underway?', '["Green to port and red to starboard","White both sides","Green to starboard and red to port","Red both sides"]'::jsonb, 2, 'Answer C. Sidelights are green to starboard and red to port. SCV Code 2021 · Caribbean Netherlands Page 15 / 40'),
  ('bm3:M04-026', 'BM-III', 4, 'Part C', 'By day you see a vessel showing three black balls in a vertical line. What does this tell you?', '["She is at anchor","She is engaged in fishing","She is aground","She is restricted in her ability to manoeuvre"]'::jsonb, 2, 'Answer C. A vessel aground shows two all-round red lights at night and three black balls by day.'),
  ('bm3:M05-001', 'BM-III', 5, 'B4.1', 'What does the term ''starboard'' refer to?', '["The right-hand side of the vessel when looking forward","The left-hand side of the vessel when looking forward","The forward end of the vessel","The widest part of the vessel"]'::jsonb, 0, 'Answer A. Starboard is the right-hand side looking forward, marked by a green light (Module 05, nautical terms).'),
  ('bm3:M05-002', 'BM-III', 5, null, 'Which term describes the vertical distance from the waterline up to the deck edge?', '["Draft","Air draft","Beam","Freeboard"]'::jsonb, 3, 'Answer D. Freeboard is the vertical distance from the waterline to the deck edge (Module 05, ship dimensions).'),
  ('bm3:M05-003', 'BM-III', 5, 'B4.1', 'What is meant by the ''draft'' of a vessel?', '["The greatest width of the hull","The full extreme length from bow to stern","The vertical distance from the waterline to the lowest point of the hull","The height of the highest fixed point above the waterline"]'::jsonb, 2, 'Answer C. Draft is the vertical distance from the waterline to the lowest point of the hull, governing minimum safe water depth (Module 05).'),
  ('bm3:M05-004', 'BM-III', 5, 'B4.1', 'You plan to pass beneath a fixed bridge. Which of the vessel''s dimensions tells you whether you can safely pass under it?', '["Air draft","Draft","Beam","Freeboard"]'::jsonb, 0, 'Answer A. Air draft — the height of the highest fixed point above the waterline — governs whether you can pass under a bridge or cable (Module 05). SCV Code 2021 · Caribbean Netherlands Page 16 / 40'),
  ('bm3:M05-005', 'BM-III', 5, 'B4.1', 'Which vessel type is described as carrying liquefied gases (LPG/LNG) under pressure and/or refrigerated?', '["Chemical tanker","Bulk carrier","Oil tanker","Gas tanker"]'::jsonb, 3, 'Answer D. A gas tanker carries liquefied gases such as LPG/LNG under pressure and/or refrigerated (Module 05, vessel types).'),
  ('bm3:M05-006', 'BM-III', 5, 'B4.1', 'A bulk carrier is designed to carry which kind of cargo?', '["Standardised containers stacked on deck and in holds","Dry bulk cargo such as ore, grain and coal in large holds","Liquid chemicals in segregated coated tanks","Vehicles on multiple internal decks"]'::jsonb, 1, 'Answer B. A bulk carrier carries dry bulk cargo (ore, grain, coal) in large holds (Module 05, vessel types).'),
  ('bm3:M05-007', 'BM-III', 5, 'Reserve buoyancy', 'What is ''reserve buoyancy''?', '["The weight of water a vessel displaces when floating","The watertight volume of the hull above the waterline","The total weight of cargo a vessel can carry","The depth of water below the keel"]'::jsonb, 1, 'Answer B. Reserve buoyancy is the watertight hull volume above the waterline, which lifts the vessel over waves and keeps it afloat if water comes aboard (Module 05).'),
  ('bm3:M05-008', 'BM-III', 5, 'Reserve buoyancy', 'As a vessel is progressively loaded with more weight, what happens to its freeboard and reserve buoyancy?', '["Freeboard increases and reserve buoyancy increases","Freeboard stays the same but reserve buoyancy increases","Both freeboard and reserve buoyancy reduce","Freeboard reduces but reserve buoyancy increases"]'::jsonb, 2, 'Answer C. As a vessel is loaded it sits deeper, freeboard reduces, and reserve buoyancy reduces with it (Module 05).'),
  ('bm3:M05-009', 'BM-III', 5, 'B17.16', 'For any vessel, the maximum load capacity is calculated from which factor?', '["The maximum permitted air draft","The greatest beam of the hull","The number of lifejackets carried","The minimum permitted freeboard"]'::jsonb, 3, 'Answer D. Maximum load capacity is calculated from the minimum permitted freeboard; at that freeboard no more weight may be added (Module 05, B17.16). SCV Code 2021 · Caribbean Netherlands Page 17 / 40'),
  ('bm3:M05-010', 'BM-III', 5, 'B17.16', 'The maximum number of persons on board is set by three things together. Which combination is correct?', '["Freeboard, stability and available life-saving appliances","Length, beam and air draft","Engine power, fuel capacity and range","Draft, displacement and cargo weight"]'::jsonb, 0, 'Answer A. Maximum persons is governed by freeboard (reserve buoyancy), stability and the available life-saving appliances, whichever gives the lowest figure (Module 05).'),
  ('bm3:M05-011', 'BM-III', 5, 'Loss of buoyancy', 'Which measure helps prevent loss of buoyancy through hull-penetrating piping below the waterline?', '["Fitting a valve at the hull so the pipe can be shut off if it fails","Painting the pipe with anti-fouling","Increasing the vessel''s freeboard","Carrying a spare bilge pump"]'::jsonb, 0, 'Answer A. Hull-penetrating piping below the waterline must have a valve at the hull so it can be shut off if it fails (Module 05).'),
  ('bm3:M05-012', 'BM-III', 5, 'A1.9', 'Which VHF channel is the international distress, safety and calling channel?', '["Channel 11","Channel 12","Channel 16","Channel 14"]'::jsonb, 2, 'Answer C. Channel 16 is the international distress, safety and calling channel (Module 05, VHF communications).'),
  ('bm3:M05-013', 'BM-III', 5, 'A1.9', 'Your vessel is taking on water and is in grave and imminent danger of sinking with people aboard. Which spoken priority word should you use on VHF?', '["SECURITE","PAN-PAN","MAYDAY","ROGER"]'::jsonb, 2, 'Answer C. MAYDAY signals distress — grave and imminent danger to a vessel or person — and has the highest priority (Module 05).'),
  ('bm3:M05-014', 'BM-III', 5, 'A1.9', 'You are approaching Bonaire and need to call Port Control on its working channel. After calling on Ch 16, which working channel does Bonaire Port Control use?', '["Channel 11","Channel 12","Channel 14","Channel 10"]'::jsonb, 0, 'Answer A. Bonaire Port Control uses channels 16 and 11; Ch 11 is the working channel (Module 05, VHF channel overview). SCV Code 2021 · Caribbean Netherlands Page 18 / 40'),
  ('bm3:M06-001', 'BM-III', 6, 'A1', 'What does the ''neutral (free)'' position of the gearbox do?', '["The propeller drives the vessel forward","The propeller drives the vessel backwards","The shaft is disconnected so the propeller does not drive","The engine is switched off"]'::jsonb, 2, 'Answer C. In neutral (free) the shaft is disconnected; the engine runs but the propeller does not drive (Module 06, gearbox).'),
  ('bm3:M06-002', 'BM-III', 6, 'A1', 'When changing between ahead and astern, why should you pause in neutral?', '["To allow the propeller to change direction by itself","To avoid shock-loading the gearbox","To increase the transverse thrust effect","To cool the engine before reversing"]'::jsonb, 1, 'Answer B. Move the control firmly but smoothly and pause in neutral when changing between ahead and astern to avoid shock-loading the gearbox (Module 06).'),
  ('bm3:M06-003', 'BM-III', 6, 'A1', 'For a right-handed propeller going ahead, which way does the stern walk?', '["To starboard","To port","Straight aft, with no sideways effect","Towards the wind"]'::jsonb, 0, 'Answer A. For a right-handed (clockwise) propeller going ahead, the stern walks to starboard and the bow swings to port (Module 06).'),
  ('bm3:M06-004', 'BM-III', 6, 'A1', 'For a right-handed propeller going astern, which way does the stern walk?', '["To port","To starboard","It does not move sideways","Always to leeward"]'::jsonb, 0, 'Answer A. For a right-handed propeller going astern, the stern walks to port (the bow swings to starboard) (Module 06).'),
  ('bm3:M06-005', 'BM-III', 6, 'A1', 'Your boat has a right-handed propeller and you wish to use the astern ''kick'' to draw the stern neatly in to the quay. Which berth should you approach?', '["A starboard-side berth","Either berth gives the same effect","A port-side berth","A berth directly downwind"]'::jsonb, 2, 'Answer C. Going astern the stern walks to port, so approaching a port-side berth lets the astern kick pull the stern in to the quay (Module 06). SCV Code 2021 · Caribbean Netherlands Page 19 / 40'),
  ('bm3:M06-006', 'BM-III', 6, 'B4.2', 'Two vessels are about to pass in a narrow channel. About a ship''s length apart, which way should both vessels initially alter?', '["Both alter to port","Both alter to starboard","Both hold the centre-line","The smaller vessel alters, the larger holds course"]'::jsonb, 1, 'Answer B. About a ship''s length apart both vessels alter to starboard (helm well over), then ease the rudder (Module 06, interaction procedure).'),
  ('bm3:M06-007', 'BM-III', 6, 'B4.2', 'What is the single best defence against dangerous interaction forces between passing vessels in a narrow or shallow channel?', '["Increase speed to pass quickly","Steer hard to port throughout","Slow down, since suction and cushion effects are small at low speed","Pass as close as possible to the bank"]'::jsonb, 2, 'Answer C. Interaction forces grow rapidly with speed and in shallow water; slowing down keeps the effects small and controllable (Module 06).'),
  ('bm3:M06-008', 'BM-III', 6, 'B4.3', 'A vessel with a large exposed superstructure is manoeuvring slowly in a strong beam wind. What effect should you expect?', '["It will be pushed bodily to leeward, especially at low speed","It will be drawn towards the wind","Wind has no effect below planing speed","It will only be affected if the engine is in neutral"]'::jsonb, 0, 'Answer A. High windage hulls are pushed bodily to leeward, especially at low speed when little water flows over the rudder to resist it (Module 06).'),
  ('bm3:M06-009', 'BM-III', 6, 'B4.3', 'What is Under-Keel Clearance (UKC)?', '["The distance from the waterline to the deck edge","The clearance between the propeller and the rudder","The water between the keel and the seabed","The depth of water needed to launch the anchor"]'::jsonb, 2, 'Answer C. UKC is the water between your keel and the seabed and must stay positive with a safe margin (Module 06).'),
  ('bm3:M06-010', 'BM-III', 6, 'B4.6', 'You are about to pass a row of berthed yachts at close distance. What is the correct action regarding your wash?', '["Maintain speed; wash is the other vessels'' concern","Ease back well before you reach them to limit your wash","Increase speed to clear the area quickly","Slow down only once you are level with them"]'::jsonb, 1, 'Answer B. You are responsible for damage your wash causes; ease back well before the hazard, not as you pass it (Module 06). SCV Code 2021 · Caribbean Netherlands Page 20 / 40'),
  ('bm3:M06-011', 'BM-III', 6, 'B4.4 / Annex 7', 'Under SCV Annex 7, what is the general minimum length of anchor line relative to a vessel that is 8 metres long overall?', '["Not less than 32 metres (4 x LOA)","Not less than 24 metres (3 x LOA)","Not less than 16 metres (2 x LOA)","Not less than 8 metres (1 x LOA)"]'::jsonb, 0, 'Answer A. SCV Annex 7: anchor line shall generally be not less than 4 times the vessel''s length overall, so 4 x 8 m = 32 m (Module 06).'),
  ('bm3:M06-012', 'BM-III', 6, 'B4.5', 'Why does adequate scope help an anchor hold?', '["It makes the pull on the anchor more vertical so it digs deeper","It makes the pull on the anchor more horizontal so it digs in","It adds weight to the anchor","It keeps the chain piled on top of the anchor"]'::jsonb, 1, 'Answer B. Adequate scope makes the pull more horizontal so the anchor digs in and holds; too little scope lifts the shank and the anchor drags (Module 06).'),
  ('bm3:M06-013', 'BM-III', 6, 'B4.8', 'Why is a polyamide (nylon) towline preferred for towing astern?', '["It floats so it cannot foul the propeller","It is cheaper than other ropes","It does not chafe at fairleads","It stretches and absorbs shock as the vessels surge"]'::jsonb, 3, 'Answer D. A polyamide (nylon) towline stretches and absorbs shock as the two vessels surge, instead of snatching (Module 06, towing).'),
  ('bm3:M06-014', 'BM-III', 6, 'B4.8', 'While towing, a beam pull from the tow threatens to roll the towing vessel over. What is this hazard called, and what control should you have ready?', '["Snap-back; keep clear of the line''s path","Chafe; protect the line at fairleads","Girting; keep the pull astern and have a means to slip the tow instantly","Squat; reduce draft by removing weight"]'::jsonb, 2, 'Answer C. Girting is a beam pull that can capsize the towing vessel; keep the pull astern and have a means to slip the tow instantly (Module 06, towing hazards).'),
  ('bm3:M06-015', 'BM-III', 6, 'A1.6', 'You must turn your boat right round in a space little longer than the boat itself. What is the correct technique?', '["Hold full ahead with the rudder hard over until she comes round","Go full astern with the rudder amidships","Alternate short bursts ahead (rudder hard over) with bursts astern, letting transverse thrust walk the stern and spin the boat in nearly its own length ✓","Drift with the wind and let the bow blow round"]'::jsonb, 0, 'Answer C. A1.6 turning short round: alternate ahead (rudder hard over) and astern bursts; the propeller''s transverse thrust walks the stern so the boat spins in almost its own length. SCV Code 2021 · Caribbean Netherlands Page 21 / 40'),
  ('bm3:M07-001', 'BM-III', 7, 'B11.2', 'What is the defining feature of planned (preventive) maintenance?', '["It is work carried out on a schedule before anything goes wrong","It is the repair made after a component has already failed","It is work carried out only when an inspector requires it","It is work that can only be done by a qualified marine engineer"]'::jsonb, 0, 'Answer A. Planned (preventive) maintenance is scheduled work done before failure, unlike corrective maintenance which repairs after a failure.'),
  ('bm3:M07-002', 'BM-III', 7, 'B11.2', 'Your engine has no running-hours clock fitted. How do you know when each service is due?', '["Service it only when the exhaust changes colour","Keep a logbook of the hours run so you can track service intervals","Service it on a fixed calendar date regardless of use","Wait for the manufacturer to contact you"]'::jsonb, 1, 'Answer B. With no running-hours clock you keep a logbook of hours run so you know when each scheduled service is due.'),
  ('bm3:M07-003', 'BM-III', 7, 'B11.2', 'How is a 2-stroke outboard engine lubricated?', '["From the crankcase / sump","By keel-cooling pipes outside the hull","By mixed (manual) lubrication — oil mixed into the fuel","By a sealed maintenance-free reservoir"]'::jsonb, 2, 'Answer C. The 2-stroke outboard uses mixed (manual) lubrication with oil mixed into the fuel; a 4-stroke is lubricated from the crankcase/sump.'),
  ('bm3:M07-004', 'BM-III', 7, 'B11.2', 'Where does a 4-stroke outboard engine take its lubrication from?', '["Oil mixed into the fuel","The crankcase / sump","The raw-water cooling circuit","The fuel water separator"]'::jsonb, 1, 'Answer B. A 4-stroke outboard is lubricated from the crankcase/sump, whereas a 2-stroke uses mixed (manual) lubrication.'),
  ('bm3:M07-005', 'BM-III', 7, 'B11.2', 'Which cooling arrangement draws seawater in through a hull fitting and requires a strainer to be checked and cleaned?', '["Keel cooling","Air cooling","Hybrid cooling","Raw-water (seawater) cooling"]'::jsonb, 3, 'Answer D. Raw-water cooling draws seawater past a raw-water strainer that traps weed and debris and must be checked and cleaned. SCV Code 2021 · Caribbean Netherlands Page 22 / 40'),
  ('bm3:M07-006', 'BM-III', 7, 'B11.2', 'Your vessel uses keel cooling. Why is there no raw-water strainer to clean on this system?', '["Because the engine coolant circulates through pipes in contact with the sea, so no seawater is drawn into the engine ✓","Because keel cooling uses air rather than any liquid","Because the strainer is fitted inside the gearbox instead","Because keel cooling relies on the exhaust gases for cooling"]'::jsonb, 0, 'Answer A. Keel cooling circulates engine coolant through pipes in contact with the cold seawater outside the hull, so no seawater is drawn in and there is no raw-water strainer.'),
  ('bm3:M07-007', 'BM-III', 7, 'B11.2', 'What is the traditional seal where the propeller shaft passes out through the stern tube, and how should it behave?', '["A waterjet impeller that should never move","A Morse cable that should be kept slack","A stuffing box (gland) that should drip only very slightly","A keel cooler that should be fully watertight at all times"]'::jsonb, 2, 'Answer C. The traditional shaft seal is a greased stuffing box (gland) tightened by a grease press; it should drip only very slightly.'),
  ('bm3:M07-008', 'BM-III', 7, null, 'Which engine check gives an early warning of trouble through a change you can see?', '["The colour of the exhaust gas","The tightness of the battery clamps","The expiry date on the fire extinguisher","The acidity read by the hydrometer"]'::jsonb, 0, 'Answer A. A change in exhaust-gas colour is an early warning of engine trouble and is part of the running checks.'),
  ('bm3:M07-009', 'BM-III', 7, 'B11.1', 'What is checked with the dipstick during the daily engine checks?', '["The V-belt tension","The oil level","The exhaust-gas colour","The raw-water strainer"]'::jsonb, 1, 'Answer B. The dipstick is used to check the engine oil level as part of the daily checks.'),
  ('bm3:M07-010', 'BM-III', 7, 'B11.4', 'On the drive of a waterjet-propelled vessel, which component is checked in place of the propeller?', '["The stuffing box","The Morse cable","The impeller","The dipstick"]'::jsonb, 2, 'Answer C. On a waterjet you check the impeller, which pumps water through the nozzle, instead of an exposed propeller. SCV Code 2021 · Caribbean Netherlands Page 23 / 40'),
  ('bm3:M07-011', 'BM-III', 7, 'B11.3', 'Before sailing, how should you satisfy yourself that the emergency shut-off valves and battery isolator will work in a fire?', '["Assume they work because they are new","Wait until a fire occurs and then test them","Know where each one is and prove to yourself they work before you sail","Leave them to the annual inspector to confirm"]'::jsonb, 2, 'Answer C. You must be able to stop the engine and isolate the fuel in an emergency, so know where every shut-off valve and the isolator are and prove they work before you sail.'),
  ('bm3:M07-012', 'BM-III', 7, null, 'Which item on the safety check should have its expiry date checked frequently?', '["The fire extinguisher","The V-belt","The propeller shaft","The water separator"]'::jsonb, 0, 'Answer A. The fire extinguisher''s expiry date must be checked frequently as part of the safety checks.'),
  ('bm3:M07-013', 'BM-III', 7, 'B11.5', 'When something goes wrong with the engine, what should you use to find the likely cause and remedy?', '["Guess based on the engine sound","The troubleshooting section of the engine manual","The Garbage Record Book","The vessel''s certificate of registry"]'::jsonb, 1, 'Answer B. Use the troubleshooting (trouble-recovery) section of the engine manual, which lists symptoms, likely causes and remedies for that exact engine.'),
  ('bm3:M07-014', 'BM-III', 7, 'B11.5', 'You are preparing for a day''s commercial work and want to be able to carry out simple emergency repairs at sea. What three things must be aboard and checked before you leave the berth?', '["Spare fuel, spare crew and a spare propeller","The engine manual, the manufacturer''s recommended spares and the correct tools","A SOPEP, an oil boom and a Garbage Record Book","A hydrometer, Vaseline and a spare V-belt only"]'::jsonb, 1, 'Answer B. Emergency repairs depend on the engine manual for troubleshooting, the manufacturer''s recommended spares, and the correct tools — all checked before departure.'),
  ('bm3:M07-015', 'BM-III', 7, 'B11.1', 'In what unit is battery capacity measured?', '["Volts (V)","Watts (W)","Ampere-hours (Ah)","Parts per million (ppm)"]'::jsonb, 2, 'Answer C. Battery capacity is measured in ampere-hours (Ah). SCV Code 2021 · Caribbean Netherlands Page 24 / 40'),
  ('bm3:M07-016', 'BM-III', 7, null, 'What is the nominal voltage of a single lead-acid cell, and what is its electrolyte?', '["2 V, with a sulphuric-acid electrolyte","12 V, with a fresh-water electrolyte","6 V, with a sodium-hydroxide electrolyte","1 V, with a lithium-based electrolyte"]'::jsonb, 0, 'Answer A. Each lead-acid cell is 2 V and the electrolyte is a sulphuric-acid solution.'),
  ('bm3:M07-017', 'BM-III', 7, 'B11.1', 'Why must a charging lead-acid battery box be placed high, ventilated, and kept away from naked flames?', '["Because the battery becomes very heavy when charging","Because charging gives off an explosive gas","Because the electrolyte freezes if mounted low","Because the clamps loosen at high temperature"]'::jsonb, 1, 'Answer B. A charging lead-acid battery gives off explosive gas, so the box is placed high, ventilated, with no naked flames, smoking or sparks.'),
  ('bm3:M07-018', 'BM-III', 7, 'B11.2', 'A lead-acid battery on your vessel was left flat for a long period and has lost much of its capacity permanently. What most likely happened?', '["The fluid rose too far above the plates","It self-discharged at 1% per day until full again","The plates sulphated because it was discharged too deeply","The cell voltage rose above 2 V"]'::jsonb, 2, 'Answer C. If a lead-acid battery is discharged too deeply the plates sulphate, permanently reducing capacity.'),
  ('bm3:M08-001', 'BM-III', 8, 'B8.1 / VIII/8', 'When organising passenger embarkation across the ship-to-shore gap, which provision is required at the access point?', '["Steps for all passengers including wheelchair users","An open quayside with no shore personnel","Safety nets, rails and lifebuoys with a safety line","Loose chains and ropes coiled near the brow"]'::jsonb, 2, 'Answer C. The reader requires safety nets, rails and lifebuoys with a safety line fitted at the access point to provide safe means of access. SCV Code 2021 · Caribbean Netherlands Page 25 / 40'),
  ('bm3:M08-002', 'BM-III', 8, null, 'Why must the deck be kept clear of chains, ropes and loose gear during embarkation?', '["To improve the vessel''s appearance for tourists","To increase the deck cargo capacity","Because the SCV Code forbids any deck equipment","Because they are trip hazards for people boarding"]'::jsonb, 3, 'Answer D. The reader states chains, ropes and loose gear must be cleared because they are trip hazards during the accident-prone embarkation phase.'),
  ('bm3:M08-003', 'BM-III', 8, 'B8.3 / VIII/7', 'Which SCV Code regulation requires an accurate record or correct written count of all persons embarking and disembarking?', '["Regulation VIII/7","Regulation VIII/8","Regulation VIII/10","Regulation VIII/15"]'::jsonb, 0, 'Answer A. Regulation VIII/7 (Record of passengers) requires an accurate record or correct written count of all persons aboard.'),
  ('bm3:M08-004', 'BM-III', 8, 'B8.3 / VIII/7', 'Before a coastal day-trip departs, a deckhand asks why the named passenger count must be deposited ashore before leaving. What is the correct reason to give?', '["It satisfies the vessel''s insurance paperwork only","It is needed to calculate the fare per head","It tells rescuers in a search and rescue how many persons to look for","It records who has paid for the trip"]'::jsonb, 2, 'Answer C. VIII/7 matters because in a search and rescue the count tells rescuers how many persons to look for.'),
  ('bm3:M08-005', 'BM-III', 8, 'B8.1 / VIII/8', 'Which of the following must the VIII/8 passenger safety announcement cover before getting under way?', '["The vessel''s fuel consumption figures","The names of all crew members on duty","The scheduled return time to the berth","The method of putting on and adjusting lifejackets, including a demonstration"]'::jsonb, 3, 'Answer D. Regulation VIII/8 requires the announcement to cover the proper method of putting on and adjusting lifejackets, including a demonstration.'),
  ('bm3:M08-006', 'BM-III', 8, null, 'Under VIII/8.2, what alternative to a full public announcement may the operator use?', '["Skip the briefing entirely on short coastal trips","Display a single sign at the gangway only","Give each passenger, or place near each seat, a card or pamphlet plus an abbreviated announcement","Rely on passengers asking the crew if they have questions"]'::jsonb, 2, 'Answer C. VIII/8.2 allows a card or pamphlet for each passenger or seat, together with an abbreviated announcement. SCV Code 2021 · Caribbean Netherlands Page 26 / 40'),
  ('bm3:M08-007', 'BM-III', 8, 'B8.1 / VIII/8.4', 'On a voyage of more than 12 hours, what additional action must passengers be requested to take during the safety orientation?', '["Sign a liability waiver and stow their luggage","Remain below decks for the duration of the orientation","Nominate a passenger leader for each section","Put on a lifejacket and go to the appropriate embarkation station"]'::jsonb, 3, 'Answer D. VIII/8.4 requires that on a voyage over 12 hours passengers put on a lifejacket and go to the appropriate embarkation station during the orientation.'),
  ('bm3:M08-008', 'BM-III', 8, 'B8.1 / VIII/8.5', 'Your vessel is about to transit a hazardous bar in worsening weather. Under VIII/8.5, what must the master require of passengers?', '["That they move to the bow for better visibility","That they stand to brace against the motion","That they wear lifejackets","That they remain on the open deck"]'::jsonb, 2, 'Answer C. VIII/8.5 requires passengers to wear lifejackets in hazardous conditions including transiting hazardous bars and inlets and severe weather.'),
  ('bm3:M08-009', 'BM-III', 8, 'B8.5 / VIII/8.5', 'Which of the following is a condition listed in the reader where passengers must wear lifejackets?', '["Calm water and clear daylight","Routine berthing alongside in harbour","Flooding, fire or other events that may call for evacuation","Passengers eating a meal on a sheltered deck"]'::jsonb, 2, 'Answer C. VIII/8.5 lists flooding, fire or other events which may call for evacuation among the hazardous conditions requiring lifejackets.'),
  ('bm3:M08-010', 'BM-III', 8, 'B8.2', 'On a small open Grade III boat, passengers begin crowding to one side to look at a seal. To protect stability and trim, what should you do?', '["Allow it, as passengers always know best where to sit","Speed up so the wash steadies the boat","Move all the crew to the opposite side to balance it permanently","Direct passengers to remain seated and evenly distributed"]'::jsonb, 3, 'Answer D. The reader requires passengers to remain seated and evenly distributed so the vessel stays in trim and stable.'),
  ('bm3:M08-011', 'BM-III', 8, 'B1.1', 'A passenger falls overboard from your open boat in daylight. What is the correct FIRST action?', '["Broadcast a distress message on VHF Channel 16","Keep visual contact with the person in the water","Sound the bilges and tanks","Prepare to launch the liferaft"]'::jsonb, 1, 'Answer B. The man-overboard action list begins with keeping visual contact with the person, then releasing the MOB buoy and sounding the alarm. SCV Code 2021 · Caribbean Netherlands Page 27 / 40'),
  ('bm3:M08-012', 'BM-III', 8, 'B1.4', 'Immediately after a collision, after sounding the general alarm, which action follows in the reader''s collision list?', '["Abandon ship at once","Beach the vessel without assessment","Manoeuvre the ship to minimise the effects of the collision","Shut down all electrical power"]'::jsonb, 2, 'Answer C. The collision list: sound the general alarm, then manoeuvre to minimise the effects, switch to VHF 16, muster passengers, sound bilges and tanks, broadcast.'),
  ('bm3:M08-013', 'BM-III', 8, null, 'In the stranding or grounding action list, which step is specific to that emergency?', '["Release the MOB buoy","Don lifejackets and abandon ship","Engage the emergency steering","Minimise the vessel''s draught"]'::jsonb, 3, 'Answer D. The grounding list includes minimising the vessel''s draught, alongside sounding the alarm, switching to VHF 16, mustering and sounding around the ship.'),
  ('bm3:M08-014', 'BM-III', 8, 'B1.7 / VIII/10', 'A fire is discovered aboard your passenger vessel. According to the reader''s fire action list, what is the correct FIRST action?', '["Determine the fire-attack plan","Sound the fire alarm","Position the ship for wind and smoke","Broadcast a distress call"]'::jsonb, 1, 'Answer B. The fire list begins with sounding the fire alarm, then informing the skipper and mustering with a head count.'),
  ('bm3:M08-015', 'BM-III', 8, 'B1.6', 'Water is entering the hull. After sounding the general alarm and sounding the bilges and tanks, what is the next step in the flooding list?', '["Identify where the water is coming in","Abandon ship immediately","Release the MOB buoy","Minimise the vessel''s draught"]'::jsonb, 0, 'Answer A. The flooding list continues with identifying where the water is coming in, then checking the bilge pump and determining the attack plan.'),
  ('bm3:M08-016', 'BM-III', 8, 'B1.4', 'In the abandon-ship action list, what comes immediately after broadcasting?', '["Marshal the liferafts together","Sound the bilges and tanks","Don lifejackets","Minimise the vessel''s draught"]'::jsonb, 2, 'Answer C. Abandon ship: broadcast, don lifejackets, prepare to launch, muster at embarkation stations, embark and launch, then marshal the rafts together. SCV Code 2021 · Caribbean Netherlands Page 28 / 40'),
  ('bm3:M08-017', 'BM-III', 8, 'B1.5', 'You may have to beach your vessel. Which of the following is one of the considerations the reader says you must weigh before committing?', '["The colour of the lifejackets aboard","The number of crew certificates held","The cost of repairs after beaching","The amount of surf, since high spray indicates rough surf"]'::jsonb, 3, 'Answer D. Beaching considerations include the seabed nature, amount of surf (high spray means rough surf), shelving, type of coastline and proximity of hazards.'),
  ('bm3:M08-018', 'BM-III', 8, null, 'Under Regulation VIII/15, how must escape hatches and emergency exits be marked?', '["\"EMERGENCY EXIT, KEEP CLEAR\"","\"KEEP CLOSED\" on both sides","With the vessel''s identity number only","\"NO ENTRY\" in red lettering"]'::jsonb, 0, 'Answer A. VIII/15 requires escape hatches and emergency exits to be marked "EMERGENCY EXIT, KEEP CLEAR"; watertight doors are marked "KEEP CLOSED".'),
  ('bm3:M08-019', 'BM-III', 8, null, 'In relation to lifejackets, what must the master be able to do for passengers?', '["Store the lifejackets out of reach to keep the deck clear","Issue lifejackets only once an emergency has begun","Assume passengers have used a lifejacket before","Demonstrate to passengers how to correctly put on and use the personal life-saving appliances"]'::jsonb, 3, 'Answer D. B8.5 (Reg VIII/8): the master must be able to demonstrate to passengers the correct donning and use of personal life-saving appliances as part of the safety briefing.'),
  ('bm3:M09-001', 'BM-III', 9, 'B13.1', 'Which disaster set in motion the chain of events leading to MARPOL?', '["The grounding and oil spill of the supertanker Torrey Canyon","The sinking of the Titanic","The Exxon Valdez running aground in Alaska","The capsize of the Herald of Free Enterprise"]'::jsonb, 0, 'Answer A. The Torrey Canyon ran aground in 1967 and spilled its oil cargo, essentially triggering the events leading to MARPOL.'),
  ('bm3:M09-002', 'BM-III', 9, 'B13.1', 'In which years was the MARPOL Convention adopted and brought into force?', '["Adopted 1967, in force 1970","Adopted 1973, in force 1983","Adopted 1983, in force 1990","Adopted 1990, in force 2000"]'::jsonb, 1, 'Answer B. MARPOL was adopted in 1973 and entered into force in 1983. SCV Code 2021 · Caribbean Netherlands Page 29 / 40'),
  ('bm3:M09-003', 'BM-III', 9, 'B13.1', 'Which type of pollution does MARPOL Annex I cover?', '["Garbage","Sewage","Oil","Air pollution"]'::jsonb, 2, 'Answer C. Annex I covers oil pollution from all ships, with Part B adding oil-tanker cargo rules.'),
  ('bm3:M09-004', 'BM-III', 9, 'B13.1', 'MARPOL Annex II covers the pollution caused by which substances?', '["Sewage from holding tanks","Packaged dangerous goods","Garbage and plastics","Noxious liquid substances carried by chemical tankers"]'::jsonb, 3, 'Answer D. Annex II covers noxious liquid substances carried by chemical tankers.'),
  ('bm3:M09-005', 'BM-III', 9, 'B13.1', 'Which MARPOL Annex deals with packaged (packed) dangerous goods?', '["Annex III","Annex IV","Annex V","Annex VI"]'::jsonb, 0, 'Answer A. Annex III covers packaged (packed) dangerous goods.'),
  ('bm3:M09-006', 'BM-III', 9, null, 'MARPOL Annex IV and Annex V cover which two kinds of pollution respectively?', '["Oil and air pollution","Sewage and garbage","Chemicals and packaged dangerous goods","Ballast water and anti-fouling"]'::jsonb, 1, 'Answer B. Annex IV covers sewage and Annex V covers garbage.'),
  ('bm3:M09-007', 'BM-III', 9, 'B13.1', 'Which kind of pollution is covered by MARPOL Annex VI?', '["Oil","Sewage","Garbage","Air pollution"]'::jsonb, 3, 'Answer D. Annex VI covers air pollution from ships.'),
  ('bm3:M09-008', 'BM-III', 9, 'B13.1', 'What is the purpose of the SOPEP (Shipboard Oil Pollution Emergency Plan)?', '["To set out what to do if there is any discharge of oil","To record how garbage was disposed of ashore","To list the safe stowage of packaged dangerous goods","To schedule the engine''s planned maintenance"]'::jsonb, 0, 'Answer A. The SOPEP sets out the immediate response and ship tasks to follow for any discharge of oil. SCV Code 2021 · Caribbean Netherlands Page 30 / 40'),
  ('bm3:M09-009', 'BM-III', 9, 'B13.1', 'You notice oil discharging from your vessel. According to the SOPEP immediate response, what should you do first?', '["Deploy the oil boom and begin ballasting","Report it / raise the alarm and stop the source","Continue the voyage and report it on arrival","Pump the oily water into the bilge for later disposal"]'::jsonb, 1, 'Answer B. The first SOPEP response to any oil discharge is to report it/raise the alarm and stop the source before it becomes a major incident.'),
  ('bm3:M09-010', 'BM-III', 9, 'B13.2', 'What is the rule on pumping oily water from the bilge overboard?', '["It is allowed at night when no other vessels are near","It is allowed once the oil has settled to the bottom","You must never pump oily water overboard","It is allowed provided it is more than 12 miles offshore"]'::jsonb, 2, 'Answer C. The bilge is not a place for oily water and you must never pump oily water overboard.'),
  ('bm3:M09-011', 'BM-III', 9, 'B13.2', 'You are about to change the engine''s lubricating oil at the berth. What precaution best prevents pollution?', '["Let any spills run into the bilge to be pumped out later","Tip the old oil over the side while moving slowly","Contain the old oil, catch every drip and keep it away from anything draining to the sea","Dilute the old oil with seawater before disposal"]'::jsonb, 2, 'Answer C. When changing lubricating oil you must contain the old oil, catch every drip and keep it well away from anything that drains to the sea.'),
  ('bm3:M09-012', 'BM-III', 9, 'B13.3', 'What does MARPOL say about discharging plastics — such as synthetic ropes, plastic sheeting and garbage bags — into the sea?', '["It is permitted beyond 25 miles from land","The discharge of all plastics into the sea is prohibited","It is permitted if the plastic is biodegradable","It is permitted in small quantities"]'::jsonb, 1, 'Answer B. The discharge of all plastics into the sea is prohibited, with no exceptions, including synthetic ropes, plastic sheeting and garbage bags.'),
  ('bm3:M09-013', 'BM-III', 9, 'B13.3', 'You have landed garbage at a port reception facility and want to keep proper evidence that the waste was managed correctly. Which record do you complete?', '["The Oil Record Book","The sewage record","The SOPEP log","The Garbage Record Book"]'::jsonb, 3, 'Answer D. Garbage handling is logged in the Garbage Record Book, which records what was produced and how it was disposed of. SCV Code 2021 · Caribbean Netherlands Page 31 / 40'),
  ('bm3:M09-014', 'BM-III', 9, 'B13.1', 'When landing oily water, oil residue or lubricating oil at a port reception facility, which record book is kept?', '["The Oil Record Book","The Garbage Record Book","The sewage record","The Garbage Management Plan"]'::jsonb, 0, 'Answer A. Oily water, oil residue and lubricating oil landed ashore are recorded in the Oil Record Book.'),
  ('bm3:M10-001', 'BM-III', 10, 'B1.8', 'Which of the following is a basic fire-prevention housekeeping measure aboard a small craft?', '["Storing oily rags in a warm, enclosed locker","Placing combustible material close to heat sources to dry it","Keeping spaces clean and free of oily rags and rubbish","Sealing battery compartments to prevent any ventilation"]'::jsonb, 2, 'Answer C. Good housekeeping means keeping spaces clean and free of oily rags and rubbish, and separating combustibles from heat sources.'),
  ('bm3:M10-002', 'BM-III', 10, 'B1.8', 'What are the three sides of the fire triangle?', '["Smoke, flame and ash","Water, foam and powder","Fuel, friction and pressure","Oxygen, heat and combustible material or vapours"]'::jsonb, 3, 'Answer D. The fire triangle is oxygen, heat (temperature) and combustible material or vapours; all three must be present at once.'),
  ('bm3:M10-003', 'BM-III', 10, 'B1.8', 'Which fourth element, added to the three sides of the triangle, forms the fire tetrahedron?', '["The self-sustaining chain reaction","An additional oxygen supply","The smoke produced","The auto-ignition temperature"]'::jsonb, 0, 'Answer A. Once burning, a self-sustaining chain reaction is added as the fourth element, turning the triangle into the tetrahedron.'),
  ('bm3:M10-004', 'BM-III', 10, 'B1.8', 'To stop combustion by removing oxygen, to roughly what level should the oxygen content be reduced from the normal 21%?', '["About 15%","About 10%","Down to 2–3%, ideally 0%","About 8%"]'::jsonb, 2, 'Answer C. The reader states bringing oxygen down to 2–3%, ideally 0%, stops combustion. SCV Code 2021 · Caribbean Netherlands Page 32 / 40'),
  ('bm3:M10-005', 'BM-III', 10, 'B1.8', 'You close a small compartment door on a contained fire and seal the openings. Which side of the fire triangle are you removing?', '["Heat, by cooling the fire","Fuel, by closing the supply","Oxygen, by smothering the fire","The chain reaction, chemically"]'::jsonb, 2, 'Answer C. Closing the compartment to smother the fire removes the oxygen side of the triangle.'),
  ('bm3:M10-006', 'BM-III', 10, 'B1.8', 'Approximately what is the flash point of diesel?', '["About 21 °C","About 52 °C","About 210 °C","About 100 °C"]'::jsonb, 1, 'Answer B. Diesel has a flash point of about 52 °C — the temperature at which it gives off enough vapour to flash with an ignition source.'),
  ('bm3:M10-007', 'BM-III', 10, 'B1.8', 'Why do gases ignite more easily than liquids or solids?', '["They are always hotter to begin with","They contain more oxygen internally","They have a higher auto-ignition temperature","Finely divided fuels, mists and gases react with surrounding air using far less energy"]'::jsonb, 3, 'Answer D. Finely divided fuels, mists and gases react with the surrounding air using far less energy, so gases ignite more easily.'),
  ('bm3:M10-008', 'BM-III', 10, 'B1.7', 'Which fire class covers liquids such as petrol, oil, paint and grease?', '["Class A","Class B","Class C","Class D"]'::jsonb, 1, 'Answer B. Class B covers liquids (petrol, oil, paint, fat, grease); Class A is solids, C gases, D metals, F cooking oil.'),
  ('bm3:M10-009', 'BM-III', 10, 'B1.7', 'A fire in a deep-fat fryer involving cooking oil falls into which fire class?', '["Class A","Class B","Class D","Class F"]'::jsonb, 3, 'Answer D. Class F covers cooking oil and deep-fat fryers.'),
  ('bm3:M10-010', 'BM-III', 10, 'B1.7', 'Burning aluminium or magnesium is an example of which fire class?', '["Class D (metals)","Class A (solids)","Class C (gases)","Class B (liquids)"]'::jsonb, 0, 'Answer A. Class D covers metal fires such as aluminium and magnesium. SCV Code 2021 · Caribbean Netherlands Page 33 / 40'),
  ('bm3:M10-011', 'BM-III', 10, 'B1.7', 'A crew member moves to throw a bucket of water on a burning pan of fat. Why is this dangerous?', '["Water is too cold and will crack the pan","Water has no extinguishing effect on any fire","Water spreads liquid fires and is unsuitable for a Class B fat fire","Water would put it out too quickly and waste effort"]'::jsonb, 2, 'Answer C. Water spreads liquid fires and must not be used on a Class B liquid fire such as burning fat.'),
  ('bm3:M10-012', 'BM-III', 10, null, 'Which is a recognised disadvantage of using water as an extinguishing agent?', '["It is scarce and expensive at sea","It conducts electricity","It provides no personal protection","It chemically reacts to produce toxic gas"]'::jsonb, 1, 'Answer B. Water conducts electricity, can spread liquid fires and causes water damage; it suits only Class A fires.'),
  ('bm3:M10-013', 'BM-III', 10, 'B1.7', 'A spilt-fuel fire is burning on the deck of your boat. Which agent and mechanism is most appropriate?', '["Water, by cooling the surface","A fire blanket dropped from a distance","Foam, by covering the surface and cutting off oxygen","Adding more oxygen to dilute the fuel"]'::jsonb, 2, 'Answer C. Foam suits Class B liquid fires; it extinguishes by covering the surface and cutting off oxygen, with secondary cooling.'),
  ('bm3:M10-014', 'BM-III', 10, 'B1.7', 'Which statement about dry powder is correct?', '["It gives a very fast knockdown but has no cooling effect","It conducts electricity and must not touch wiring","It is only suitable for Class A fires","It works best when combined with foam"]'::jsonb, 0, 'Answer A. Powder gives a very fast response on Class A, B and C, does not conduct electricity, but has no cooling effect and must not be combined with foam.'),
  ('bm3:M10-015', 'BM-III', 10, 'B1.7', 'Which agent must never be combined with dry powder?', '["Water","CO₂","A fire blanket","Foam"]'::jsonb, 3, 'Answer D. The reader warns powder must not be used together with foam. SCV Code 2021 · Caribbean Netherlands Page 34 / 40'),
  ('bm3:M10-016', 'BM-III', 10, 'B1.7', 'A fire breaks out in an enclosed engine compartment. Which agent works best there, and how does it extinguish the fire?', '["Water, by cooling the metal","CO₂, by displacing the oxygen in the enclosed space","Foam, by deep-seated penetration","Powder, by cooling the fire below combustion temperature"]'::jsonb, 1, 'Answer B. CO₂ works by displacing oxygen and is best in enclosed spaces such as machinery compartments.'),
  ('bm3:M10-017', 'BM-III', 10, 'B1.7', 'Which figures correctly describe CO₂ as an extinguishing agent?', '["About 1.5× heavier than air, with 10% concentration lethal to humans","About 1.5× lighter than air, with 21% concentration lethal","Equal density to air, with no suffocation risk","About 3× heavier than air, with 2% concentration lethal"]'::jsonb, 0, 'Answer A. CO₂ is about 1.5× heavier than air so it sinks into low spaces, and a 10% concentration is lethal to humans.'),
  ('bm3:M10-018', 'BM-III', 10, 'B1.7', 'You are about to attack a fire aboard. According to the tactical rules, which principle should guide your very first move?', '["Surround the fire completely before doing anything else","Prevent secondary water damage above all","Tackle the greatest danger first while protecting personal safety","Ventilate the space fully to clear the smoke"]'::jsonb, 2, 'Answer C. The tactical rules begin with tackling the greatest danger first and protecting personal safety, then preventing spread, surrounding the fire and preventing secondary damage.'),
  ('bm3:M11-001', 'BM-III', 11, 'B1.9 / VI', 'Which of the following is shown on a vessel''s safety plan?', '["Muster stations, life-saving appliances, emergency exits and fire-fighting equipment","The crew watch rota and meal times","The intended passage plan and waypoints","The engine maintenance schedule"]'::jsonb, 0, 'Answer A. The safety plan marks fire-fighting equipment, emergency exits, safety equipment, LSA, muster stations and emergency signals.'),
  ('bm3:M11-002', 'BM-III', 11, null, 'Where on a vessel are lifebuoys located and what markings must they carry?', '["On the foredeck only, marked with the owner''s name","Stowed below deck in a locker, marked with their expiry date","On both sides of the open decks, marked with the ship''s name and port of registry","At the helm only, marked with the maximum number of persons"]'::jsonb, 2, 'Answer C. Lifebuoys are located on both sides of the ship on the open decks and marked with the ship''s name and home port (port of registry). SCV Code 2021 · Caribbean Netherlands Page 35 / 40'),
  ('bm3:M11-003', 'BM-III', 11, 'B1.9 / VI/6', 'A self-righting lifejacket should turn an unconscious person face-up within how long, and hold the chin roughly how far above the water?', '["Within 10 seconds, chin about 6 cm above the water","Within 5 seconds, chin about 12 cm above the water","Within 15 seconds, chin about 20 cm above the water","Within 3 seconds, chin about 30 cm above the water"]'::jsonb, 1, 'Answer B. A good lifejacket self-rights within 5 seconds, holding the chin about 12 cm above the water.'),
  ('bm3:M11-004', 'BM-III', 11, 'B1.9 / VI/6', 'From what height should a wearer be able to jump safely into the water in a properly designed lifejacket?', '["1.5 m","3.0 m","6.0 m","4.5 m"]'::jsonb, 3, 'Answer D. A lifejacket should allow the wearer to jump safely from a height of 4.5 m into the water.'),
  ('bm3:M11-005', 'BM-III', 11, 'B1.9 / VI/6', 'Approximately what weight-capacity range should a range of lifejackets cover for the persons on board?', '["About 20 kg to 90 kg","About 30 kg to 120 kg","About 43 kg to 140 kg","About 50 kg to 160 kg"]'::jsonb, 2, 'Answer C. Lifejackets cater from a lower level of about 43 kg up to about 140 kg, with infant, child and adult types.'),
  ('bm3:M11-006', 'BM-III', 11, 'B1.9 / VI/6', 'A deckhand is wearing a work vest while working on the open deck in fine weather. Is the work vest an acceptable substitute for a lifejacket?', '["Yes, a work vest provides the same protection as a lifejacket","No, a work vest is a buoyancy aid and is not a substitute for a full lifejacket","Yes, provided the deckhand can swim","Yes, because it is daylight and the sea is calm"]'::jsonb, 1, 'Answer B. A work vest is a buoyancy aid worn while working on deck; it is not a full lifejacket and is not a substitute for one.'),
  ('bm3:M11-007', 'BM-III', 11, 'B1.9 / VI/6', 'How many lifejackets must be provided on board?', '["One lifejacket for every two persons on board","Only enough for the crew, not the passengers","One lifejacket per survival craft","One lifejacket for every person on board"]'::jsonb, 3, 'Answer D. A lifejacket must be provided for every person on board, with spares kept in different locations. SCV Code 2021 · Caribbean Netherlands Page 36 / 40'),
  ('bm3:M11-008', 'BM-III', 11, 'B7 / VI/4', 'Which of the following is an aid to location used to help rescuers find you?', '["A signalling mirror (heliograph)","A sea anchor","A bilge pump","An emergency tiller"]'::jsonb, 0, 'Answer A. Aids to location include pyrotechnics, a signalling mirror, a whistle, a radar reflector and retro-reflective material.'),
  ('bm3:M11-009', 'BM-III', 11, 'B7', 'On a handheld VHF radio, which channel is used for distress and safety calls?', '["Channel 6","Channel 67","Channel 16","Channel 72"]'::jsonb, 2, 'Answer C. For distress and safety use, handheld VHF radios use Channel 16.'),
  ('bm3:M11-010', 'BM-III', 11, 'B7', 'Why is an EPIRB fitted with a Hydrostatic Release Unit (HRU)?', '["So it can be charged from the vessel''s batteries","So it can be used as a handheld torch","So it transmits only when switched on by hand","So it floats free and transmits automatically if the vessel sinks"]'::jsonb, 3, 'Answer D. An EPIRB fitted with an HRU floats free and transmits automatically if the vessel sinks.'),
  ('bm3:M11-011', 'BM-III', 11, 'B7', 'What does a SART (Search and Rescue Transponder) do?', '["Broadcasts a voice distress message on Channel 16","Shows the vessel''s position as a line of dots on a rescuer''s radar screen","Releases an oil slick to mark the position","Sounds a continuous audible alarm only"]'::jsonb, 1, 'Answer B. A SART shows the vessel''s position as a line of dots on a rescuer''s radar screen.'),
  ('bm3:M11-012', 'BM-III', 11, null, 'A passenger falls overboard from your open boat. What is your very first action?', '["Immediately turn the vessel hard to port","Go below to fetch the first-aid kit","Keep visual contact, point at the casualty, and throw the MOB buoy","Broadcast a MAYDAY before doing anything else"]'::jsonb, 2, 'Answer C. The first MOB actions are to keep visual contact and point at the casualty and release the MOB buoy towards them. SCV Code 2021 · Caribbean Netherlands Page 37 / 40'),
  ('bm3:M11-013', 'BM-III', 11, 'B1.2 / B1.3', 'Your engine has failed and will not restart while you drift towards a lee shore. Which response is most appropriate?', '["Keep cranking the starter continuously until the battery is flat","Anchor if the depth allows, show the correct shapes/lights and call for assistance on VHF","Abandon ship immediately into the water","Ignore it and wait for the engine to cool down"]'::jsonb, 1, 'Answer B. On loss of engines, anchor if depth allows, show the correct not-under-command shapes/lights and call for assistance on VHF while watching your drift.'),
  ('bm3:M11-014', 'BM-III', 11, 'B1.5', 'Your vessel is taking on water and in danger of sinking close inshore. You decide to beach her. Which shore should you choose?', '["A steep rocky shore with heavy surf","The nearest harbour wall, approached at full speed","An exposed reef where the vessel will be visible from far off","A gently shelving, sheltered, sandy or shingle shore clear of rocks and surf, approached slowly bow-on ✓"]'::jsonb, 0, 'Answer D. For beaching, choose a gently shelving, sheltered, sandy or shingle shore clear of rocks and surf, and approach slowly bow-on.')
on conflict (id) do update set
  course_code = excluded.course_code,
  module_seq  = excluded.module_seq,
  ref         = excluded.ref,
  stem        = excluded.stem,
  opts        = excluded.opts,
  correct     = excluded.correct,
  expl        = excluded.expl;

-- ---- Module-content (reader/deck-paden + gecureerde quizlijst) ----
-- Storage-paden in bucket 'course-content'. Volgnummer = modules.sequence.

update modules m set
  reader_path = 'bm3/readers/M01.pdf',
  deck_path   = 'bm3/decks/M01.pdf',
  quiz_ids    = '["bm3:M01-001","bm3:M01-002","bm3:M01-003","bm3:M01-004","bm3:M01-005","bm3:M01-006","bm3:M01-007","bm3:M01-008"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-III' and m.sequence = 1;
update modules m set
  reader_path = 'bm3/readers/M02.pdf',
  deck_path   = 'bm3/decks/M02.pdf',
  quiz_ids    = '["bm3:M02-001","bm3:M02-002","bm3:M02-003","bm3:M02-004","bm3:M02-005","bm3:M02-006","bm3:M02-007","bm3:M02-008","bm3:M02-009","bm3:M02-010","bm3:M02-011","bm3:M02-012","bm3:M02-013","bm3:M02-014","bm3:M02-015","bm3:M02-016","bm3:M02-017","bm3:M02-018","bm3:M02-019"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-III' and m.sequence = 2;
update modules m set
  reader_path = 'bm3/readers/M03.pdf',
  deck_path   = 'bm3/decks/M03.pdf',
  quiz_ids    = '["bm3:M03-001","bm3:M03-002","bm3:M03-003","bm3:M03-004","bm3:M03-005","bm3:M03-006","bm3:M03-007","bm3:M03-008","bm3:M03-009","bm3:M03-010","bm3:M03-011","bm3:M03-012","bm3:M03-013","bm3:M03-014","bm3:M03-015","bm3:M03-016","bm3:M03-017","bm3:M03-018"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-III' and m.sequence = 3;
update modules m set
  reader_path = 'bm3/readers/M04.pdf',
  deck_path   = 'bm3/decks/M04.pdf',
  quiz_ids    = '["bm3:M04-001","bm3:M04-002","bm3:M04-003","bm3:M04-004","bm3:M04-005","bm3:M04-006","bm3:M04-007","bm3:M04-008","bm3:M04-009","bm3:M04-010","bm3:M04-011","bm3:M04-012","bm3:M04-013","bm3:M04-014","bm3:M04-015","bm3:M04-016","bm3:M04-017","bm3:M04-018","bm3:M04-019","bm3:M04-020","bm3:M04-021","bm3:M04-022","bm3:M04-023","bm3:M04-024","bm3:M04-025","bm3:M04-026"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-III' and m.sequence = 4;
update modules m set
  reader_path = 'bm3/readers/M05.pdf',
  deck_path   = 'bm3/decks/M05.pdf',
  quiz_ids    = '["bm3:M05-001","bm3:M05-002","bm3:M05-003","bm3:M05-004","bm3:M05-005","bm3:M05-006","bm3:M05-007","bm3:M05-008","bm3:M05-009","bm3:M05-010","bm3:M05-011","bm3:M05-012","bm3:M05-013","bm3:M05-014"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-III' and m.sequence = 5;
update modules m set
  reader_path = 'bm3/readers/M06.pdf',
  deck_path   = 'bm3/decks/M06.pdf',
  quiz_ids    = '["bm3:M06-001","bm3:M06-002","bm3:M06-003","bm3:M06-004","bm3:M06-005","bm3:M06-006","bm3:M06-007","bm3:M06-008","bm3:M06-009","bm3:M06-010","bm3:M06-011","bm3:M06-012","bm3:M06-013","bm3:M06-014","bm3:M06-015"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-III' and m.sequence = 6;
update modules m set
  reader_path = 'bm3/readers/M07.pdf',
  deck_path   = 'bm3/decks/M07.pdf',
  quiz_ids    = '["bm3:M07-001","bm3:M07-002","bm3:M07-003","bm3:M07-004","bm3:M07-005","bm3:M07-006","bm3:M07-007","bm3:M07-008","bm3:M07-009","bm3:M07-010","bm3:M07-011","bm3:M07-012","bm3:M07-013","bm3:M07-014","bm3:M07-015","bm3:M07-016","bm3:M07-017","bm3:M07-018"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-III' and m.sequence = 7;
update modules m set
  reader_path = 'bm3/readers/M08.pdf',
  deck_path   = 'bm3/decks/M08.pdf',
  quiz_ids    = '["bm3:M08-001","bm3:M08-002","bm3:M08-003","bm3:M08-004","bm3:M08-005","bm3:M08-006","bm3:M08-007","bm3:M08-008","bm3:M08-009","bm3:M08-010","bm3:M08-011","bm3:M08-012","bm3:M08-013","bm3:M08-014","bm3:M08-015","bm3:M08-016","bm3:M08-017","bm3:M08-018","bm3:M08-019"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-III' and m.sequence = 8;
update modules m set
  reader_path = 'bm3/readers/M09.pdf',
  deck_path   = 'bm3/decks/M09.pdf',
  quiz_ids    = '["bm3:M09-001","bm3:M09-002","bm3:M09-003","bm3:M09-004","bm3:M09-005","bm3:M09-006","bm3:M09-007","bm3:M09-008","bm3:M09-009","bm3:M09-010","bm3:M09-011","bm3:M09-012","bm3:M09-013","bm3:M09-014"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-III' and m.sequence = 9;
update modules m set
  reader_path = 'bm3/readers/M10.pdf',
  deck_path   = 'bm3/decks/M10.pdf',
  quiz_ids    = '["bm3:M10-001","bm3:M10-002","bm3:M10-003","bm3:M10-004","bm3:M10-005","bm3:M10-006","bm3:M10-007","bm3:M10-008","bm3:M10-009","bm3:M10-010","bm3:M10-011","bm3:M10-012","bm3:M10-013","bm3:M10-014","bm3:M10-015","bm3:M10-016","bm3:M10-017","bm3:M10-018"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-III' and m.sequence = 10;
update modules m set
  reader_path = 'bm3/readers/M11.pdf',
  deck_path   = 'bm3/decks/M11.pdf',
  quiz_ids    = '["bm3:M11-001","bm3:M11-002","bm3:M11-003","bm3:M11-004","bm3:M11-005","bm3:M11-006","bm3:M11-007","bm3:M11-008","bm3:M11-009","bm3:M11-010","bm3:M11-011","bm3:M11-012","bm3:M11-013","bm3:M11-014"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-III' and m.sequence = 11;
update modules m set
  reader_path = 'bm3/readers/M12.pdf',
  deck_path   = 'bm3/decks/M12.pdf',
  quiz_ids    = '["bm3:M01-008","bm3:M06-002","bm3:M06-013","bm3:M10-003","bm3:M10-011","bm3:M10-013","bm3:M11-012"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-III' and m.sequence = 12;

-- Klaar.
