-- ============================================================
-- Plaza Boat College — Seed e-learning BM II
-- AUTOGEGENEREERD door scripts/gen-seed.mjs — niet handmatig bewerken.
-- Bron: data.js  ·  156 vragen
-- Idempotent: on conflict (id) do update. Voer uit NA migrations/0002_elearning.sql.
-- ============================================================

-- ---- Vragenbank (BM II) ----
insert into questions (id, course_code, module_seq, ref, stem, opts, correct, expl) values
  ('bm2:B3-001', 'BM-II', 2, 'B3.1', 'In the event of a death on board, the boatmaster must:', '["Tell only the owner","Bury the body at sea at once","Continue normally and report on return next month","Preserve the scene as far as possible, notify the authorities/Coast Guard, and make a full record in the log"]'::jsonb, 3, 'Answer D. A death must be reported to the authorities without delay, the scene preserved where possible, and full entries made in the deck log.'),
  ('bm2:B3-002', 'BM-II', 2, 'B3.1', 'After a serious injury to a passenger, beyond immediate first aid the boatmaster must:', '["Say nothing to avoid liability","Wait until the next inspection","Record the facts, report the casualty to the relevant authority, and cooperate with any investigation","Delete the log entry"]'::jsonb, 2, 'Answer C. Injuries to seafarers/passengers must be recorded and reported to the competent authority; honest records support investigation and safety improvement.'),
  ('bm2:B3-003', 'BM-II', 2, 'B3.2', 'Which document certifies that a Small Commercial Vessel meets the SCV Code construction and equipment standards?', '["The VHF licence","The deck log","The crew list","The SCV Safety Certificate"]'::jsonb, 3, 'Answer D. The SCV Safety Certificate (Reg. I/15) shows the vessel complies with the Code''s construction, stability and equipment requirements.'),
  ('bm2:B3-004', 'BM-II', 2, 'B3.3', 'A Grade 2 boatmaster''s operational limits are primarily set by:', '["The owner''s instructions alone","The grade and area restrictions on the licence and the vessel''s certificate (waters, size, passenger numbers)","Personal preference","The weather only"]'::jsonb, 1, 'Answer B. Operation is bounded by the licence grade/area endorsements (Table X/5.2) and the vessel''s certificate limits — waters, size and passenger numbers.'),
  ('bm2:B3-005', 'BM-II', 2, 'X/5.2', 'Under Table X/5.2, a Grade 2 licence is the minimum grade for which of these?', '["A 12–24 m passenger vessel in coastal waters","A vessel under 24 m in protected waters and under 24 m (non-passenger) in coastal waters","All vessels in exposed waters","An open boat in protected waters by day"]'::jsonb, 1, 'Answer B. Grade 2 is minimum for <24 m in protected waters, <12 m passenger and <24 m non-passenger in coastal waters; 12–24 m passenger/coastal and exposed need Grade 1.'),
  ('bm2:B3-006', 'BM-II', 2, 'X/6.2', 'Which of the following is NOT one of the requirements to obtain a Boatmaster Licence Grade 2?', '["Have at least 4 months approved seagoing service","Have completed approved practical instruction","Be 20 years of age or over","Hold a valid medical certificate"]'::jsonb, 0, 'Answer A. Grade 2 requires 2 months approved seagoing service (X/6.2.4); 4 months is the Grade 1 requirement.'),
  ('bm2:B3-007', 'BM-II', 2, 'X/13', 'A Boatmaster Licence (holder under 63) is subject to re-validation:', '["Every year","Every five years","Only once for life","Every three years, with proof of at least 45 days'' service and a valid medical"]'::jsonb, 3, 'Answer D. X/13.1: re-validation every three years for under-63s, needing at least 45 days'' service in the period and a current medical certificate.'),
  ('bm2:B3-008', 'BM-II', 2, 'X/8.1', 'The Grade 2 boatmaster examination under SCV Code X/8.1 consists of:', '["A written paper only","A practical test only","An oral examination plus a practical test on a vessel of the size for which the licence is needed","Three separate written papers"]'::jsonb, 2, 'Answer C. X/8.1: the Grade 2 exam is in two parts — an oral examination and a practical handling test on a vessel of the appropriate size.'),
  ('bm2:B3-009', 'BM-II', 2, 'X/8.3', 'A candidate who passes only one part of the Grade 2 examination may:', '["Only re-sit both parts together","Keep it for life","Never re-sit","Retain that pass for one year when re-sitting the other part, subject to holding a valid medical certificate"]'::jsonb, 3, 'Answer D. X/8.3: a pass in one part is retained for one year on re-sitting the other part, subject to a valid medical fitness certificate.'),
  ('bm2:B9-001', 'BM-II', 2, 'B9.1', 'Providing ''safe access'' to the vessel means ensuring that:', '["The boat is locked","Passengers and crew can get on and off safely — secure gangway/steps, adequate lighting, and assistance where needed","Boarding is done at speed","Only crew may board"]'::jsonb, 1, 'Answer B. Safe access requires a secure, well-lit means of boarding/landing and appropriate assistance, so no one is injured embarking or disembarking.'),
  ('bm2:B9-002', 'BM-II', 2, 'B9.2', '''Safe working practices'' on board include:', '["Working alone in all tasks","Briefing crew, using appropriate PPE, keeping decks clear, and managing tasks like mooring and anchoring safely","Ignoring risk to save time","Removing all guards"]'::jsonb, 1, 'Answer B. Safe working means risk awareness, PPE, clear decks, and safe handling of lines, anchors and machinery to protect crew and passengers.'),
  ('bm2:B9-003', 'BM-II', 2, 'I/15', 'The SCV Safety Certificate (Reg. I/15) must be:', '["Renewed only after an accident","Displayed to passengers as a ticket","Kept ashore by the owner","Valid, carried on board and available for inspection, and its conditions/limits complied with"]'::jsonb, 3, 'Answer D. The Safety Certificate must be in force, carried on board, available for inspection, and the vessel operated within its conditions and limits.'),
  ('bm2:B9-004', 'BM-II', 2, 'B9.4', 'A basic security measure for a small commercial passenger vessel is to:', '["Control access, be alert to suspicious behaviour or unattended items, and account for persons on board","Ignore unknown packages","Leave the vessel open and unattended","Carry weapons"]'::jsonb, 0, 'Answer A. Basic security means access control, vigilance for suspicious persons/items, and accounting for everyone on board.'),
  ('bm2:B9-005', 'BM-II', 2, 'B9.2', 'Who carries the ultimate responsibility for the safety of the vessel, crew and passengers?', '["The boatmaster (person in charge) on board","The owner ashore","The most senior passenger","The Coast Guard"]'::jsonb, 0, 'Answer A. The boatmaster has ultimate responsibility on board for the safety of the vessel and all persons aboard.'),
  ('bm2:B9-006', 'BM-II', 2, 'B9.3', 'If a Safety Certificate condition is breached (e.g. equipment missing or out of date), the boatmaster should:', '["Not operate outside the certificate''s terms — rectify the deficiency before carrying passengers","Sail anyway and fix it later","Ask passengers to sign a waiver","Carry fewer passengers and ignore it"]'::jsonb, 0, 'Answer A. The vessel must be operated within the Safety Certificate; a breach must be rectified before operating, not waived away.'),
  ('bm2:B10-001', 'BM-II', 3, 'B10.1', 'A boatmaster planning a coastal passage should obtain a forecast from:', '["Last week''s newspaper","Personal optimism","Word of mouth only","Official meteorological services via radio, internet or marine forecasts, and check it before departure"]'::jsonb, 3, 'Answer D. Use official met-service forecasts (radio/internet/marine broadcasts) and check the latest before sailing and again under way.'),
  ('bm2:B10-002', 'BM-II', 3, 'B10.3', 'A rapidly falling barometer usually warns of:', '["Fog only","No change","Settled fine weather","Approaching strong winds and deteriorating weather"]'::jsonb, 3, 'Answer D. A rapid fall in barometric pressure indicates an approaching depression/front and strengthening winds — take precautions.'),
  ('bm2:B10-003', 'BM-II', 3, 'B10.3', 'High, wispy cirrus cloud thickening and lowering to a milky sky with a halo around the sun often indicates:', '["A passing shower only","Improving weather","Imminent calm","An approaching warm front and worsening weather within a day or so"]'::jsonb, 3, 'Answer D. Thickening, lowering high cloud and a halo are classic signs of an approaching warm front and deteriorating weather.'),
  ('bm2:B10-004', 'BM-II', 3, 'B10.2', 'In the Caribbean trade-wind belt, local ''acceleration zones'' off the ends of high islands mean a boatmaster should expect:', '["Calm in the lee always","Lighter wind near headlands","No local effect","Locally stronger wind and steeper seas where the trades funnel around or off the island"]'::jsonb, 3, 'Answer D. Wind funnels and accelerates around high islands, producing stronger gusts and steeper seas in the acceleration zones — a key Caribbean local effect.'),
  ('bm2:B10-005', 'BM-II', 3, 'B10.2', 'The greatest seasonal weather hazard for small craft in the Caribbean Netherlands is:', '["Snow","Pack ice","Permanent fog","The tropical storm/hurricane season (broadly June–November)"]'::jsonb, 3, 'Answer D. The Atlantic hurricane season (about June–November) is the major seasonal hazard; monitor warnings and avoid being caught out.'),
  ('bm2:B10-006', 'BM-II', 3, 'B10.3', 'Sudden gusty squalls with a dark line of cloud and a wind-shift approaching are best handled by:', '["Reducing speed, securing the vessel and passengers, and being ready for the wind increase and shift","Increasing speed to outrun them","Heading straight into the steepest seas at full power","Ignoring them"]'::jsonb, 0, 'Answer A. Approaching squalls call for reduced speed, securing the boat/people and readiness for the gust and wind-shift; don''t try to outrun them.'),
  ('bm2:B14-001', 'BM-II', 3, 'B14.1', 'Radar is principally used by a small-craft boatmaster to:', '["Receive weather faxes","Detect other vessels, landmasses and (some) hazards and measure their range and bearing, especially in poor visibility","Steer the autopilot","Measure water temperature"]'::jsonb, 1, 'Answer B. Radar detects targets and measures range/bearing — invaluable for collision avoidance and position-fixing in poor visibility.'),
  ('bm2:B14-002', 'BM-II', 3, 'B14.1', 'A key limitation of radar the boatmaster must remember is that it:', '["Replaces a lookout","Works perfectly in all conditions","Shows colours of vessels","May not detect small craft, low objects or those with poor radar reflection, and needs correct interpretation"]'::jsonb, 3, 'Answer D. Radar can miss small/low/poor-reflecting targets and clutter can hide them; it supplements but never replaces a visual/aural lookout.'),
  ('bm2:B14-003', 'BM-II', 3, 'B14.1', 'AIS (Automatic Identification System) provides the boatmaster with:', '["Identity, position, course, speed and other data broadcast by AIS-fitted vessels","The depth of water","A radar picture of non-AIS targets","A weather forecast"]'::jsonb, 0, 'Answer A. AIS exchanges identity, position, course and speed of equipped vessels — but not all craft carry it, so it is not a complete picture.'),
  ('bm2:B14-004', 'BM-II', 3, 'B14.1', 'An echo sounder measures the:', '["Distance to the nearest vessel","Depth of water below the transducer","Speed over ground","Wind speed"]'::jsonb, 1, 'Answer B. An echo sounder measures water depth beneath the transducer; the operator must know whether it reads from the keel, waterline or transducer.'),
  ('bm2:B14-005', 'BM-II', 3, 'B14.1', 'Satellite navigation (GPS/GNSS) gives the boatmaster a continuous:', '["Radar picture","Position (latitude/longitude), and derived course and speed over the ground","Engine temperature","Depth reading"]'::jsonb, 1, 'Answer B. GNSS provides continuous position and, from successive fixes, course and speed over the ground; cross-check against other means.'),
  ('bm2:B14-006', 'BM-II', 3, 'B14.1', 'A prudent boatmaster treats electronic aids by:', '["Switching off the lookout","Ignoring them in clear weather","Cross-checking electronic position/data against visual observation, the chart and the echo sounder","Trusting the GPS plotter absolutely"]'::jsonb, 2, 'Answer C. Electronic aids can fail or mislead; always cross-check against eyes, chart, soundings and other instruments, and keep a lookout.'),
  ('bm2:B5-001', 'BM-II', 3, 'B5.1', 'On a chart, a number such as ''12'' printed in open water normally indicates the:', '["Tidal range","Magnetic variation","Distance to shore","Charted depth (soundings) reduced to chart datum"]'::jsonb, 3, 'Answer D. Soundings are charted depths reduced to chart datum (normally LAT); the figure shows the depth in the chart''s stated units.'),
  ('bm2:B5-002', 'BM-II', 3, 'B5.1', 'An asterisk or small symbol with the abbreviation ''Wk'' on a chart marks a:', '["Working area","Anchorage","Weather station","Wreck"]'::jsonb, 3, 'Answer D. ''Wk'' marks a wreck; the symbol style and any depth figure show whether it is dangerous and how it is marked.'),
  ('bm2:B5-003', 'BM-II', 3, 'B5.1', 'Chart datum, to which charted depths are reduced, is normally chosen as:', '["Mean sea level","High water springs","The deck level of the survey ship","A low-water level (e.g. Lowest Astronomical Tide) so the real depth is rarely less than charted"]'::jsonb, 3, 'Answer D. Charts use a low-water datum (commonly LAT) so the actual depth is almost always at least the charted sounding — a safety margin.'),
  ('bm2:B5-004', 'BM-II', 3, 'B5.1', 'On a chart the abbreviation ''S'' against the seabed nature means:', '["Shell","Stone","Shoal","Sand"]'::jsonb, 3, 'Answer D. Seabed quality abbreviations: S = sand, M = mud, Co = coral, R = rock — important for choosing holding ground.'),
  ('bm2:B5-005', 'BM-II', 3, 'B5.2', 'A Tidal Diamond on a chart (a magenta diamond with a letter) gives the:', '["Position of a buoy","Magnetic variation","Charted depth","Tidal stream set (direction) and rate (speed) at that position for each hour relative to HW"]'::jsonb, 3, 'Answer D. Tidal diamonds key to a table giving the tidal-stream direction and rate for each hour before/after high water at a reference port.'),
  ('bm2:B5-006', 'BM-II', 3, 'B5.2', 'To use a tidal diamond you must know the:', '["State of tide (time relative to HW at the reference port) and whether it is springs or neaps","Compass deviation only","Engine RPM","Vessel''s fuel state"]'::jsonb, 0, 'Answer A. The diamond table is entered with the hour relative to HW and adjusted for springs/neaps to read the stream''s set and rate.'),
  ('bm2:B5-007', 'BM-II', 3, 'B5.1', 'On a chart, the abbreviation ''Fl'' beside a light symbol means the light is:', '["Fixed (steady)","Flashing","Faint","Floodlit"]'::jsonb, 1, 'Answer B. ''Fl'' denotes a flashing light (the light period shorter than the dark); ''F'' would be a fixed (steady) light.'),
  ('bm2:B5-008', 'BM-II', 3, 'B5.2', 'If a tidal-stream rate from a tidal diamond is given for springs and neaps, the rate on a day between springs and neaps is found by:', '["Using the spring rate always","Using the neap rate always","Interpolating between the spring and neap rates","Doubling the neap rate"]'::jsonb, 2, 'Answer C. The actual rate is interpolated between the tabulated spring and neap figures according to where the day falls in the cycle.'),
  ('bm2:B2-001', 'BM-II', 4, 'Rule 5', 'COLREG Rule 5 requires every vessel to:', '["Use radar at all times","Post a lookout only in fog","Keep a lookout only at night","Keep a proper lookout by sight and hearing and by all available means"]'::jsonb, 3, 'Answer D. Rule 5: a proper lookout shall be maintained at all times by sight and hearing and by all available appropriate means.'),
  ('bm2:B2-002', 'BM-II', 4, 'Rule 6', 'Under Rule 6, ''safe speed'' is a speed at which a vessel can:', '["Maintain schedule","Take proper and effective action to avoid collision and stop within a distance appropriate to the circumstances","Plane fully","Reach maximum economy"]'::jsonb, 1, 'Answer B. Safe speed allows proper avoiding action and stopping within an appropriate distance, judged from visibility, traffic, manoeuvrability etc.'),
  ('bm2:B2-003', 'BM-II', 4, 'Rule 7', 'Rule 7 states that risk of collision shall be deemed to exist if:', '["The other vessel is large","You are the stand-on vessel","The compass bearing of an approaching vessel does not appreciably change","The vessels are more than 3 miles apart"]'::jsonb, 2, 'Answer C. If the compass bearing of an approaching vessel does not appreciably change, risk of collision shall be deemed to exist.'),
  ('bm2:B2-004', 'BM-II', 4, 'Rule 8', 'Action to avoid collision under Rule 8 should be:', '["Left to the last moment","Positive, made in ample time, large enough to be readily apparent to another vessel","A series of tiny course changes","Small and gradual so as not to alarm"]'::jsonb, 1, 'Answer B. Avoiding action must be positive, made in ample time and large enough to be readily apparent visually or by radar.'),
  ('bm2:B2-005', 'BM-II', 4, 'Rule 9', 'In a narrow channel, a vessel shall keep:', '["As near to the outer limit on her starboard side as is safe and practicable","Wherever the deepest water is","To the centre","To the port side"]'::jsonb, 0, 'Answer A. Rule 9: keep as near to the outer limit of the channel on your starboard side as is safe and practicable.'),
  ('bm2:B2-006', 'BM-II', 4, 'Rule 9', 'A vessel of less than 20 m in length or a sailing vessel in a narrow channel shall:', '["Anchor in the fairway","Always sound five blasts","Not impede the passage of a vessel that can safely navigate only within the channel","Have right of way over a power-driven vessel"]'::jsonb, 2, 'Answer C. Rule 9(b): a vessel under 20 m or a sailing vessel shall not impede a vessel which can safely navigate only within the channel.'),
  ('bm2:B2-007', 'BM-II', 4, 'Rule 10', 'When crossing a traffic separation scheme that cannot be avoided, a vessel shall cross:', '["On a heading as nearly as practicable at right angles to the general direction of traffic flow","Against the flow to save time","Diagonally with the flow","Along the separation zone"]'::jsonb, 0, 'Answer A. Rule 10: cross a TSS on a heading as nearly as practicable at right angles to the general traffic direction.'),
  ('bm2:B2-008', 'BM-II', 4, 'Rule 12', 'Two sailing vessels approaching with the wind on different sides: which keeps clear?', '["The vessel with the wind on the port side keeps out of the way","The smaller vessel","The faster vessel","The one with wind on the starboard side"]'::jsonb, 0, 'Answer A. Rule 12: when each has the wind on a different side, the vessel with the wind on the port side keeps out of the way.'),
  ('bm2:B2-009', 'BM-II', 4, 'Rule 13', 'An overtaking vessel (Rule 13) is one coming up on another from more than how many degrees abaft the beam?', '["90 degrees","22.5 degrees","45 degrees","10 degrees"]'::jsonb, 1, 'Answer B. An overtaking vessel approaches from more than 22.5 degrees abaft the beam (where at night it would see only the sternlight).'),
  ('bm2:B2-010', 'BM-II', 4, 'Rule 13', 'The duty of an overtaking vessel is to:', '["Sound one prolonged blast","Maintain course and speed","Keep out of the way of the vessel being overtaken until finally past and clear","Pass close down the other''s port side"]'::jsonb, 2, 'Answer C. The overtaking vessel must keep clear of the overtaken vessel until past and clear; this duty is not cancelled by any later change of bearing.'),
  ('bm2:B2-011', 'BM-II', 4, 'Rule 14', 'Two power-driven vessels meeting head-on should each:', '["Stop engines","Alter course to starboard so each passes on the port side of the other","Hold course and speed","Alter course to port"]'::jsonb, 1, 'Answer B. Rule 14: in a head-on meeting each power-driven vessel alters course to starboard to pass port-to-port.'),
  ('bm2:B2-012', 'BM-II', 4, 'Rule 15', 'In a crossing situation between two power-driven vessels, the vessel which has the other on her own starboard side shall:', '["Stand on","Keep out of the way and avoid crossing ahead of the other","Alter to port across the bow","Increase speed"]'::jsonb, 1, 'Answer B. Rule 15: the vessel that has the other on its starboard side gives way and shall, if possible, avoid crossing ahead of the other.'),
  ('bm2:B2-013', 'BM-II', 4, 'Rule 16', 'The give-way vessel (Rule 16) shall:', '["Wait for the stand-on vessel to act","Sound the danger signal","Take early and substantial action to keep well clear","Maintain course and speed"]'::jsonb, 2, 'Answer C. Rule 16: the give-way vessel must take early and substantial action to keep well clear.'),
  ('bm2:B2-014', 'BM-II', 4, 'Rule 17', 'Under Rule 17 the stand-on vessel shall initially:', '["Cross ahead of the give-way vessel","Alter to port immediately","Keep her course and speed","Stop her engines"]'::jsonb, 2, 'Answer C. The stand-on vessel keeps course and speed initially, but may and must act if the give-way vessel is not taking appropriate action.'),
  ('bm2:B2-015', 'BM-II', 4, 'Rule 18', 'In the general pecking order of Rule 18, a power-driven vessel under way shall keep out of the way of all of the following EXCEPT:', '["Another ordinary power-driven vessel under way","A vessel not under command","A vessel restricted in her ability to manoeuvre","A vessel engaged in fishing"]'::jsonb, 0, 'Answer A. A power-driven vessel gives way to NUC, RAM, fishing and (so far as practicable) sailing vessels; it has no such duty to another ordinary power-driven vessel except under the steering rules.'),
  ('bm2:B2-016', 'BM-II', 4, 'Rule 19', 'In restricted visibility, a vessel hearing apparently forward of the beam the fog signal of another vessel shall, so far as the situation admits:', '["Maintain full speed","Sound five short blasts","Alter boldly to port","Reduce to minimum speed at which she can be kept on course, or take all way off if necessary"]'::jsonb, 3, 'Answer D. Rule 19(e): reduce speed to the minimum at which she can be kept on her course; take all way off if necessary, and navigate with caution.'),
  ('bm2:B2-017', 'BM-II', 4, 'Rule 19', 'Rule 19 (restricted visibility) applies to vessels:', '["Only at anchor","Not in sight of one another, navigating in or near an area of restricted visibility","Only when overtaking","In sight of one another"]'::jsonb, 1, 'Answer B. Rule 19 governs conduct of vessels not in sight of one another in or near restricted visibility; the steering/sailing rules of Section II do not apply.'),
  ('bm2:B2-018', 'BM-II', 4, 'Rule 19', 'A vessel which detects by radar alone another vessel and assesses a close-quarters situation is developing shall avoid, if the alteration of course is to be made:', '["An alteration of course towards a vessel abeam or abaft the beam","Sounding any signal","Any reduction of speed","An alteration of course to starboard for a vessel forward of the beam (other than for one being overtaken) — and avoid turning toward a vessel abeam/abaft"]'::jsonb, 3, 'Answer D. Rule 19(d): avoid an alteration to port for a vessel forward of the beam (other than one being overtaken) and avoid altering toward a vessel abeam or abaft the beam.'),
  ('bm2:B2-019', 'BM-II', 4, 'Rule 35', 'In or near restricted visibility, a power-driven vessel making way through the water shall sound:', '["One prolonged blast at intervals of not more than 2 minutes","Five short blasts continuously","One short blast every minute","Two prolonged blasts every minute"]'::jsonb, 0, 'Answer A. Rule 35: a power-driven vessel making way sounds one prolonged blast at intervals of not more than 2 minutes.'),
  ('bm2:B2-020', 'BM-II', 4, 'Rule 34', 'In sight of one another, a power-driven vessel altering course to starboard sounds:', '["One short blast","One prolonged blast","Two short blasts","Three short blasts"]'::jsonb, 0, 'Answer A. Rule 34: one short blast = ''I am altering my course to starboard''; two = to port; three = operating astern propulsion.'),
  ('bm2:B2-021', 'BM-II', 4, 'Rule 34', 'Five or more short and rapid blasts is the signal meaning:', '["I doubt whether you are taking sufficient action to avoid collision (the danger/wake-up signal)","I am at anchor","I am altering to port","I am overtaking on your starboard side"]'::jsonb, 0, 'Answer A. At least five short rapid blasts is the danger signal, indicating doubt that the other vessel is taking sufficient avoiding action.'),
  ('bm2:B2-022', 'BM-II', 4, 'Rule 23', 'A power-driven vessel under way of less than 50 m in length must exhibit at night:', '["Sidelights only","An all-round red light","A masthead light, sidelights and a sternlight (a second masthead light optional under 50 m)","Two masthead lights, sidelights and a sternlight"]'::jsonb, 2, 'Answer C. A power-driven vessel under 50 m shows one masthead light forward, sidelights and a sternlight; a second masthead is optional under 50 m.'),
  ('bm2:B2-023', 'BM-II', 4, 'Rule 24', 'A vessel towing astern where the length of tow exceeds 200 m shows, in addition to other lights:', '["Nothing extra","A single red all-round light","Three masthead lights in a vertical line forward and a diamond shape by day","A black ball"]'::jsonb, 2, 'Answer C. When the tow exceeds 200 m the towing vessel shows three masthead lights in a vertical line and, by day, a diamond shape.'),
  ('bm2:B2-024', 'BM-II', 4, 'Rule 25', 'A sailing vessel under way (and not motoring) at night exhibits:', '["An all-round white light only","A masthead light and sidelights","Two red lights in a line","Sidelights and a sternlight"]'::jsonb, 3, 'Answer D. A sailing vessel shows sidelights and a sternlight; if she is also being propelled by machinery she must show a masthead light and is treated as power-driven.'),
  ('bm2:B2-025', 'BM-II', 4, 'Rule 30', 'A vessel at anchor of less than 50 m exhibits at night:', '["An all-round white light where it can best be seen","A red over green","A masthead light and sidelights","Two all-round red lights"]'::jsonb, 0, 'Answer A. A vessel under 50 m at anchor shows one all-round white light where best seen (and by day one black ball forward).'),
  ('bm2:B2-026', 'BM-II', 4, 'Rule 27', 'A vessel not under command (NUC) exhibits at night:', '["Two all-round red lights in a vertical line","Two all-round green lights","Red over white","Three all-round red lights vertically"]'::jsonb, 0, 'Answer A. A NUC vessel shows two all-round red lights in a vertical line, and when making way also sidelights and a sternlight.'),
  ('bm2:B2-027', 'BM-II', 4, 'Rule 26', 'A vessel engaged in fishing (other than trawling) by night exhibits:', '["Two red lights","Green over white all-round","Two green lights","Red over white all-round lights in a vertical line"]'::jsonb, 3, 'Answer D. A vessel fishing (not trawling) shows an all-round red over an all-round white light; a trawler shows green over white.'),
  ('bm2:B2-028', 'BM-II', 4, 'Rule 32', 'Under the COLREG sound-signal definitions, a ''prolonged blast'' lasts:', '["From four to six seconds","About 1 second","Ten seconds","Exactly 2 seconds"]'::jsonb, 0, 'Answer A. A prolonged blast is of four to six seconds'' duration; a short blast is about one second.'),
  ('bm2:B2-029', 'BM-II', 4, 'Rule 3', 'Under Rule 3, a vessel ''restricted in her ability to manoeuvre'' is one which:', '["Is at anchor","Has a deep draught","From the nature of her work is restricted in her ability to keep out of the way of another vessel","Is simply slow"]'::jsonb, 2, 'Answer C. A RAM vessel is restricted by the nature of her work (e.g. laying cable, dredging) from manoeuvring as required by the Rules.'),
  ('bm2:B2-030', 'BM-II', 4, 'B2.3', 'Keeping a ''good lookout'' in busy daylight pilotage water specifically requires the boatmaster to:', '["Post a lookout only when overtaking","Watch the chart plotter only","Use sight and hearing, scan all round including astern, and not be distracted by other duties","Rely on AIS targets only"]'::jsonb, 2, 'Answer C. A good lookout is continuous, all-round, by eye and ear, undistracted — radar/AIS supplement but never replace it.'),
  ('bm2:B2-031', 'BM-II', 4, 'B2.4', 'The principal purpose of keeping a Deck Log on a Grade 2 vessel is to:', '["Record the crew''s wages","Provide a chronological, factual record of the voyage, navigation, weather, incidents and key decisions","List the passengers'' meals","Replace the SMS"]'::jsonb, 1, 'Answer B. The deck log is the official, contemporaneous record of the voyage — navigation, weather, position, incidents — and is vital evidence after any incident.'),
  ('bm2:B2-032', 'BM-II', 4, 'B2.4', 'Which of the following should normally be entered in the deck log?', '["Nothing unless there is an incident","Only departure and arrival","Just the fuel cost","Times of departure/arrival, courses and speeds, weather, significant events, defects and any emergencies"]'::jsonb, 3, 'Answer D. The deck log records times, courses/speeds, weather, significant events, defects and emergencies — a complete narrative of the watch.'),
  ('bm2:B2-033', 'BM-II', 4, 'B2.2', 'Why does Grade 2 (unlike Grade 3) require a FULL knowledge of the Collision Regulations?', '["Only the practical test matters","A Grade 2 may operate larger/decked vessels and in coastal waters where the full range of situations, lights and signals must be applied","The rules differ at Grade 2","Grade 2 boatmasters never use them"]'::jsonb, 1, 'Answer B. Grade 2 covers larger vessels and coastal operation, so the full COLREG — all lights, shapes, signals and conduct rules — must be mastered, not just a practical working knowledge.'),
  ('bm2:B2-034', 'BM-II', 4, 'Rule 2', 'Rule 2 (Responsibility) means that compliance with the Rules:', '["Does not exonerate a vessel from the consequences of neglect, and a departure from the Rules may be necessary to avoid immediate danger","Applies only by day","Excuses any consequences","Is optional for small craft"]'::jsonb, 0, 'Answer A. Rule 2: nothing exonerates neglect of ordinary good seamanship, and a departure from the Rules is permitted where necessary to avoid immediate danger.'),
  ('bm2:B4-001', 'BM-II', 5, 'B4.1', 'On a vessel the term ''freeboard'' means the:', '["Distance from the keel to the waterline","Length of the anchor cable","Vertical distance from the waterline to the main deck edge","Width of the deck"]'::jsonb, 2, 'Answer C. Freeboard is the height of the deck (or deck edge) above the waterline — the reserve buoyancy above the sea.'),
  ('bm2:B4-002', 'BM-II', 5, 'B4.1', 'The ''scope'' of an anchor cable is:', '["The chain''s diameter","The ratio of the length of cable veered to the depth of water","The breaking strain","The weight of the anchor"]'::jsonb, 1, 'Answer B. Scope is the ratio of cable length paid out to water depth; adequate scope (e.g. 4:1 chain or more) keeps the pull horizontal so the anchor holds.'),
  ('bm2:B4-003', 'BM-II', 5, 'B4.2', '''Interaction'' between two vessels passing close at speed tends to:', '["Only slow them down","Push them apart strongly","Have no effect","Cause the vessels to be drawn together (and the smaller vessel to sheer), especially in shallow or narrow water"]'::jsonb, 3, 'Answer D. Pressure fields cause close-passing vessels to attract each other and the smaller craft to sheer; risk rises in shallow or confined water.'),
  ('bm2:B4-004', 'BM-II', 5, 'B4.3', 'When berthing with a strong onshore (setting you onto the berth) wind, you should:', '["Ignore the wind entirely","Approach fast and let the wind stop you","Approach at a shallow angle, control the rate of closing, and use lines/fenders early because the wind will set you on","Approach beam-on at speed"]'::jsonb, 2, 'Answer C. An onshore wind sets you onto the berth, so close slowly at a shallow angle and get lines on early; never let the wind slam you alongside.'),
  ('bm2:B4-005', 'BM-II', 5, 'B4.4', 'After weighing anchor, the anchor and cable should be:', '["Left hanging over the bow under way","Towed astern","Properly secured and stowed, with the cable stopper/devil''s claw on, to prevent it running out or causing damage","Coiled on deck loose"]'::jsonb, 2, 'Answer C. Anchors and cable must be securely stowed and the stopper applied so they cannot run out accidentally or shift at sea.'),
  ('bm2:B4-006', 'BM-II', 5, 'B4.5', 'Selecting a good anchorage depends mainly on:', '["Being as close to other boats as possible","Proximity to a restaurant","The deepest possible water","Good holding ground, adequate shelter from wind/sea, sufficient and suitable depth, swinging room, and clear of cables/fairways"]'::jsonb, 3, 'Answer D. A proper anchorage needs good holding ground, shelter, suitable depth, swinging room and clearance of hazards, cables and fairways.'),
  ('bm2:B4-007', 'BM-II', 5, 'B4.6', 'Navigating at reduced speed past moored boats and shorelines is important chiefly because:', '["It saves fuel only","It looks professional","Your bow and stern wave (wash) can cause damage and injury, for which you are responsible","It is faster overall"]'::jsonb, 2, 'Answer C. Excessive wash from your bow/stern wave can damage moored craft and the shore and injure people; the boatmaster is responsible for it.'),
  ('bm2:B4-008', 'BM-II', 5, 'B4.7', 'Compared with a single-screw boat, a twin-screw boat is generally:', '["More manoeuvrable at low speed because differential thrust gives a strong turning couple","Unable to turn in its own length","Less affected by transverse thrust on every prop","Harder to manoeuvre at low speed"]'::jsonb, 0, 'Answer A. Twin screws give excellent low-speed control: opposing thrust turns the boat in its own length and keeps steerage with little headway.'),
  ('bm2:B4-009', 'BM-II', 5, 'B4.8', 'Two basic hazards associated with towing another vessel are:', '["Saving fuel and time","Improved stability and speed","No hazards if the rope is strong","The tow yawing/girting the towing vessel, and the tow-line parting under shock loading (snap-back danger)"]'::jsonb, 3, 'Answer D. Towing risks include girting/capsize from a sheering tow, and a parting line snapping back lethally; rig a quick-release and keep clear of the bight.'),
  ('bm2:B4-010', 'BM-II', 5, 'B4.1', 'A ''bight'' of a rope or towline is:', '["A loop or curved part of the rope between its ends","The end of the rope","A type of knot","The cleat"]'::jsonb, 0, 'Answer A. A bight is a loop or curve in a rope between the ends; standing in a bight under load is dangerous if it comes taut.'),
  ('bm2:A-001', 'BM-II', 6, 'A1.7', 'Transverse thrust (paddle-wheel effect) on a single right-handed fixed propeller is most noticeable when the engine is:', '["Idling ahead in deep water","Running ahead at cruising speed","Stopped with the rudder amidships","First put astern from rest, before the boat gathers sternway"]'::jsonb, 3, 'Answer D. Transverse thrust is most pronounced going astern from rest, before water flow over the rudder builds; a right-handed prop walks the stern to port.'),
  ('bm2:A-002', 'BM-II', 6, 'A1.7', 'A right-handed (clockwise when viewed from astern) single screw is put astern from rest. The stern will tend to walk to:', '["Whichever way the wind blows only","Port","Starboard","Stay dead straight"]'::jsonb, 1, 'Answer B. A right-handed propeller going astern walks the stern to port (and the bow swings to starboard).'),
  ('bm2:A-003', 'BM-II', 6, 'A1.5', 'When manoeuvring a single-screw vessel in confined water, the most effective way to turn it short round in its own length is to:', '["Use alternating bursts of ahead (with rudder hard over) and astern, exploiting prop wash and transverse thrust","Use full ahead with hard-over rudder only","Drift and let wind do the turning","Tow the bow round with the dinghy"]'::jsonb, 0, 'Answer A. Turning short round uses short bursts ahead against hard-over rudder to kick the stern, alternated with astern, using prop wash and transverse thrust.'),
  ('bm2:A-004', 'BM-II', 6, 'A1.1', 'When coming alongside a berth, the safest general approach is to:', '["Approach beam-on and let the fenders absorb the contact","Approach fast so the boat answers the helm and stop with a burst astern at the last moment","Approach downwind and downtide for an easy stop","Approach slowly, at an angle, stemming any wind or tide so you keep steerage at low speed"]'::jsonb, 3, 'Answer D. Approach slowly against the stronger of wind or tide so the boat is held back and steerage is retained; never approach faster than you are willing to hit.'),
  ('bm2:A-005', 'BM-II', 6, 'A1.2', 'When weighing (recovering) the anchor, the helmsman should:', '["Drive ahead hard to break out the anchor while the crew heaves","Motor gently up towards the anchor as the cable is recovered so the crew never has to take the boat''s weight","Go full astern to drag it out","Leave the engine in neutral throughout"]'::jsonb, 1, 'Answer B. The boat is motored gently up to the anchor to reduce strain; the windlass/crew should never take the full weight of the boat.'),
  ('bm2:A-006', 'BM-II', 6, 'A1.3', 'When coming alongside another vessel that is under way and making way, you should match her:', '["Opposite course, bow to bow","Course and speed, approaching from astern on the lee side","Course but at twice her speed","Speed only, ignoring her heading"]'::jsonb, 1, 'Answer B. Come alongside a moving vessel by matching course and speed and closing gently, normally on the lee (sheltered) side.'),
  ('bm2:A-007', 'BM-II', 6, 'A1.4', 'To make fast to a mooring buoy single-handed in a tideway, you should approach:', '["Beam-on at speed","Downtide so you arrive quickly","Heading into the tide (or the stronger of wind/tide) so the buoy stops you","From directly downwind only, ignoring tide"]'::jsonb, 2, 'Answer C. Approach a buoy stemming the tide (or stronger of wind/tide); it acts as a brake and lets you stop alongside the buoy with control.'),
  ('bm2:A-008', 'BM-II', 6, 'A1.6', 'Twin-screw vessels can turn in their own length most readily by:', '["Putting both engines ahead","Putting one engine ahead and the other astern","Using rudder only with both ahead","Putting both engines astern"]'::jsonb, 1, 'Answer B. Going ahead on one engine and astern on the other produces a strong turning couple, letting a twin-screw turn in its own length.'),
  ('bm2:A-009', 'BM-II', 6, 'A1.8', 'Steering an accurate compass course means:', '["Following the GPS course-over-ground exactly with no compass","Pointing the bow at the destination and locking the wheel","Steering by the wake only","Steering the lubber line on the desired compass figure and checking against a transit/landmark"]'::jsonb, 3, 'Answer D. Keep the compass card steady on the ordered course at the lubber line, cross-checking with a transit or fixed mark to detect set.'),
  ('bm2:A-010', 'BM-II', 6, 'A1.9', 'On VHF, the correct spoken word that precedes a DISTRESS call is:', '["SEELONCE","PAN-PAN","SECURITE","MAYDAY (spoken three times)"]'::jsonb, 3, 'Answer D. A distress call is preceded by MAYDAY spoken three times — used only when a vessel or person is in grave and imminent danger.'),
  ('bm2:A-011', 'BM-II', 6, 'A1.9', 'The VHF urgency signal, used for an urgent message about the safety of a vessel or person but not in grave and imminent danger, is:', '["SECURITE","PAN-PAN (spoken three times)","MAYDAY","MAYDAY RELAY"]'::jsonb, 1, 'Answer B. PAN-PAN (three times) is the urgency signal — a very urgent message concerning the safety of a vessel/person, short of grave and imminent danger.'),
  ('bm2:A-012', 'BM-II', 6, 'A1.9', 'The VHF safety signal SECURITE is used to introduce:', '["A navigational or meteorological warning","A routine radio check","A distress message","A request to change channel"]'::jsonb, 0, 'Answer A. SECURITE (three times) introduces an important navigational or meteorological warning.'),
  ('bm2:A-013', 'BM-II', 6, 'A1.9', 'Which VHF channel is the international distress, safety and calling channel?', '["Channel 6","Channel 16","Channel 80","Channel 72"]'::jsonb, 1, 'Answer B. Channel 16 (156.8 MHz) is the international distress, safety and calling channel and must be monitored.'),
  ('bm2:A-014', 'BM-II', 6, 'A1.9', 'A DSC distress alert on VHF is normally transmitted on:', '["Channel 70","Channel 13","Channel 16 by voice only","Channel 6"]'::jsonb, 0, 'Answer A. DSC (Digital Selective Calling) distress alerts are sent on VHF Channel 70; the voice MAYDAY then follows on Channel 16.'),
  ('bm2:A-015', 'BM-II', 6, 'A1.9', 'The single most important reason a MAYDAY voice message must include the vessel''s position is that it:', '["Tells rescuers where to search and is required to fix the casualty","Confirms the working channel","Records the time of day","Identifies the radio licence"]'::jsonb, 0, 'Answer A. Position is the most safety-critical element of a MAYDAY: it tells SAR units where to go.'),
  ('bm2:A-016', 'BM-II', 6, 'A1.9', 'Deliberately making a false distress call on VHF is:', '["Permitted on Channel 16 only","Allowed if cancelled within an hour","A serious offence that wastes SAR resources and endangers others","Acceptable for a radio test"]'::jsonb, 2, 'Answer C. Misuse of distress channels and false alerts is a serious offence; it diverts SAR assets and endangers genuine casualties.'),
  ('bm2:A-017', 'BM-II', 6, 'A1.9', 'Before transmitting a routine call on a busy VHF working channel you should:', '["Whistle into the microphone","Transmit immediately on Channel 16","Listen first to ensure the channel is clear so you do not interfere with other traffic","Use the distress channel"]'::jsonb, 2, 'Answer C. Always listen before transmitting so you do not interfere; use the correct working channel and keep messages brief and clear.'),
  ('bm2:B17-001', 'BM-II', 6, 'B17.15', 'The particular danger of severe wind and heavy rolling in a following sea is that it can:', '["Increase freeboard","Lead to broaching or a reduction of stability on a wave crest, risking capsize","Stop the engine","Improve stability"]'::jsonb, 1, 'Answer B. In a following sea the vessel can be picked up, surf and broach, and lose stability on a crest — a recognised capsize risk in severe conditions.'),
  ('bm2:B17-002', 'BM-II', 6, 'B17.16', 'Not exceeding the vessel''s load capacity matters chiefly because overloading:', '["Reduces freeboard and stability and removes the reserve of safety, risking swamping or capsize","Helps in rough seas","Wears the paint","Slows the boat only"]'::jsonb, 0, 'Answer A. Overloading reduces freeboard and stability and erodes the safety margin, making swamping or capsize far more likely.'),
  ('bm2:B17-003', 'BM-II', 6, 'B17.17', 'Before anyone enters an enclosed space (e.g. a sealed locker, tank or void) the principal hazard to consider is:', '["Bright light","Cold water","Noise","A dangerous (oxygen-deficient or toxic/flammable) atmosphere"]'::jsonb, 3, 'Answer D. Enclosed spaces may have oxygen-deficient, toxic or flammable atmospheres; the atmosphere must be tested and made safe first.'),
  ('bm2:B17-004', 'BM-II', 6, 'B17.17', 'Safe entry into an enclosed space requires, as a minimum:', '["Just opening the hatch and climbing in","Atmosphere testing, ventilation, a permit/authorisation, a standby person outside and a means of rescue","Holding your breath","One quick look only"]'::jsonb, 1, 'Answer B. Enclosed-space entry needs testing, ventilation, authorisation, a standby/attendant outside and rescue arrangements — never enter unprepared.'),
  ('bm2:B17-005', 'BM-II', 6, 'B17.17', 'If a person collapses inside an enclosed space, an untrained rescuer who rushes in to help typically:', '["Saves the casualty easily","Improves the air","Becomes a second casualty from the same dangerous atmosphere","Is unaffected"]'::jsonb, 2, 'Answer C. Many enclosed-space deaths are would-be rescuers overcome by the same atmosphere; raise the alarm and use proper equipment, never rush in.'),
  ('bm2:B17-006', 'BM-II', 6, 'B17.15', '''Free surface effect'' from liquid moving in a partly filled tank or bilge:', '["Reduces stability because the shifting liquid moves the centre of gravity to the low side","Only matters at anchor","Has no effect","Increases stability"]'::jsonb, 0, 'Answer A. A free liquid surface lets the liquid surge to the low side, effectively raising G and reducing stability — keep tanks pressed up or empty and bilges dry.'),
  ('bm2:B11-001', 'BM-II', 7, 'B11.1', 'Daily pre-start checks on a diesel installation should include checking the:', '["Chart folio","Paint condition only","Oil level, coolant level, fuel level/water trap, belts, and battery condition","Radio volume"]'::jsonb, 2, 'Answer C. Daily checks: lubricating-oil and coolant levels, fuel and water-separator, drive belts and battery state — before starting.'),
  ('bm2:B11-002', 'BM-II', 7, 'B11.1', 'A correctly maintained battery for engine starting should have its terminals:', '["Painted over","Loose for easy removal","Disconnected at sea","Clean, tight and lightly protected against corrosion, with electrolyte at the correct level where applicable"]'::jsonb, 3, 'Answer D. Battery terminals must be clean and tight with corrosion protection; loose/corroded terminals cause starting failures and voltage drop.'),
  ('bm2:B11-003', 'BM-II', 7, 'B11.3', 'An engine high-temperature alarm or shut-off device exists to:', '["Save fuel","Indicate low fuel","Warn of (or prevent) overheating before serious engine damage occurs","Increase power"]'::jsonb, 2, 'Answer C. Safety/shut-off devices warn of or stop the engine on overheating or low oil pressure to prevent catastrophic damage.'),
  ('bm2:B11-004', 'BM-II', 7, 'B11.4', 'While the engine is running, a quick visual ''running check'' includes watching for:', '["The flag","The colour of the deck","The radio channel","Abnormal exhaust colour/smoke, cooling-water flow, oil pressure and temperature, and unusual noise or vibration"]'::jsonb, 3, 'Answer D. Running checks: exhaust colour, cooling-water telltale flow, oil pressure/temperature gauges and any unusual noise/vibration.'),
  ('bm2:B11-005', 'BM-II', 7, 'B11.5', 'Blue smoke from a diesel exhaust generally indicates:', '["Too much cooling water","Oil being burnt (e.g. worn rings or overfilled sump)","Normal running","Correct fuel mix"]'::jsonb, 1, 'Answer B. Blue exhaust smoke indicates lubricating oil being burnt; black = over-fuelling/overload, white = water or unburnt fuel.'),
  ('bm2:B11-006', 'BM-II', 7, 'B11.5', 'The engine suddenly overheats with no cooling-water flow from the exhaust. The first thing to check is the:', '["Steering","Fuel gauge","Battery voltage","Raw-water intake (seacock open?) and strainer/impeller for a blockage"]'::jsonb, 3, 'Answer D. Loss of raw-water flow points to a closed seacock, blocked strainer or failed impeller; check these first to avoid overheating damage.'),
  ('bm2:B11-007', 'BM-II', 7, 'B11.5', 'If a diesel engine will not start and turns over normally but no fuel reaches it, a likely cause is:', '["Flat battery","Wrong propeller","Air in the fuel system or a blocked fuel filter — bleed/replace as needed","Open seacock"]'::jsonb, 2, 'Answer C. If it cranks but won''t fire, suspect fuel: air in the system, blocked filter or empty tank — bleed the system and check filters.'),
  ('bm2:B11-008', 'BM-II', 7, 'B11.2', 'Routine maintenance intervals for engine oil and filters should be:', '["As specified by the manufacturer''s manual, by running hours or calendar, whichever comes first","Only after a breakdown","Whenever convenient","Never, if it runs"]'::jsonb, 0, 'Answer A. Follow the manufacturer''s schedule (running hours/calendar) for oil and filter changes to keep the machinery reliable.'),
  ('bm2:B11-009', 'BM-II', 7, 'B11.3', 'Before working on machinery (e.g. the propeller shaft or impeller), the engine must be:', '["Put in gear","Left idling","Stopped and the start isolated (key out/battery isolator off) so it cannot be started accidentally","Run at half speed"]'::jsonb, 2, 'Answer C. Isolate the engine (stop, remove key, switch off the battery isolator) before working on it so it cannot start and injure you.'),
  ('bm2:B1-001', 'BM-II', 8, 'B1.1', 'On sighting a person fall overboard, the first immediate actions are to:', '["Drop the anchor immediately","Shout ''man overboard'', throw a lifebuoy, post a pointer to keep the casualty in sight and press the MOB button","Turn 180 degrees at full speed","Stop the engine and call the owner"]'::jsonb, 1, 'Answer B. Raise the alarm, throw buoyancy at once, detail a dedicated lookout to point continuously, and mark the position (GPS MOB).'),
  ('bm2:B1-002', 'BM-II', 8, 'B1.1', 'The danger of a propeller to a person in the water during MOB recovery means you should:', '["Keep full power on until contact is made","Stop the engine (or take it out of gear) before the casualty comes alongside","Reverse hard alongside the casualty","Approach with the casualty on the windward bow under power throughout"]'::jsonb, 1, 'Answer B. The propeller must be stopped or in neutral before the casualty is alongside to avoid a fatal injury.'),
  ('bm2:B1-003', 'BM-II', 8, 'B1.10', 'Conducting a search in reduced visibility for a person overboard, the boatmaster should:', '["Stop all watch and rely on radar only","Switch off the engine and wait","Post extra lookouts, reduce speed, use a systematic search pattern and sound signals, and alert the Coast Guard","Increase speed to cover more area"]'::jsonb, 2, 'Answer C. Bad-weather/low-visibility SAR needs extra lookouts, safe slow speed, a methodical pattern, sound/light signals and early Coast Guard notification.'),
  ('bm2:B1-004', 'BM-II', 8, 'B1.10', 'An expanding square search pattern is most appropriate when:', '["The casualty''s position is known fairly accurately and a single vessel searches outward from it","Searching at night with no datum","Two vessels search in parallel tracks","The position is completely unknown over a huge area"]'::jsonb, 0, 'Answer A. The expanding square is used by a single unit from a reasonably known datum, searching in growing concentric legs.'),
  ('bm2:B1-005', 'BM-II', 8, 'B1.11', 'When choosing a place to beach a sinking vessel deliberately, you should prefer:', '["The nearest reef","A steep rocky lee shore","A gently shelving sheltered beach of sand or mud, clear of obstructions, ideally to windward of the shore","Anywhere with deep water close in"]'::jsonb, 2, 'Answer C. Beaching is safest on a gentle sand/mud shore, sheltered, free of rocks, where the vessel can be re-floated and people landed safely.'),
  ('bm2:B1-006', 'BM-II', 8, 'B1.2', 'If the main engine fails in a confined channel with a foul tide, the prudent first action is usually to:', '["Abandon ship at once","Let go the anchor to stop the vessel drifting into danger while you assess","Send a MAYDAY immediately","Restart repeatedly at full throttle"]'::jsonb, 1, 'Answer B. Anchoring stops uncontrolled drift and buys time to diagnose and to call for help if needed.'),
  ('bm2:B1-007', 'BM-II', 8, 'B1.3', 'On total loss of steering, an effective immediate method to maintain some directional control on a twin-screw vessel is to:', '["Go full astern","Climb the mast to rig a sail","Drop both anchors","Steer by adjusting the relative thrust of the two engines"]'::jsonb, 3, 'Answer D. With twin screws you can steer by differential engine power; on a single screw a drogue or jury rudder may be rigged.'),
  ('bm2:B1-008', 'BM-II', 8, 'B1.4', 'Immediately after a collision your first priorities are to:', '["Apportion blame in the log","Lower all anchors","Check for injuries, assess flooding/damage and stability, stand by the other vessel and be ready to render assistance","Steam away quickly"]'::jsonb, 2, 'Answer C. After a collision: people first (injuries), then assess damage/flooding and stability, render assistance and exchange details; do not leave the scene.'),
  ('bm2:B1-009', 'BM-II', 8, 'B1.5', 'After running aground on a falling tide the WORST general action is to:', '["Immediately drive full ahead to force her off, risking further damage and flooding","Check for hull damage and ingress","Sound around the vessel to find deep water","Reduce draught/heel and consider kedging off on the rising tide"]'::jsonb, 0, 'Answer A. Driving hard ahead can hole the hull and worsen flooding; assess damage first and refloat carefully, often on the rising tide.'),
  ('bm2:B1-010', 'BM-II', 8, 'B1.6', 'Faced with a serious medical emergency offshore beyond your training, the correct step is to:', '["Anchor and wait until morning","Make a PAN-PAN (or MAYDAY if life-threatening), request medical advice/evacuation and give first aid within your competence","Administer any drugs you can find","Continue the passage and hope it improves"]'::jsonb, 1, 'Answer B. Seek radio medical advice and assistance (PAN-PAN/MAYDAY as appropriate), and give first aid only within your competence.'),
  ('bm2:B1-011', 'BM-II', 8, 'B1.7', 'Which class of fire is burning electrical equipment, and what must you NOT use on it?', '["Electrical fire; do not use water or foam — isolate the supply and use CO2 or dry powder","Class B; do not use dry powder","Class F; do not use CO2","Class A; do not use foam"]'::jsonb, 0, 'Answer A. Live-electrical fires must not be fought with water/foam (conductive); isolate the supply and use CO2 or dry powder.'),
  ('bm2:B1-012', 'BM-II', 8, 'B1.7', 'A galley fat/cooking-oil fire (Class F) is best tackled with:', '["Sand thrown from windward","A jet of water","A wet chemical (Class F) or fire blanket; never water","A CO2 flood only"]'::jsonb, 2, 'Answer C. Class F fat fires need a wet-chemical extinguisher or a fire blanket to smother; water causes a violent flare-up.'),
  ('bm2:B1-013', 'BM-II', 8, 'B1.9', 'The boatmaster''s duty regarding life-saving appliances in an emergency is to:', '["Locate them when the emergency starts","Rely on passengers to find them","Keep them locked until told otherwise","Know where every LSA item is, how to deploy it, and ensure crew/passengers can use it"]'::jsonb, 3, 'Answer D. The person in charge must know the location and use of all LSA and be able to direct their deployment without delay.'),
  ('bm2:B1-014', 'BM-II', 8, 'B1.2', 'If an outboard''s kill-cord is pulled and the engine stops while under way, the immediate concern is that:', '["The fuel tank will explode","Nothing — the boat is now safe","The boat may continue in an uncontrolled circle if a crew is thrown out and the helm is unattended — refit the cord and regain control","The radio will fail"]'::jsonb, 2, 'Answer C. A kill cord stops the engine if the helmsman is displaced, preventing the classic ''circle of death''; refit it and regain control safely.'),
  ('bm2:B8-001', 'BM-II', 8, 'B8.1', 'Before getting under way the safety announcement to passengers (Reg. VIII/8) must cover at least:', '["The lunch menu","The vessel''s top speed","The crew''s home addresses","Location and use of lifejackets (with a demonstration), emergency exits, and what to do in an emergency"]'::jsonb, 3, 'Answer D. The pre-departure briefing covers lifejacket location/donning (demonstrated), exits/muster, and emergency actions.'),
  ('bm2:B8-002', 'BM-II', 8, 'B8.2', 'Disposition of passengers to maintain stability and trim means the boatmaster should:', '["Put everyone on the bow","Let everyone sit where they like","Keep all passengers standing","Distribute people so the vessel is not overloaded on one side or end, keeping a safe trim and avoiding free movement in a seaway"]'::jsonb, 3, 'Answer D. Passengers must be spread to keep the boat upright and properly trimmed; crowding to one side/end can dangerously reduce stability.'),
  ('bm2:B8-003', 'BM-II', 8, 'B8.3', 'The passenger number and reporting system (Reg. VIII/7) exists so that:', '["The number of persons on board is known and recorded ashore, and never exceeds the certified maximum","Passengers get a souvenir","Crew can be reduced","The owner can bill correctly"]'::jsonb, 0, 'Answer A. Knowing and recording the exact number on board (and not exceeding the certificate) is vital for SAR accountability and stability.'),
  ('bm2:B8-004', 'BM-II', 8, 'B8.4', 'Knowledge of emergency instructions and orderly evacuation (Reg. VIII/10) for a Grade 2 vessel requires the boatmaster to:', '["Evacuate only the crew","Improvise on the day","Rely on passengers to organise themselves","Have a plan for mustering, briefing and evacuating passengers in order, suited to the vessel''s size and area"]'::jsonb, 3, 'Answer D. There must be a practised plan for orderly muster and evacuation appropriate to the vessel and operating area, directed by the crew.'),
  ('bm2:B8-005', 'BM-II', 8, 'B8.5', 'Demonstrating personal life-saving appliances to passengers means showing them:', '["How to put on and adjust a lifejacket correctly, including any light/whistle and child versions","The price of the equipment","Only where the lifejackets are stowed","How to inflate the liferaft"]'::jsonb, 0, 'Answer A. The crew must be able to demonstrate correct donning and adjustment of lifejackets (and their attachments) to passengers.'),
  ('bm2:B8-006', 'BM-II', 8, 'B8.2', 'Carrying more passengers than the certificate permits is dangerous mainly because it:', '["Slows the boat","Improves the ride","Saves fuel","Reduces freeboard and stability and removes the safety margin, and is also unlawful"]'::jsonb, 3, 'Answer D. Overloading reduces freeboard/stability, removes reserve buoyancy and is illegal; the certified maximum must never be exceeded.'),
  ('bm2:B8-007', 'BM-II', 8, 'B8.4', 'During an orderly evacuation of passengers the crew should:', '["Evacuate in the dark to save time","Keep passengers calm, direct them to muster/exit points, assist the vulnerable, and account for everyone","Let passengers decide","Leave first to prepare the dock"]'::jsonb, 1, 'Answer B. Orderly evacuation: keep people calm, direct them to muster/exits, help the vulnerable, and account for all persons — crew lead, not leave.'),
  ('bm2:B13-001', 'BM-II', 9, 'B13.3', 'Under MARPOL, the disposal into the sea of all plastics, including synthetic ropes and garbage bags, is:', '["Allowed if ground up","Totally prohibited everywhere","Allowed beyond 12 miles","Allowed at night only"]'::jsonb, 1, 'Answer B. MARPOL Annex V prohibits the disposal of all plastics into the sea anywhere — they must be retained and landed ashore.'),
  ('bm2:B13-002', 'BM-II', 9, 'B13.2', 'When changing lubricating oil, the key precaution to prevent marine pollution is to:', '["Contain all old oil and drips and keep them clear of anything draining to the sea, landing them at a reception facility","Let spills go to the bilge","Mix oil with detergent and discharge it","Pour the old oil over the side while moving"]'::jsonb, 0, 'Answer A. Old oil and every drip must be contained and kept away from drains/bilge that reach the sea, then landed at a reception facility.'),
  ('bm2:B13-003', 'BM-II', 9, 'B13.2', 'Before pumping out the bilge, the boatmaster must:', '["Pump only at night","Add oil to lubricate the pump","Check the bilge water is not contaminated with oil; oily water must not be discharged but landed ashore","Pump regardless of content"]'::jsonb, 2, 'Answer C. Oily bilge water must never be pumped overboard; check for oil first and, if present, retain it for shore disposal.'),
  ('bm2:B13-004', 'BM-II', 9, 'B13.1', 'MARPOL is the international convention dealing with:', '["Prevention of pollution from ships","Load lines","Crew certification","Collision avoidance"]'::jsonb, 0, 'Answer A. MARPOL is the International Convention for the Prevention of Pollution from Ships, covering oil, chemicals, sewage, garbage and air pollution.'),
  ('bm2:B13-005', 'BM-II', 9, 'B13.1', 'A small fuel spill at the berth during refuelling should be dealt with by:', '["Spreading it with detergent","Stopping the source, containing it with absorbent material, and reporting it as required","Hosing it into the sea","Ignoring it if small"]'::jsonb, 1, 'Answer B. Stop the source, contain with absorbents, and report as required; never disperse oil into the sea with detergent.'),
  ('bm2:B13-006', 'BM-II', 9, 'B13.2', 'A drip tray under the engine and a clean bilge help prevent pollution by:', '["Reducing noise","Cooling the engine","Improving speed","Catching oil leaks so contaminated water is not pumped overboard"]'::jsonb, 3, 'Answer D. A drip tray and clean bilge catch oil leaks, keeping bilge water clean so it does not become oily and unlawful to discharge.'),
  ('bm2:B13-007', 'BM-II', 9, 'B13.1', 'Sewage and garbage management on a small passenger vessel should follow:', '["Owner''s preference","Discharge everything offshore","MARPOL and local requirements — retain and land ashore where discharge is restricted, and never dispose of plastics at sea","No rules inshore"]'::jsonb, 2, 'Answer C. Sewage/garbage are handled under MARPOL and local rules; in restricted/inshore waters retain and land ashore, and plastics are never discharged.'),
  ('bm2:B6-001', 'BM-II', 11, 'B6.1', 'The person in charge of the vessel must, regarding life-saving and fire-fighting appliances:', '["Test them only annually","Leave checks to passengers","Assume the owner has dealt with them","Be satisfied that they are present, in date and properly maintained before sailing"]'::jsonb, 3, 'Answer D. Reg. B6.1: the boatmaster must satisfy himself that LSA and FFA meet statutory requirements and are properly maintained before the voyage.'),
  ('bm2:B6-002', 'BM-II', 11, 'B6.1', 'Portable fire extinguishers on board should be checked to confirm they are:', '["Empty for safety","Stowed in a locked locker","Painted the right colour only","In date (within service period), correctly charged/pressurised, accessible and undamaged"]'::jsonb, 3, 'Answer D. Extinguishers must be in service date, charged (gauge in the green where fitted), unobstructed and undamaged — checked before sailing.'),
  ('bm2:B6-003', 'BM-II', 11, 'B6.5', '''Buoyant apparatus'' (e.g. buoyant seats/floats) must be maintained so that it:', '["Is the right colour","Retains its buoyancy and securing/floatation is intact, with grab-lines and markings serviceable","Is stowed below deck","Looks tidy"]'::jsonb, 1, 'Answer B. Buoyant apparatus must keep its buoyancy; check the body, grab-lines, lashings and markings so it will float and support people when needed.'),
  ('bm2:B6-004', 'BM-II', 11, 'B6.1', 'Lifejackets carried for passengers should be:', '["Inflated and ready at all times","Kept locked away","One size only, stowed centrally","Of suitable sizes (including child sizes if children carried), in good condition, readily accessible and sufficient in number"]'::jsonb, 3, 'Answer D. Sufficient serviceable lifejackets of appropriate sizes (incl. children where carried) must be readily accessible to all persons on board.'),
  ('bm2:B6-005', 'BM-II', 11, 'B6.1', 'A liferaft''s annual servicing is important because it:', '["Confirms the raft will inflate correctly and that its equipment, gas and hydrostatic release are in date and serviceable","Is only a paperwork formality","Repaints the container","Reduces its weight"]'::jsonb, 0, 'Answer A. Servicing verifies inflation, the gas system, the equipment pack and the HRU/painter so the raft works when needed; it must be kept in date.'),
  ('bm2:B6-006', 'BM-II', 11, 'B6.1', 'Lifebuoys (ring buoys) carried for instant MOB use should be:', '["Kept in the wheelhouse only","Lashed down tightly","Readily accessible on deck, with self-igniting light and/or buoyant line as fitted, ready for immediate throwing","Stowed below in a locker"]'::jsonb, 2, 'Answer C. Lifebuoys must be instantly available on deck, with their lights/lines serviceable, so one can be thrown the instant someone goes overboard.'),
  ('bm2:B7-001', 'BM-II', 11, 'B7.1', 'Which of the following is a recognised distress signal under Annex IV of the Collision Regulations?', '["Continuous sounding of a fog-signalling apparatus","A black ball hoisted","A single white flare","Three short blasts"]'::jsonb, 0, 'Answer A. Annex IV distress signals include the continuous sounding of any fog-signalling apparatus, red flares, SOS, MAYDAY, etc.'),
  ('bm2:B7-002', 'BM-II', 11, 'B7.1', 'A red hand-held flare or red parachute rocket is used to:', '["Signal you are altering course","Indicate distress and help rescuers locate you","Show you are at anchor","Mark a fishing net"]'::jsonb, 1, 'Answer B. Red pyrotechnics (hand flare/parachute rocket) are distress signals; red = distress, used to attract attention and pinpoint position.'),
  ('bm2:B7-003', 'BM-II', 11, 'B7.1', 'An orange smoke signal is primarily effective as a distress signal:', '["Underwater","In fog only","At night","By day, to mark position for searching aircraft or vessels"]'::jsonb, 3, 'Answer D. Orange smoke is a daytime distress signal, giving a position datum and wind indication for aircraft/vessels; flares are better by night.'),
  ('bm2:B7-004', 'BM-II', 11, 'B7.1', 'Slowly and repeatedly raising and lowering arms outstretched to each side is:', '["An anchoring signal","A recognised distress signal","A signal to overtake","A greeting"]'::jsonb, 1, 'Answer B. Raising and lowering outstretched arms is one of the Annex IV distress signals indicating need of assistance.'),
  ('bm2:B7-005', 'BM-II', 11, 'B7.2', 'When the Coast Guard receives your distress signal, you should expect them to:', '["Acknowledge, coordinate the SAR response, task assets and maintain communications with you","Charge a fee before responding","Ignore small craft","Wait until daylight"]'::jsonb, 0, 'Answer A. The Coast Guard/MRCC acknowledges, coordinates SAR, tasks vessels/aircraft and keeps communications going until the situation is resolved.'),
  ('bm2:B7-006', 'BM-II', 11, 'B7.1', 'An EPIRB, once activated, sends a distress alert via:', '["VHF Channel 16 voice only","A loud-hailer","A signal lamp","The Cospas-Sarsat satellite system, with a coded identity and (if GPS-equipped) position"]'::jsonb, 3, 'Answer D. An EPIRB transmits a coded 406 MHz distress alert through the Cospas-Sarsat satellites, identifying the vessel and giving position if GPS-equipped.'),
  ('bm2:B18-001', 'BM-II', 12, 'B18.1', 'The boatmaster''s responsibility for the first-aid kit is to:', '["Use it only for the crew","Assume it is complete","Keep it locked away","Know its location and contents, keep it stocked and in date, and know how to use the items"]'::jsonb, 3, 'Answer D. The boatmaster must know where the kit is, what it contains and how to use it, and keep it complete and in date.'),
  ('bm2:B18-002', 'BM-II', 12, 'B18.1', 'A marine first-aid kit should as a minimum contain:', '["Dressings, bandages, antiseptic, adhesive plasters, gloves and basic instructions","Charts","Engine spares","Flares"]'::jsonb, 0, 'Answer A. A first-aid kit holds dressings, bandages, antiseptic, plasters, protective gloves and clear instructions for use.'),
  ('bm2:B18-003', 'BM-II', 12, 'B18.1', 'If first-aid items are used or found out of date during a check, the boatmaster should:', '["Borrow from passengers","Replace/restock them promptly so the kit is complete before the next voyage","Remove the kit","Leave the gap until the next service"]'::jsonb, 1, 'Answer B. Used or expired items must be replaced promptly so the kit is complete and serviceable before sailing.'),
  ('bm2:B18-004', 'BM-II', 12, 'B18.1', 'The simplest immediate first-aid action for a small bleeding wound is to:', '["Apply direct pressure with a clean dressing and elevate if possible","Leave it open","Pour fuel on it","Apply a tourniquet at once"]'::jsonb, 0, 'Answer A. Direct pressure with a clean dressing (and elevation) controls most minor bleeding; tourniquets are only for severe, uncontrollable limb bleeding.'),
  ('bm2:B18-005', 'BM-II', 12, 'B18.1', 'For a suspected spinal injury after a fall on board, basic first-aid principle is to:', '["Move the casualty quickly to the cabin","Avoid unnecessary movement, keep the casualty still and support the head/neck while summoning help","Sit them upright at once","Have them walk it off"]'::jsonb, 1, 'Answer B. With a suspected spinal injury, minimise movement, support the head/neck and keep the casualty still while getting medical help — within your competence.')
on conflict (id) do update set
  course_code = excluded.course_code,
  module_seq  = excluded.module_seq,
  ref         = excluded.ref,
  stem        = excluded.stem,
  opts        = excluded.opts,
  correct     = excluded.correct,
  expl        = excluded.expl;

-- ---- Module-content (reader/deck-paden + gecureerde quizlijst) ----
-- Storage-paden in bucket 'course-content'. Volgnummer = modules.sequence.

update modules m set
  reader_path = 'bm2/readers/M01.pdf',
  deck_path   = 'bm2/decks/M01.pdf',
  quiz_ids    = '["bm2:B2-030","bm2:B2-031","bm2:B2-033","bm2:B3-004","bm2:B3-005","bm2:B3-006","bm2:B3-007","bm2:B3-008"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-II' and m.sequence = 1;
update modules m set
  reader_path = 'bm2/readers/M02.pdf',
  deck_path   = 'bm2/decks/M02.pdf',
  quiz_ids    = '["bm2:B3-001","bm2:B3-002","bm2:B3-003","bm2:B3-004","bm2:B3-005","bm2:B3-006","bm2:B3-007","bm2:B3-008","bm2:B3-009","bm2:B9-001","bm2:B9-002","bm2:B9-003","bm2:B9-004","bm2:B9-005","bm2:B9-006"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-II' and m.sequence = 2;
update modules m set
  reader_path = 'bm2/readers/M03.pdf',
  deck_path   = 'bm2/decks/M03.pdf',
  quiz_ids    = '["bm2:B10-001","bm2:B10-002","bm2:B10-003","bm2:B10-004","bm2:B10-005","bm2:B10-006","bm2:B14-001","bm2:B14-002","bm2:B14-003","bm2:B14-004","bm2:B14-005","bm2:B14-006","bm2:B5-001","bm2:B5-002","bm2:B5-003","bm2:B5-004","bm2:B5-005","bm2:B5-006","bm2:B5-007","bm2:B5-008"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-II' and m.sequence = 3;
update modules m set
  reader_path = 'bm2/readers/M04.pdf',
  deck_path   = 'bm2/decks/M04.pdf',
  quiz_ids    = '["bm2:B2-001","bm2:B2-002","bm2:B2-003","bm2:B2-004","bm2:B2-005","bm2:B2-006","bm2:B2-007","bm2:B2-008","bm2:B2-009","bm2:B2-010","bm2:B2-011","bm2:B2-012","bm2:B2-013","bm2:B2-014","bm2:B2-015","bm2:B2-016","bm2:B2-017","bm2:B2-018","bm2:B2-019","bm2:B2-020","bm2:B2-021","bm2:B2-022","bm2:B2-023","bm2:B2-024","bm2:B2-025","bm2:B2-026","bm2:B2-027","bm2:B2-028","bm2:B2-029","bm2:B2-030","bm2:B2-031","bm2:B2-032","bm2:B2-033","bm2:B2-034"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-II' and m.sequence = 4;
update modules m set
  reader_path = 'bm2/readers/M05.pdf',
  deck_path   = 'bm2/decks/M05.pdf',
  quiz_ids    = '["bm2:B4-001","bm2:B4-002","bm2:B4-003","bm2:B4-004","bm2:B4-005","bm2:B4-006","bm2:B4-007","bm2:B4-008","bm2:B4-009","bm2:B4-010"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-II' and m.sequence = 5;
update modules m set
  reader_path = 'bm2/readers/M06.pdf',
  deck_path   = 'bm2/decks/M06.pdf',
  quiz_ids    = '["bm2:A-001","bm2:A-002","bm2:A-003","bm2:A-004","bm2:A-005","bm2:A-006","bm2:A-007","bm2:A-008","bm2:A-009","bm2:A-010","bm2:A-011","bm2:A-012","bm2:A-013","bm2:A-014","bm2:A-015","bm2:A-016","bm2:A-017","bm2:B17-001","bm2:B17-002","bm2:B17-003","bm2:B17-004","bm2:B17-005","bm2:B17-006"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-II' and m.sequence = 6;
update modules m set
  reader_path = 'bm2/readers/M07.pdf',
  deck_path   = 'bm2/decks/M07.pdf',
  quiz_ids    = '["bm2:B11-001","bm2:B11-002","bm2:B11-003","bm2:B11-004","bm2:B11-005","bm2:B11-006","bm2:B11-007","bm2:B11-008","bm2:B11-009"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-II' and m.sequence = 7;
update modules m set
  reader_path = 'bm2/readers/M08.pdf',
  deck_path   = 'bm2/decks/M08.pdf',
  quiz_ids    = '["bm2:B1-001","bm2:B1-002","bm2:B1-003","bm2:B1-004","bm2:B1-005","bm2:B1-006","bm2:B1-007","bm2:B1-008","bm2:B1-009","bm2:B1-010","bm2:B1-011","bm2:B1-012","bm2:B1-013","bm2:B1-014","bm2:B8-001","bm2:B8-002","bm2:B8-003","bm2:B8-004","bm2:B8-005","bm2:B8-006","bm2:B8-007"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-II' and m.sequence = 8;
update modules m set
  reader_path = 'bm2/readers/M09.pdf',
  deck_path   = 'bm2/decks/M09.pdf',
  quiz_ids    = '["bm2:B13-001","bm2:B13-002","bm2:B13-003","bm2:B13-004","bm2:B13-005","bm2:B13-006","bm2:B13-007"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-II' and m.sequence = 9;
update modules m set
  reader_path = 'bm2/readers/M10.pdf',
  deck_path   = 'bm2/decks/M10.pdf',
  quiz_ids    = '["bm2:B1-011","bm2:B1-012","bm2:B6-001","bm2:B6-002","bm2:B11-007"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-II' and m.sequence = 10;
update modules m set
  reader_path = 'bm2/readers/M11.pdf',
  deck_path   = 'bm2/decks/M11.pdf',
  quiz_ids    = '["bm2:B6-001","bm2:B6-002","bm2:B6-003","bm2:B6-004","bm2:B6-005","bm2:B6-006","bm2:B7-001","bm2:B7-002","bm2:B7-003","bm2:B7-004","bm2:B7-005","bm2:B7-006"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-II' and m.sequence = 11;
update modules m set
  reader_path = 'bm2/readers/M12.pdf',
  deck_path   = 'bm2/decks/M12.pdf',
  quiz_ids    = '["bm2:B18-001","bm2:B18-002","bm2:B18-003","bm2:B18-004","bm2:B18-005"]'::jsonb
from courses c
where m.course_id = c.id and c.code = 'BM-II' and m.sequence = 12;

-- Klaar.
